const fs=require('node:fs'),path=require('node:path');
const css=fs.readFileSync('review/trapper/index.html','utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const img=(file)=>'data:image/jpeg;base64,'+fs.readFileSync(file).toString('base64');
function gallery(dir,title,lead,views,foot){const article=([id,heading,note])=>`<article><h2>${heading}</h2><figure><div class="pair">${['before','after'].map(p=>`<div class="${p}"><div class="label">${p==='before'?'Before':'After'}</div><img loading="lazy" src="${img(path.join(dir,p+'-'+id+'.jpg'))}" alt="${heading} ${p}"></div>`).join('')}</div><figcaption>${note}</figcaption></figure></article>`;fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${css}</style><main><header><small>DEAD-WAVE / EQUIPMENT REVIEW / OCTOBER 2, 2026</small><h1>${title}</h1><p>${lead}</p><p><a href="/review/equipment-night/index.html">All equipment changes</a></p></header><nav>${[['after','After'],['before','Before'],['compare','Side by side']].map(([id,label])=>`<button data-mode="${id}" aria-pressed="${id==='after'}">${label}</button>`).join('')}</nav>${article(views[0])}<div class="grid">${views.slice(1).map(article).join('')}</div><footer><p>${foot}</p><p>Independent crew visual acceptance, full integration and load/FPS verification remain pending.</p></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);console.log(dir+': '+views.length+' comparisons');}
gallery('review/marine-gear','Carried like a complete loadout','Long guns flank the backpack. Paired secondaries cross its center, with additional weapons on the lower mounts.',[
 ['pair','Both Uzis are there','An owned akimbo pair now appears as two stowed guns. Their magazines sit through the grips, and the guns cross the center of the pack.'],
 ['back','Long guns at the sides','Two primaries now sit beside the pack, leaving its center for secondaries.'],
 ['quarter','A clearer silhouette','The back mounts follow the torso and keep the rifle stocks and barrels recognizable.'],
 ['two-pairs','A fully paired loadout','A second pair uses the lower rear mounts; a purchased second issued pistol uses the opposite hip. Guns disappear from their mounts as they are drawn.'],
 ['pair-drawn','Both guns in hand','Drawing akimbo removes both copies from the pack.'],
 ['pair-single','One drawn, one stowed','Single-hand use leaves the other owned Uzi visible.'],
 ['front','Equipment fit','Magazine tops now align with the actual pouches. The vest, shoulder pockets and arm pivots retain their fit.'],
 ['side','Retention and holsters','Added pack compression webbing, buckles, a grab handle and a belt attachment for the holster.'],
 ['head','Chin-strap fit','The helmet straps now run continuously down to the chin instead of stopping short. Headset, microphone, goggles and balaclava were inspected.'],
 ['nvg','Night equipment','Checked with night-vision equipment lowered.'],
 ['bare','Without armor','Inspected the unarmored equipment combination as well as the vest.'],
 ['heavy','Heavy weapons','Checked the side mounts with the minigun and flamethrower.'],
 ['walk','Walking','Inspected the carry rig on the production walk pose.'],
 ['run','Running','Inspected the carry rig on the production run pose.'],
 ['survivor','Shared survivor equipment','Shared pack and strap refinements also reach survivor figures; their individual clothing remains intact.']
],'Seventeen existing carry checks, paired ownership/draw checks and eight unit checks passed. Fifteen production-renderer views. Draw reach coordinates now point toward the new mounts; final animated hand paths still need independent crew review.');
gallery('review/armory/height','An armory window he can reach','The central opening and sill are 82 cm lower, at marine height. The sign remains centered over the cabinet.',[
 ['hq','At marine height','The clear hatch is centered 1.48 m above the cabinet base.'],['player','At the window','The marine now stands in front of the opening rather than beneath it.'],['training','Training Ground','The same corrected hatch is used in Training.'],['wall','Wall integration','The mesh and wall surround retain their approved layout.'],['attachments','Every gun still fits','The finished weapon upgrades fit inside the case at full model size. Primary spacing responds to the fitted magazines and tanks.']
],'148 display, inventory, placement and clearance checks passed after the weapons pass. The existing armory integration test has 27 passes and two old stored-only display expectations that conflict with the approved all-owned display; these remain flagged for the owner.');
const names={m4:'M4',ak:'AK',aa12:'AA-12',shotgun:'Pump shotgun',sniper:'Sniper rifle',minigun:'Minigun',launcher:'Grenade launcher',flamer:'Flamethrower',chainsaw:'Chainsaw',uzi:'Uzi',pistol:'Pistol',revolver:'Revolver'};
const changes={uzi:'Narrower magazine, aligned to the grip rake and seated through the grip. The reload keeps its original hand and muzzle anchors.',pistol:'Extended magazine is one continuous body, following the grip angle with its feed end fixed.',ak:'The extended curved magazine no longer has a second chopped-off magazine hanging below its floorplate.',m4:'A continuous extended magazine; existing sights, light, stock, muzzle and handguard retained.',aa12:'Larger drum remains seated at the feed tower rather than expanding upward from its center.',shotgun:'The capacity upgrade now visibly extends the under-barrel magazine tube.',sniper:'The extended box magazine remains seated in the chassis.',minigun:'The larger ammunition box grows downward from its feed connection.',flamer:'The bigger-tank upgrade now changes the tank assembly, including its straps, caps and hoses.',launcher:'Inspected the drum, barrel, sights, foregrip and stock. No magazine-extension option exists for this weapon.',chainsaw:'Inspected the bar, moving chain, handles, body and guard. The model is retained.',revolver:'Inspected the cylinder, barrel, hammer, grip and trigger guard. The model is retained.'};
const views=[['uzi-side','Uzi: magazine through the grip',changes.uzi],['uzi-upgrades','Uzi: fitted upgrades','The extended magazine stays continuous and seated. The existing suppressor and heavy sleeve are shown for model inspection; the live armory still permits only one magazine/heavy mod at a time.']];
for(const[k,name]of Object.entries(names))for(const v of['side','three','upgrades']){if(k==='uzi'&&v!=='three')continue;views.push([k+'-'+v,name+(v==='side'?' · side':v==='three'?' · angled':' · attachment inspection'),changes[k]]);}
views.push(['m240','Watchman MG: connected tripod','All three legs meet the traversing head and now have ground pads. Weapon position, firing and carry behavior are retained.'],['mortar','Mortar: open bore and seated base','Opened the capped muzzle, added bore depth, connected the bipod and seated the breech cup on the baseplate. Original aiming pivot retained.'],['knife','Issue knife','Inspected the blade, edge, guard and grip; retained.'],['machete','Machete','Inspected blade-to-handle fit, edge and guard; retained.']);
gallery('review/weapon-fidelity','Weapons that fit together','A complete visual inspection of twelve handheld weapons, two blades and both crewed weapons, with repairs focused on the faults found.',views,'Forty production-renderer views at matching angles, framed to each model. Eleven upgrade round trips, seven actual Uzi reload poses and ten assembled-copy checks passed. Backpack and display copies now return magazines, slides, bolts and drums to their assembled poses without moving the live weapon.');
const dir='review/equipment-night';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dead-Wave · Equipment pass</title><style>${css}a{color:#e4c486}.grid a{display:block;text-decoration:none}img{width:100%;height:auto;display:block}</style><main><header><small>DEAD-WAVE / OCTOBER 2, 2026</small><h1>Ready for your morning inspection</h1><p>The new carry layout, a lower armory hatch, fitted marine equipment and the weapon repairs. Each review has before, after and side-by-side views.</p></header><div class="grid">${[['marine-gear','The complete loadout','pair','Primaries beside the backpack. Paired Uzis crossed in the center, with extra pairs below.'],['armory/height','A reachable armory','hq','The mesh opening and sill lowered to marine height.'],['weapon-fidelity','A full weapon inspection','uzi-side','The Uzi feeds through its grip, extensions stay connected, and the emplacement supports are seated.']].map(([p,t,id,n])=>`<article><a href="../${p}/index.html"><h2>${t} →</h2><img src="${img('review/'+p+'/after-'+id+'.jpg')}" alt="${t}"><p>${n}</p></a></article>`).join('')}</div><footer><p>Changes are in the working game. Targeted checks passed; independent crew acceptance and the full integration/performance checks are pending. Claude and Grokbot were kept informed through the crew board.</p></footer></main></html>`);
