const fs=require('node:fs'),path=require('node:path'),dir=__dirname;
const css=fs.readFileSync('review/trapper/index.html','utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
 ['training','Screened armory','Expanded-metal mesh covers the front, with a small clear hatch in the center. The full-size gun lineup remains visible behind it.'],
 ['player','A central service opening','A framed opening and narrow counter break up the mesh without obscuring the cabinet with a solid panel.'],
 ['wall','A cleaner Training Ground wall','The redundant CIF / SUPPLY / ARMORY wall lettering is removed. Each terminal retains its own label.'],
 ['hq','Built into the wall','A deep steel surround, anchor bolts and lower apron close the cabinet back to the HQ wall. The Armory sign is centered on the cabinet and hatch.'],
 ['attachments','The gun display is preserved','All eleven gun types retain their original scale and attachment clearance behind the new security screen.']
];
const article=([id,title,note])=>`<article><h2>${title}</h2><figure><div class="pair">${['before','after'].map(p=>`<div class="${p}"><div class="label">${p==='before'?'Before':'After'}</div><img loading="lazy" src="data:image/jpeg;base64,${fs.readFileSync(path.join(dir,p+'-'+id+'.jpg')).toString('base64')}" alt="${title} ${p}"></div>`).join('')}</div><figcaption>${note}</figcaption></figure></article>`;
fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Armory · Mesh service screen</title><style>${css}</style><main><header><small>DEAD-WAVE / ARMORY WALL INTEGRATION / OCTOBER 2, 2026</small><h1>A secured issue window</h1><p>A centered sign, a bolted wall surround, and a mesh front with a clear central hatch.</p></header><nav>${[['after','After'],['before','Before'],['compare','Side by side']].map(([id,label])=>`<button data-mode="${id}" aria-pressed="${id==='after'}">${label}</button>`).join('')}</nav>${article(views[0])}<div class="grid">${views.slice(1).map(article).join('')}</div><footer><p>Matched views in the production game renderer. Focused display, inventory and placement checks pass. The gun display and inventory behavior are unchanged from the approved full-size cabinet.</p><p>Independent visual acceptance, full integration and load/FPS verification remain pending.</p></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('Built five armory comparisons.');
