import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as T from 'three';import * as Fake from '../../tools/tests/fakethree.mjs';
const oldDetails=fs.readFileSync(new URL('details-before.js',import.meta.url),'utf8'),newDetails=fs.readFileSync('assets/world/landmark-details.js','utf8');
const strip=s=>s.slice(0,s.indexOf("  if(o.kind==='dock')"))+s.slice(s.indexOf("  if(o.kind==='wreck')"));assert.equal(strip(newDetails),strip(oldDetails),'other landmark builders unchanged');
const build=(source,options,THREE=T)=>{const c={window:{}};vm.runInNewContext(source,c);return c.window.buildLandmarkDetails(THREE,options);};
let vertices=0;for(const boatSide of[-1,1])for(const slope of[-.15,0,.15]){const o={kind:'dock',halfWidth:1.15,length:9.5,boatSide,ground:(x,z)=>slope*x+.04*z-.7},a=build(oldDetails,o),b=build(newDetails,o);assert.equal(JSON.stringify(a.solids),JSON.stringify(b.solids));for(const p of b.parts){p.updateMatrix();assert([...p.geometry.attributes.position.array,...p.matrix.elements].every(Number.isFinite));vertices+=p.geometry.attributes.position.count;}build(newDetails,o,Fake);}
const current=fs.readFileSync('index.html','utf8'),oldDock=fs.readFileSync(new URL('buildDock-before.txt',import.meta.url),'utf8'),newDock=current.slice(current.indexOf('    function buildDock(d)'),current.indexOf('    function buildBridge(b)'));
function run(source,details,side){const solids=[],platforms=[],parts=[];const paint=new Proxy({}, {get:()=>()=>{}}),c={THREE:T,DOCK_LEN:9.5,DOCK_HW:1.15,LAKE:{level:-3.4},sampleHeight:(x,z)=>side*x*.01,scene:new T.Group(),platforms,poiMat:new T.MeshStandardMaterial(),sayText:k=>k==='story.dock.signTimes'?'00:00 06:00\n12:00 18:00':k,document:{createElement:()=>({width:0,height:0,getContext:()=>paint})},poiBox:(ps,m,w,h,d,x,y,z,ry=0,rz=0,rx=0)=>{const p=new T.Mesh(new T.BoxGeometry(w,h,d),m);p.position.set(x,y,z);p.rotation.set(rx,ry,rz);ps.push(p);},mergeParts:ps=>{parts.push(...ps);return new T.Group();},addSolid:(...a)=>solids.push(a)};c.appendLandmarkDetails=(ps,kind,cx,cz,gy,yaw,o)=>{const d=build(details,{kind,...o,ground:()=>-.6});ps.push(...d.parts);return{theme:d.theme,register:()=>d.solids.forEach(s=>solids.push([cx+s.x*Math.cos(yaw)+s.z*Math.sin(yaw),cz-s.x*Math.sin(yaw)+s.z*Math.cos(yaw),s.r,gy+s.y,gy+s.y+s.h]))};};vm.createContext(c);vm.runInContext(source+';globalThis.run=buildDock;',c);const d={x:0,z:0,yaw:.2,deckY:-2.85};c.run(d);return JSON.parse(JSON.stringify({solids,platforms}));}
for(const s of[-1,1])assert.deepEqual(run(newDock,newDetails,s),run(oldDock,oldDetails,s),'production dock collision/deck contract');
fs.writeFileSync(new URL('geometry-checks.json',import.meta.url),JSON.stringify({cases:6,verticesPerCase:vertices/6,otherBuildersUnchanged:true,finiteGeometry:true,fakeThree:true,productionDockSolidsAndPlatformsUnchanged:true},null,2));
console.log('PASS six dock geometry cases, fake THREE, all other landmark builders unchanged; production deck and solids identical for both boat sides.');
