import fs from 'node:fs';
const root=new URL('./',import.meta.url),pic=(p,id)=>'data:image/jpeg;base64,'+fs.readFileSync(new URL(p+'-'+id+'.jpg',root)).toString('base64');
const css=fs.readFileSync(new URL('../trapper/index.html',root),'utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
['whole','Threshold’s stores, stranded','The front end has dropped onto damaged suspension. A bare hub, folded bonnet and torn tyre make the truck read as an abandoned wreck.'],
['front','This truck is staying here','The missing front wheel exposes the rusted brake disc and spindle. The remaining front tyre is collapsed, with damaged steering gear and scrape marks underneath.'],
['engine','A ruined engine bay','The bonnet has split and folded back. Broken radiator bars, a twisted core and severed hoses expose the damage beneath it.'],
['cargo','Supplies for the twelve','Worn PGB / THRESHOLD markings identify the load. The existing crates and torn canvas remain, with paint losses and an abandoned stretcher at the lowered tailgate.'],
['stretcher','An interrupted recovery','The canvas litter is halfway out of the cargo bed, its handles near the ground. Someone began unloading the medical equipment and never finished.'],
['supplies','A burst medical shipment','The shipping crate has split open. Bandage rolls and wrapped packs spill across broken boards; the medical marking connects the contents to Threshold’s supplies.'],
['approach','The recoverable supplies stay clear','The existing medical pickup keeps its position and open approach. The wreck’s new details provide context around the established objective.']
];
fs.writeFileSync(new URL('index.html',root),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Threshold supply wreck · Before and after</title><style>${css}</style><main><header><small>DEAD-WAVE / THE MEDICAL SUPPLY WRECK</small><h1>The recovery was never finished.</h1><p>Actual in-game pictures: a disabled truck, Threshold’s medical cargo and equipment left halfway out of the bed.</p></header><nav aria-label="Picture comparison"><button data-mode="after" aria-pressed="true">After</button><button data-mode="before" aria-pressed="false">Before</button><button data-mode="compare" aria-pressed="false">Side by side</button></nav>${views.map(([id,title,note],i)=>`${i===1?'<div class="grid">':''}<article><h2>${title}</h2><figure><div class="pair"><div class="before"><div class="label">Before</div><img loading="lazy" src="${pic('before',id)}" alt="${title} before"></div><div class="after"><div class="label">After</div><img loading="lazy" src="${pic('after',id)}" alt="${title} after"></div></div><figcaption>${note}</figcaption></figure></article>${i===views.length-1?'</div>':''}`).join('')}<footer><p>Focused checks passed: all seven objective props and their clear approaches, unchanged wreck positions and collision shapes, unchanged utility truck geometry, and no page errors in the real renderer.</p><p>Independent crew playthrough, full integration and load/FPS acceptance remain pending.</p><a href="../world-story/index.html">Original world photo review</a> · <a href="../relay/index.html">Sato’s relay</a></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('PASS: seven matched medical wreck comparisons built.');
