import fs from 'node:fs';
const root=new URL('./',import.meta.url),pic=(p,id)=>'data:image/jpeg;base64,'+fs.readFileSync(new URL(p+'-'+id+'.jpg',root)).toString('base64');
const css=fs.readFileSync(new URL('../trapper/index.html',root),'utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
['whole','Sato’s relay station','The existing mast now carries patched steelwork, bolted footings and signs of interrupted maintenance. Its location, height and approach remain the same.'],
['station','Work left unfinished','A dropped headset and open tool roll sit beside the repair cabinet. Small practical details connect the equipment to the person who worked here.'],
['rack','Kept running with field repairs','Chipped edges, service wiring and replacement plates dress the existing rack. A wooden cable reel and its chocks sit behind it.'],
['grounding','The connection into the rock','A copper grounding strap follows the ground to a low rock, secured beneath a steel plate. It quietly echoes the story’s connection between the signal and the valley itself.'],
['broken','He pulled the fuse','The open bay has empty ceramic clips and exposed brass contacts. The removed fuse rests below it, making Sato’s action visible in the equipment.'],
['repaired','The connection restored','The existing repaired state now seats the fuse between its contacts, alongside the connected leads and green status light. This is a preview of that existing state.'],
['boots','Prepared for electrical work','The insulated boots sit on a worn rubber work mat beside the abandoned tools. Picking up the boots leaves the mat behind.']
];
fs.writeFileSync(new URL('index.html',root),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sato’s relay · Before and after</title><style>${css}</style><main><header><small>DEAD-WAVE / THE RELAY STATION</small><h1>He pulled the fuse. It didn’t stop.</h1><p>Actual in-game pictures of Sato’s station: opened equipment, abandoned tools and a grounding connection into the rock.</p></header><nav aria-label="Picture comparison"><button data-mode="after" aria-pressed="true">After</button><button data-mode="before" aria-pressed="false">Before</button><button data-mode="compare" aria-pressed="false">Side by side</button></nav>${views.map(([id,title,note],i)=>`${i===1?'<div class="grid">':''}<article><h2>${title}</h2><figure><div class="pair"><div class="before"><div class="label">Before</div><img loading="lazy" src="${pic('before',id)}" alt="${title} before"></div><div class="after"><div class="label">After</div><img loading="lazy" src="${pic('after',id)}" alt="${title} after"></div></div><figcaption>${note}</figcaption></figure></article>${i===views.length-1?'</div>':''}`).join('')}<footer><p>Focused checks passed: all seven objective props, their repair states, footprints and clear approaches; boots pickup/reset; unchanged sites and nearby collision shapes. No page errors in the real renderer.</p><p>Independent crew playthrough, full integration and load/FPS acceptance remain pending.</p><a href="../world-story/index.html">Original world photo review</a> · <a href="../tower/sightline/index.html">Watchtower sightline</a></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('PASS: seven matched relay comparisons built.');
