const fs=require('node:fs'),path=require('node:path'),dir=__dirname;
const css=fs.readFileSync('review/trapper/index.html','utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
 ['training','The complete Training Ground rack','All eleven handheld gun types at their original model scale. Rifles and heavy weapons sit below; pistol, Uzi and revolver hang above. Melee, grenades and emplacements are excluded.'],
 ['player','Sized against the marine','The cabinet has room for full-size weapons. It no longer shrinks every gun to squeeze into a narrow strip.'],
 ['wall','Fits beside the other terminals','The larger case stays on the existing wall and stops before the firing line. CIF and supply terminal positions are unchanged.'],
 ['hq','The same cabinet at Threshold','HQ shows each owned firearm, including carried weapons. These are display copies; ownership, ammo, loadout and storage are unchanged. A fresh run starts with the issued pistol on display.'],
 ['attachments','Room for fitted attachments','Suppressors and extended magazines use the real fitted gun models. Bounds and separation checks cover every gun with all available suppressors and extended magazines fitted.']
];
const article=([id,title,note])=>`<article><h2>${title}</h2><figure><div class="pair">${['before','after'].map(p=>`<div class="${p}"><div class="label">${p==='before'?'Before':'After'}</div><img loading="lazy" src="data:image/jpeg;base64,${fs.readFileSync(path.join(dir,p+'-'+id+'.jpg')).toString('base64')}" alt="${title} ${p}"></div>`).join('')}</div><figcaption>${note}</figcaption></figure></article>`;
fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Armory · Full-size display</title><style>${css}</style><main><header><small>DEAD-WAVE / ARMORY DISPLAY / OCTOBER 2, 2026</small><h1>A proper weapons rack</h1><p>Full-size guns, a complete lineup, and space for their attachments.</p></header><nav>${[['after','After'],['before','Before'],['compare','Side by side']].map(([id,label])=>`<button data-mode="${id}" aria-pressed="${id==='after'}">${label}</button>`).join('')}</nav>${article(views[0])}<div class="grid">${views.slice(1).map(article).join('')}</div><footer><p>Matched views in the production game renderer. Focused display, inventory and placement checks pass. The older stored-only rack test requires crew review to match Jerry’s revised display requirement.</p><p>Independent visual acceptance, full integration and load/FPS verification remain pending.</p></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('Built five armory comparisons.');
