import fs from 'node:fs';
const root=new URL('./',import.meta.url),pic=(p,id)=>'data:image/jpeg;base64,'+fs.readFileSync(new URL(p+'-'+id+'.jpg',root)).toString('base64');
const css=fs.readFileSync(new URL('../trapper/index.html',root),'utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
['whole','Brandt’s observation post','Weathered timber, iron fittings and practical repairs give the tower a history. Its established location and height are retained.'],
['deck','A deck kept in service','Rain-grey boards, two lighter replacements, flush fasteners and scars. The middle stays open for the lookout.'],
['gear','Someone held this position','An ammunition tin and scattered spent brass suggest a watch that became a fight. Equipment stays against the edges.'],
['table','Watching and recording','The plotting table now carries binoculars, a marked sheet, pencil and compass. A leather binocular case hangs underneath.'],
['ladder','A clear way up','The ladder opening and landing remain clear. The steel post cuffs now follow the leaning timber instead of floating beside it.'],
['rail','Count them from the tower. Five.','Brandt’s clue is written directly onto the lake-facing rail, as something left by the lookout.'],
['outlook','A sightline that still needs work','This is the actual view toward the lake from deck height. Existing trees and a ridge obscure the stones; that world-layout issue has been sent to Claude. This art pass preserves the tower height and surrounding terrain.']
];
fs.writeFileSync(new URL('index.html',root),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Brandt’s tower · Before and after</title><style>${css}</style><main><header><small>DEAD-WAVE / THE WATCHTOWER</small><h1>Someone was keeping watch.</h1><p>Actual in-game pictures of Brandt’s observation post: repaired timber, worn equipment, spent brass and a message left on the rail.</p><p><a href="sightline/index.html">Latest: the repaired lake sightline, by day and night</a></p></header><nav aria-label="Picture comparison"><button data-mode="after" aria-pressed="true">After</button><button data-mode="before" aria-pressed="false">Before</button><button data-mode="compare" aria-pressed="false">Side by side</button></nav>${views.map(([id,title,note],i)=>`${i===1?'<div class="grid">':''}<article><h2>${title}</h2><figure><div class="pair"><div class="before"><div class="label">Before</div><img loading="lazy" src="${pic('before',id)}" alt="${title} before"></div><div class="after"><div class="label">After</div><img loading="lazy" src="${pic('after',id)}" alt="${title} after"></div></div><figcaption>${note}</figcaption></figure></article>${i===views.length-1?'</div>':''}`).join('')}<footer><p>Focused checks passed: tower location, deck height, ladder, collision shapes, durability and lantern settings match the original. The real renderer reports no page errors.</p><p>Independent crew playthrough, full integration and load/FPS acceptance remain pending. The lake-stones sightline is repaired in the linked follow-up.</p><a href="../world-story/index.html">Original world photo review</a> · <a href="../dock/index.html">Evacuation dock</a></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('PASS: seven matched tower comparisons built.');
