import fs from'node:fs';import vm from'node:vm';import assert from'node:assert/strict';import * as T from'three';import * as Fake from'../../tools/tests/fakethree.mjs';
const old=fs.readFileSync(new URL('details-before.js',import.meta.url),'utf8'),next=fs.readFileSync('assets/world/landmark-details.js','utf8');
const strip=s=>s.slice(0,s.indexOf("  if(o.kind==='tower')"))+s.slice(s.indexOf("  if(o.kind==='mast')"));assert.equal(strip(next),strip(old));
const build=(source,o,THREE=T)=>{const c={window:{}};vm.runInNewContext(source,c);return c.window.buildLandmarkDetails(THREE,o);};
let count=0;for(const slope of[-.2,0,.2]){const o={kind:'tower',ladderOut:2.25,ground:(x,z)=>.1+slope*x-.02*z},a=build(old,o),b=build(next,o);assert.equal(JSON.stringify(b.solids),JSON.stringify(a.solids));for(const p of b.parts){p.updateMatrix();assert([...p.geometry.attributes.position.array,...p.matrix.elements].every(Number.isFinite));}build(next,o,Fake);count++;}
const index=fs.readFileSync('index.html','utf8'),prior=fs.readFileSync(new URL('buildWatchtower-before.txt',import.meta.url),'utf8'),current=index.slice(index.indexOf('    function buildWatchtower('),index.indexOf('    function buildGraveyard('));
function run(source,details){const c={THREE:T,groundMinAround:()=>3,scene:new T.Group(),TOWER_LADDER_OUT:2.25,TOWER_MAX_HP:900,campfires:[],landmarks:[],tower:null,poiMat:new T.MeshStandardMaterial(),document:{createElement:()=>({getContext:()=>new Proxy({},{get:()=>()=>{}})})},sayText:()=> 'Count them from the tower. Five.',addSolid:(x,z,r,y0,y1)=>({x,z,r,y0,y1}),poiBox:(ps,m,w,h,d,x,y,z,ry=0,rz=0,rx=0)=>{const p=new T.Mesh(new T.BoxGeometry(w,h,d),m);p.position.set(x,y,z);p.rotation.set(rx,ry,rz);ps.push(p);},mergeParts:()=>new T.Group()};c.appendLandmarkDetails=(ps,kind,cx,cz,gy,yaw,o)=>{const d=build(details,{kind,...o,ground:()=>.1});ps.push(...d.parts);return{theme:d.theme,register:owner=>d.solids.forEach(s=>owner.colliders.push({x:cx+s.x,z:cz+s.z,r:s.r,y0:gy+s.y,y1:gy+s.y+s.h}))};};vm.createContext(c);vm.runInContext(source+';buildWatchtower(37,-134);',c);const t=c.tower;return JSON.parse(JSON.stringify({x:t.x,z:t.z,gy:t.gy,deckY:t.deckY,ladderX:t.ladderX,ladderZ:t.ladderZ,hp:t.hp,solids:t.colliders,lanterns:c.campfires.map(({x,z,y,phase,lantern})=>({x,z,y,phase,lantern}))}));}
assert.deepEqual(run(current,next),run(prior,old));
fs.writeFileSync(new URL('geometry-checks.json',import.meta.url),JSON.stringify({slopeCases:count,finiteGeometry:true,fakeThree:true,otherBuildersUnchanged:true,productionDeckLadderSolidsLanternUnchanged:true},null,2));console.log('PASS three terrain cases/fake THREE; other landmark builders unchanged; production deck, ladder, solids, HP and lantern identical.');
