import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import * as T from 'three';import * as Fake from '../../tools/tests/fakethree.mjs';import * as H from '../../world/history-props.js';import {mulberry} from '../../world/first-people.js';
let source=fs.readFileSync(new URL('./history-before.js',import.meta.url),'utf8');source=source.replace("'../ui/strings.js'",JSON.stringify(new URL('../../ui/strings.js',import.meta.url).href)).replace("'./first-people.js'",JSON.stringify(new URL('../../world/first-people.js',import.meta.url).href));const old=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const names=['buildChurchShell','buildRuinedFoundation','buildChimney','buildIronBandedGrave','buildOpenGrave'];let cases=0;const stats=[];
for(const seed of [1,5,61,511,49616])for(const name of names){const a=mulberry(seed),b=mulberry(seed),opts={w:5+seed%9*.21,d:4+seed%7*.17,door:seed%2===1};old[name](T,a,opts);const g=H[name](T,b,opts);assert.equal(b(),a(),name+' preserves caller random state');let meshes=0,vertices=0;
 g.traverse(o=>{if(o.isMesh){meshes++;vertices+=o.geometry.attributes.position.count;assert([...o.geometry.attributes.position.array].every(Number.isFinite),name+' finite geometry');}});assert(meshes<=2,name+' at most two static batches');
 g.position.set(4,1,8);g.rotation.y=.6;const coords=g.children.map(m=>Float32Array.from(m.geometry.attributes.position.array));g.userData.seatHistoryTerrain((x,z)=>.1*x+.08*z);const once=g.children.map(m=>Array.from(m.geometry.attributes.position.array));g.userData.seatHistoryTerrain(()=>99);assert.deepEqual(g.children.map(m=>Array.from(m.geometry.attributes.position.array)),once,'seating idempotent');
 for(let j=0;j<g.children.length;j++){const a=coords[j],b=g.children[j].geometry.attributes.position.array;for(let i=0;i<a.length;i+=3){const delta=.1*(Math.cos(.6)*a[i]+Math.sin(.6)*a[i+2])+.08*(-Math.sin(.6)*a[i]+Math.cos(.6)*a[i+2]);assert(Math.abs(b[i+1]-a[i+1]-delta)<1e-5,'terrain seating retains local height');}}
 if(seed===5)stats.push({name,meshes,vertices});cases++;
}
for(const name of names)assert(H[name](Fake,mulberry(5)).children.length,'test THREE '+name);
fs.writeFileSync(new URL('./geometry-checks.json',import.meta.url),JSON.stringify({cases,stats,rngUnchanged:true,finite:true,terrainSeating:true,fakeThree:true},null,2));console.log('PASS '+cases+' builder/seed cases: exact legacy RNG, finite geometry, <=2 static batches, terrain seating and idempotence; fake THREE builds.');console.log(JSON.stringify(stats));
