// GP-110: bounded real-renderer before/after review of Coldwater only.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';
const {chromium}=createRequire(import.meta.url)('playwright'),out='review/coldwater',before=process.argv.includes('--before'),prefix=before?'before':'after';
const s=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(async()=>{window.CW={T:await import('three')};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);const all=TT.historyProps.group.children;return{placement:all.map(o=>({name:o.name,position:o.position.toArray(),rotation:o.rotation.toArray()})),taken:TT.historyProps.taken,geometry:all.filter(o=>/coldwater|grave/.test(o.name)).map(o=>{let meshes=0,vertices=0;o.traverse(c=>{if(c.isMesh){meshes++;vertices+=c.geometry.attributes.position.count;}});return{name:o.name,meshes,vertices};})};});
if(!before){const old=JSON.parse(fs.readFileSync(out+'/before-checks.json'));assert.deepEqual(state.placement,old.placement,'ALL history placements and rotations unchanged');assert.deepEqual(state.taken,old.taken,'History reserved footprints unchanged');}
const views=[['church',19,[10,9,14],[0,2,0]],['church-inside',19,[1,3.8,4.6],[0,1.5,-4]],['home-1',20,[8,7,9],[0,.5,0]],['home-2',21,[8,7,9],[0,.5,0]],['home-3',22,[8,7,9],[0,.5,0]],['chimney',23,[5,4,6],[0,2,0]],['iron-grave-1',24,[2.5,2.8,3.5],[0,.2,0]],['iron-grave-2',25,[2.5,2.8,3.5],[0,.2,0]],['open-grave',26,[2.8,3.1,3.8],[0,.2,0]],['cemetery',null],['church-night',19,[10,9,14],[0,2,0]],['grave-night',26,[2.8,3.1,3.8],[0,.2,0]]];
for(const [id,idx,eye,target]of views){await p.evaluate(({id,idx,eye,target})=>{TT.setWorldTime(id.endsWith('night')?.02:.4);let p,t;if(idx!==null){const o=TT.historyProps.group.children[idx];o.updateWorldMatrix(true,true);p=o.localToWorld(new CW.T.Vector3(...eye));t=o.localToWorld(new CW.T.Vector3(...target));}else{const o=TT.POI.graveyard;p=new CW.T.Vector3(o.x+25,TT.sampleHeight(o.x,o.z)+26,o.z+28);t=new CW.T.Vector3(o.x,TT.sampleHeight(o.x,o.z)+1,o.z);}TT.setShotView({x:p.x,y:p.y,z:p.z,tx:t.x,ty:t.y,tz:t.z,fov:48});},{id,idx,eye,target});await p.waitForTimeout(230);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({...state,pageErrors:errors},null,2));console.log('PASS '+prefix+': 12 real-renderer photos; no page errors; '+(!before?'all history placements/reservations unchanged':'baseline recorded'));console.log(JSON.stringify(state.geometry));
}finally{clearTimeout(stop);await b?.close();s.close();}
