import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/cordon',before=process.argv.includes('--before'),prefix=before?'before':'after';fs.mkdirSync(out,{recursive:true});
const server=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));if(before)await p.route('**/index.html*',route=>{const source=fs.readFileSync('index.html','utf8').replace(/^.*import \{ planConvoyRoute.*\r?\n/m,'').replace(/          \/\/ GP-121: former[\s\S]*?          \}; \/\/ GP-121 checkpoint end\r?\n/,'');return route.fulfill({contentType:'text/html',body:source.replace(/^.*historyProps.buildCheckpoint\?\.\(\).*\r?\n/m,'')});});await p.goto(server.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(()=>{const m=TT.historyProps.parts['cordon-gate'];m.updateMatrixWorld(true);window.CG={m};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);const local=p=>m.worldToLocal(new TT.THREE.Vector3(p.x,TT.sampleHeight(p.x,p.z),p.z)).toArray();return{gate:{position:m.position.toArray(),rotation:m.rotation.toArray()},sites:TT.getObjectiveProps().sites,paths:TT.PATHS.map(p=>p.map(v=>({x:v.x,z:v.z}))),trees:TT.trees.map(t=>({x:t.x,z:t.z})),nearTrees:TT.trees.filter(t=>Math.hypot(t.x-m.position.x,t.z-m.position.z)<85).map(local),nearEnds:TT.PATHS.flatMap(p=>[p[0],p.at(-1)]).filter(v=>Math.hypot(v.x-m.position.x,v.z-m.position.z)<100).map(local),solids:TT.worldSolids.map(s=>({x:s.x,z:s.z,r:s.radius,y0:s.y0,y1:s.y1}))};});
if(!before){const old=JSON.parse(fs.readFileSync(out+'/before-checks.json')).state;for(const k of['gate','sites','paths','trees'])assert.deepEqual(state[k],old[k],k);const current=new Set(state.solids.map(s=>JSON.stringify(s)));assert(old.solids.every(s=>current.has(JSON.stringify(s))),'original solids retained');}
for(const[id,eye,target]of[['gate',[8,5,12],[0,2,0]],['checkpoint',[-11,7,15],[1,1,4]],['inside',[14,22,44],[0,0,18]],['outside',[7,4.5,-8],[0,2,-.9]],['road',[-40,30,-35],[-24,1,-12]],['details',[1,2.7,11],[-4.8,1.3,7.5]],['connection',[40,60,84],[-8,0,40]]]){await p.evaluate(({eye,target})=>{const m=CG.m;const a=m.localToWorld(new TT.THREE.Vector3(...eye)),t=m.localToWorld(new TT.THREE.Vector3(...target));TT.setShotView({x:a.x,y:a.y,z:a.z,tx:t.x,ty:t.y,tz:t.z,fov:52});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
if(!before){
const routeChecks=await p.evaluate(()=>{const m=CG.m,c=TT.historyProps.parts['cordon-checkpoint'],routes=c.userData.routes,world=q=>m.localToWorld(new TT.THREE.Vector3(q.x,0,q.z));let minClear=Infinity,treeClear=Infinity;for(const line of Object.values(routes))for(const q of line){const p=world(q),y=TT.sampleHeight(p.x,p.z);for(const s of TT.worldSolids)if(s.y1>y+.25&&s.y0<y+1.8)minClear=Math.min(minClear,Math.hypot(p.x-s.x,p.z-s.z)-(s.radius||0));for(const t of TT.trees)treeClear=Math.min(treeClear,Math.hypot(p.x-t.x,p.z-t.z)-(t.trunkRadius||.3));}const last=world(routes.inside.at(-1)),join=Math.min(...TT.PATHS.flatMap(line=>line.map(q=>Math.hypot(q.x-last.x,q.z-last.z))));return{minClear,treeClear,join,innerLength:routes.inside.reduce((s,q,i,a)=>s+(i?Math.hypot(q.x-a[i-1].x,q.z-a[i-1].z):0),0),outerLength:routes.outside.reduce((s,q,i,a)=>s+(i?Math.hypot(q.x-a[i-1].x,q.z-a[i-1].z):0),0),draws:c.children.length,routes};});fs.writeFileSync(out+'/route-checks.json',JSON.stringify(routeChecks,null,2));assert(routeChecks.minClear>2.2,'vehicle lane clearance '+routeChecks.minClear);assert(routeChecks.treeClear>2.3,'truck clearance to trees '+routeChecks.treeClear);assert(routeChecks.join<.01);assert.equal(routeChecks.draws,2);console.log('PASS route clearance and exact existing-trail join',JSON.stringify({...routeChecks,routes:undefined}));
const result=await p.evaluate(fs.readFileSync('tools/tests/t52.js','utf8'));fs.writeFileSync(out+'/objective-checks.txt',result);assert(!result.includes('FAIL '),result);
}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': seven real-renderer checkpoint views; no page errors; '+(before?'baseline saved':'gate, paths, trees, objective sites and original solids identical'));
}finally{clearTimeout(stop);await b?.close();server.close();}
