// GP-116: bounded actual-renderer comparison, preserving the dock gameplay footprint.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/dock',before=process.argv.includes('--before'),prefix=before?'before':'after';fs.mkdirSync(out,{recursive:true});if(before){fs.copyFileSync('assets/world/landmark-details.js',out+'/details-before.js');const s=fs.readFileSync('index.html','utf8');fs.writeFileSync(out+'/buildDock-before.txt',s.slice(s.indexOf('    function buildDock(d)'),s.indexOf('    function buildBridge(b)')));}
const server=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(server.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(async()=>{window.DR={T:await import('three'),d:TT.POI.dock};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);const d=DR.d;return{dock:{x:d.x,z:d.z,yaw:d.yaw,deckY:d.deckY},platforms:TT.platforms.filter(x=>x.landmark).map(x=>({...x})),history:TT.historyProps.group.children.map(o=>({n:o.name,p:o.position.toArray()}))};});
if(!before)assert.deepEqual(state,JSON.parse(fs.readFileSync(out+'/before-checks.json')).state);
for(const[id,eye,target]of[['whole',[-8,6,-10],[0,0,0]],['deck',[-5,4,-6],[0,.1,-.5]],['boarding',[-5,3,8],[0,0,3]],['rowboat',[-6,2.7,4],[-2.35,-.25,1.8]],['schedule',[-2.8,1.75,-5.4],[1.3,1.15,-3.7]],['shore',[-7,3,-10],[0,.3,-1]]]){await p.evaluate(({eye,target})=>{const{T,d}=DR,w=v=>new T.Vector3(d.x+Math.cos(d.yaw)*v[0]+Math.sin(d.yaw)*v[2],d.deckY+v[1],d.z-Math.sin(d.yaw)*v[0]+Math.cos(d.yaw)*v[2]);const e=w(eye),t=w(target);TT.setShotView({x:e.x,y:e.y,z:e.z,tx:t.x,ty:t.y,tz:t.z,fov:48});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': six real-renderer dock views; no page errors; '+(before?'baseline saved':'dock, platforms and history positions unchanged'));
}finally{clearTimeout(stop);await b?.close();server.close();}
