// GP-114: bounded campsite photo review in the real renderer.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';
const {chromium}=createRequire(import.meta.url)('playwright'),v2=process.argv.includes('--v2'),out='review/hikers'+(v2?'/v2':''),before=process.argv.includes('--before'),prefix=before?'before':'after';fs.mkdirSync(out,{recursive:true});if(before)fs.copyFileSync('assets/world/campsites.js',out+'/camp-before.js');
const s=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(async()=>{window.HR={T:await import('three'),camp:TT.landmarks.find(l=>l.kind==='campsite'&&l.campStyle==='hikers')};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);return{history:TT.historyProps.group.children.map(o=>({name:o.name,p:o.position.toArray(),r:o.rotation.toArray()})),camps:TT.landmarks.filter(l=>l.kind==='campsite').map(c=>({style:c.campStyle,x:c.x,z:c.z,yaw:c.campYaw,colliders:c.colliders.map(x=>({x:x.x,z:x.z,r:x.radius,y0:x.y0,y1:x.y1}))}))};});
if(v2)console.log(await p.evaluate(()=>{const c=HR.camp;return TT.trees.map(t=>{const q=t.position||t;const x=q.x-c.x,z=q.z-c.z;return{x:Math.cos(c.campYaw)*x-Math.sin(c.campYaw)*z,z:Math.sin(c.campYaw)*x+Math.cos(c.campYaw)*z};}).filter(t=>Math.hypot(t.x,t.z)<22);}));
if(!before){const old=JSON.parse(fs.readFileSync(out+'/before-checks.json')).state;assert.deepEqual(state.history,old.history);for(let i=0;i<old.camps.length;i++){const a=state.camps[i],b=old.camps[i];assert.deepEqual({...a,colliders:undefined},{...b,colliders:undefined});const n=v2&&a.style==='hikers'?6:b.colliders.length;assert.deepEqual(a.colliders.slice(0,n),b.colliders.slice(0,n));assert.equal(a.colliders.length-b.colliders.length,a.style==='hikers'&&!v2?3:0);}}
for(const [id,eye,target]of [['camp',[10,10,13],[0,.5,-1.4]],['orange-tent',[-.4,2.8,1.3],[-3,.7,-2]],['blue-tent',[5.8,3.5,.8],[2.3,.7,-3.4]],['meal',[3.4,3.4,4.7],[.4,.3,1]],['waiting',[5.5,2.8,4.4],[1.9,.55,.8]],['shelter',[.3,2.5,-1.2],[0,.55,-5.5]],['shelter-side',[-3.1,2.6,-3.5],[0,.55,-5.5]]]){await p.evaluate(({eye,target})=>{const {T,camp:c}=HR;const world=v=>new T.Vector3(c.x+Math.cos(c.campYaw)*v[0]+Math.sin(c.campYaw)*v[2],c.gy+v[1],c.z-Math.sin(c.campYaw)*v[0]+Math.cos(c.campYaw)*v[2]);const e=world(eye),t=world(target);TT.setShotView({x:e.x,y:e.y,z:e.z,tx:t.x,ty:t.y,tz:t.z,fov:48});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
if(v2)for(const[id,eye,target]of [['hidden',[-10,2,-23.5],[-13,.4,-19]],['hidden-side',[-17,2.7,-22],[-13,.4,-19]],['setting',[-2,11,9],[-6,0,-6]]]){await p.evaluate(({eye,target})=>{const{T,camp:c}=HR;const w=v=>new T.Vector3(c.x+Math.cos(c.campYaw)*v[0]+Math.sin(c.campYaw)*v[2],v[1],c.z-Math.sin(c.campYaw)*v[0]+Math.cos(c.campYaw)*v[2]);const e=w(eye),t=w(target),g=TT.sampleHeight(t.x,t.z);e.y+=g;t.y+=g;TT.setShotView({x:e.x,y:e.y,z:e.z,tx:t.x,ty:t.y,tz:t.z,fov:48});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': '+(v2?'ten':'seven')+' real-renderer views, no page errors; '+(before?'baseline recorded':v2?'camp/history positions and original six hiker colliders retained; three shelter solids relocated':'camp/history positions and existing colliders retained, three shelf colliders added'));
}finally{clearTimeout(stop);await b?.close();s.close();}
