import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/marine-gear',before=process.argv.includes('--before'),prefix=before?'before':'after',srv=await serve(process.cwd(),0);let browser;const timer=setTimeout(()=>process.exit(2),120000);
try{browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/index.html*',r=>{let s=fs.readFileSync('index.html','utf8');if(before)for(const{a,b,text}of JSON.parse(fs.readFileSync(out+'/source-before.json','utf8'))){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i);s=s.slice(0,i)+text+s.slice(j);}return r.fulfill({contentType:'text/html',body:s});});
if(before)for(const[file,name]of[['marine-body.js','body'],['marine-draw.js','draw']])await p.route('**/studio/'+file+'*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(out+'/'+name+'-before.js','utf8')}));
await p.goto(srv.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);await p.evaluate(()=>{document.getElementById('playerName').value='Equipment review';document.getElementById('modeTraining').click();});await p.waitForFunction(()=>TT.trainingDbg.state().active);
await p.evaluate(async()=>{TT.getMarine().visible=false;const m=TT.makeMarine();m.position.set(0,-200,-647);TT.scene.add(m);window.G=m;const{rigs}=await import('./studio/rigs.js'),{loadClip,sampleClip,applyPose}=await import('./studio/clip.js');window.GV={inst:rigs.get('marine').create({group:m}),sampleClip,applyPose,clips:{}};for(const k of['stand','walk','run'])GV.clips[k]=loadClip(await(await fetch('./studio/clips/marine/'+k+'.json')).json());const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');});
const shots=[['back',Math.PI,{}],['quarter',2.5,{}],['front',0,{}],['side',Math.PI/2,{}],['pair',Math.PI,{dualOwned:{uzi:true}}],['pair-drawn',Math.PI,{dualOwned:{uzi:true},inHand:'uzi',akimbo:true}],['pair-single',Math.PI,{dualOwned:{uzi:true},inHand:'uzi',akimbo:false}],['two-pairs',Math.PI,{dualOwned:{uzi:true,revolver:true,pistol:true}}],['heavy',2.8,{loadout:{primary:['minigun','flamer'],secondary:['uzi','revolver']},dualOwned:{uzi:true}}],['walk',2.5,{pose:'walk'}],['run',2.5,{pose:'run'}],['head',.55,{head:true}],['nvg',.55,{head:true,nvg:true}],['bare',.5,{bare:true}],['survivor',.5,{survivor:true}]];
const states={};for(const[id,angle,o]of shots){states[id]=await p.evaluate(({angle,o})=>{const m=G,u=m.userData;m.rotation.y=angle;GV.applyPose(GV.inst,GV.sampleClip(GV.clips[o.pose||'stand'],o.pose?.25:0));for(const[k,list]of Object.entries(u.gearParts))for(const a of list)a.visible=(o.bare?['bareHead','bareTorso']:['helmet','vest','pads','nvg']).includes(k);u.nvgPivot.rotation.x=o.nvg?0:-1.35;if(u.eyewearG)u.eyewearG.visible=!o.nvg;const load=o.loadout||{primary:['m4','shotgun'],secondary:['uzi','revolver']};const rig=TT.carryPreview(m,{loadout:load,inHand:null,akimbo:false,dualOwned:{},vest:!o.bare,grenades:3,...o});if(o.head)for(const a of rig.slings)a.g.visible=false;else for(const a of rig.slings)a.g.visible=true;
if(o.survivor){if(!window.SG){window.SG=TT.makeSurvivorFigure('brandt');SG.position.copy(m.position);TT.scene.add(SG);}m.visible=false;SG.visible=true;SG.rotation.y=angle;}else{m.visible=true;if(window.SG)SG.visible=false;}
TT.setShotView({x:0,y:-200+(o.head?1.47:1.1),z:-647+(o.head?1.1:4.7),tx:0,ty:-200+(o.head?1.45:.96),tz:-647,fov:o.head?35:32});return{slings:rig.slings.map(s=>s.kind),base:rig.holsters.map(s=>s.kind),pairs:rig.pairs?.map(s=>s.kind),hip:rig.hip.kind,hipPair:rig.hipPair?.kind,wardrobe:Object.keys(u.wardrobe).sort()};},{angle,o});await p.waitForTimeout(180);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
if(!before){assert.equal(states.pair.pairs[0],'uzi');assert.equal(states['pair-drawn'].base[0],null);assert.equal(states['pair-drawn'].pairs[0],null);assert.equal(states['pair-single'].pairs[0],'uzi');assert.deepEqual(states['two-pairs'].pairs,['uzi','revolver']);assert.equal(states['two-pairs'].hipPair,'pistol');const old=JSON.parse(fs.readFileSync(out+'/before-checks.json','utf8'));for(const k of Object.keys(states))assert.deepEqual(states[k].wardrobe,old.states[k].wardrobe);const t=await p.evaluate(fs.readFileSync('tools/tests/t140.js','utf8'));fs.writeFileSync(out+'/t140.txt',t);assert(!t.includes('FAIL'),t);console.log(t);}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({states,errors},null,2));console.log('PASS '+prefix+'15 gear/carry views; paired gun state checks '+(!before?'PASS':'baseline recorded'));
}finally{clearTimeout(timer);await browser?.close();srv.close();}
