import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/marine-fit',before=process.argv.includes('--before'),prefix=before?'before':'after',srv=await serve(process.cwd(),0);let browser;const timer=setTimeout(()=>process.exit(2),120000);
try{browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.error(e.stack);});
await p.route('**/index.html*',r=>{let s=fs.readFileSync('index.html','utf8');if(before)for(const{a,b,text}of JSON.parse(fs.readFileSync(out+'/source-before.json','utf8'))){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i);s=s.slice(0,i)+text+s.slice(j);}return r.fulfill({contentType:'text/html',body:s});});
if(before)for(const[file,name]of[['studio/marine-body.js','body']])await p.route('**/'+file+'*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(out+'/'+name+'-before.js','utf8')}));
await p.goto(srv.origin+'/index.html?debug=1&raf=timer&renderer=webgl',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);await p.evaluate(()=>{document.getElementById('playerName').value='Equipment review';document.getElementById('modeTraining').click();});await p.waitForFunction(()=>TT.trainingDbg.state().active);
await p.evaluate(async()=>{TT.getMarine().visible=false;const m=TT.makeMarine();m.position.set(0,-200,-647);TT.scene.add(m);window.G=m;const{rigs}=await import('./studio/rigs.js'),{loadClip,sampleClip,applyPose}=await import('./studio/clip.js');window.GV={inst:rigs.get('marine').create({group:m}),sampleClip,applyPose,clips:{}};for(const k of['stand','walk','run'])GV.clips[k]=loadClip(await(await fetch('./studio/clips/marine/'+k+'.json')).json());const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');});
const loadout={primary:['shotgun','launcher'],secondary:[]};
const shots=[['carrier-front',0,{belt:true,loadout}],['carrier-quarter',.65,{belt:true,loadout}],['carrier-side',1.57,{belt:true,loadout}],['shirt-front',0,{bare:true,belt:true,loadout}],['shirt-quarter',.65,{bare:true,belt:true,loadout}],['back',2.9,{pack:true,loadout}],['shoulder',.8,{belt:true,loadout:{primary:[],secondary:[]}}],['walk',.5,{pose:'walk',loadout}],['run',2.5,{pose:'run',loadout}],['brandt',.5,{survivor:true}],['okafor',.5,{survivor:'okafor'}],['pike',.5,{survivor:'pike'}]];
const states={};for(const[id,angle,o]of shots){states[id]=await p.evaluate(({angle,o})=>{const m=G,u=m.userData;m.rotation.y=angle;GV.applyPose(GV.inst,GV.sampleClip(GV.clips[o.pose||'stand'],o.pose?.25:0));for(const[k,list]of Object.entries(u.gearParts))for(const a of list)a.visible=(o.hat?['bareHead','vest','pads']:o.bare?['bareHead','bareTorso']:['helmet','vest','pads','nvg']).includes(k);if(o.hat)for(const[k,g]of Object.entries(u.dress.hats))g.visible=k===o.hat;u.nvgPivot.rotation.x=o.nvg?0:-1.35;if(u.eyewearG)u.eyewearG.visible=!o.nvg;const load=o.loadout||{primary:['m4','shotgun'],secondary:['uzi','revolver']};const rig=TT.carryPreview(m,{loadout:load,inHand:null,akimbo:false,dualOwned:{},vest:!o.bare,grenades:3,...o});if(o.head)for(const a of rig.slings)a.g.visible=false;else for(const a of rig.slings)a.g.visible=true;
if(o.survivor){if(!window.SG||SG.userData.survivorWho!==(o.survivor===true?'brandt':o.survivor)){if(window.SG)TT.scene.remove(SG);window.SG=TT.makeSurvivorFigure(o.survivor===true?'brandt':o.survivor);SG.position.copy(m.position);TT.scene.add(SG);}m.visible=false;SG.visible=true;SG.rotation.y=angle;}else{m.visible=true;if(window.SG)SG.visible=false;}
const cy=o.head?1.45:o.boots?.17:o.belt?.99:o.pack?1.05:.96,dist=o.head?1.3:o.boots?1.1:o.belt||o.pack?1.7:4.7;TT.setShotView({x:0,y:-200+cy+.07,z:-647+dist,tx:0,ty:-200+cy,tz:-647,fov:o.head?35:32});return{slings:rig.slings.map(s=>s.kind),base:rig.holsters.map(s=>s.kind),pairs:rig.pairs?.map(s=>s.kind),hip:rig.hip.kind,hipPair:rig.hipPair?.kind,wardrobe:Object.keys(u.wardrobe).sort()};},{angle,o});await p.waitForTimeout(180);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
if(!before){const old=JSON.parse(fs.readFileSync(out+'/before-checks.json','utf8'));for(const k of Object.keys(states))assert.deepEqual(states[k].wardrobe,old.states[k].wardrobe);const t=await p.evaluate(fs.readFileSync('tools/tests/t140.js','utf8'));fs.writeFileSync(out+'/t140.txt',t);assert(!t.includes('FAIL'),t);console.log(t);}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({states,errors},null,2));console.log('PASS '+prefix+' '+shots.length+' gear/carry views; paired gun state checks '+(!before?'PASS':'baseline recorded'));
}finally{clearTimeout(timer);await browser?.close();srv.close();}
