import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/medical-wreck',before=process.argv.includes('--before'),prefix=before?'before':'after';
fs.mkdirSync(out,{recursive:true});
const server=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(server.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(()=>{window.WR={m:TT.POI.wrecks[0].mesh,medical:TT.getObjectiveProps().props['objective:medical-convoy']};const m=WR.m;const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);const u=TT.POI.wrecks[1].mesh;let hash=2166136261;u.traverse(o=>{for(const a of Object.values(o.geometry?.attributes||{}))for(const n of new Uint8Array(a.array.buffer)){hash=Math.imul(hash^n,16777619)>>>0;}});return{wrecks:TT.POI.wrecks.map(w=>({x:w.x,z:w.z,pos:w.mesh.position.toArray(),rot:w.mesh.rotation.toArray()})),sites:TT.getObjectiveProps().sites,utilityHash:hash,solids:TT.worldSolids.filter(s=>Math.hypot(s.x-m.position.x,s.z-m.position.z)<12).map(s=>({x:s.x,z:s.z,r:s.radius,y0:s.y0,y1:s.y1}))};});
if(!before)assert.deepEqual(state,JSON.parse(fs.readFileSync(out+'/before-checks.json')).state);
for(const[id,eye,target]of[['whole',[-9,6,-10],[0,.8,0]],['front',[-4,2.8,-5],[0,.8,-1.6]],['engine',[3,3.5,-4],[0,1.1,-2.2]],['cargo',[4,4,5],[0,1,1.3]],['stretcher',[-4,3,5],[-.8,.5,2.8]],['supplies',[5,3,4],[1.65,.4,2.4]]]){await p.evaluate(({eye,target})=>{const m=WR.m;m.updateMatrixWorld(true);const a=m.localToWorld(new TT.THREE.Vector3(...eye)),t=m.localToWorld(new TT.THREE.Vector3(...target));TT.setShotView({x:a.x,y:a.y,z:a.z,tx:t.x,ty:t.y,tz:t.z,fov:48});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
await p.evaluate(()=>{const r=WR.medical,a=r.approach,t=r.centre;TT.setShotView({x:a.x+(a.x-t.x)*2,y:a.y+2.8,z:a.z+(a.z-t.z)*2,tx:t.x,ty:t.y+.35,tz:t.z,fov:55});});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-approach.jpg',type:'jpeg',quality:93});
const result=await p.evaluate(fs.readFileSync('tools/tests/t52.js','utf8'));fs.writeFileSync(out+'/'+prefix+'-objective-checks.txt',result);assert.ok(!result.includes('FAIL '),result);
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': seven real-renderer wreck views; t52 all pass; no page errors; '+(before?'baseline saved':'sites, both wreck transforms, utility geometry and all nearby solids identical'));
}finally{clearTimeout(stop);await b?.close();server.close();}
