// GP-112: bounded actual-renderer mine art review.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';
const {chromium}=createRequire(import.meta.url)('playwright'),out=process.argv.includes('--arch')?'review/mine/arch':'review/mine',before=process.argv.includes('--before'),prefix=before?'before':'after';fs.mkdirSync(out,{recursive:true});if(before)fs.copyFileSync('world/history-props.js',out+'/history-before.js');
const s=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(async()=>{window.MR={T:await import('three'),cave:TT.POI.caves.find(c=>c.theme==='iron')};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);return{placement:TT.historyProps.group.children.map(o=>({name:o.name,position:o.position.toArray(),rotation:o.rotation.toArray()})),taken:TT.historyProps.taken,caves:TT.POI.caves.map(c=>({theme:c.theme,x:c.x,z:c.z,yaw:c.yaw,mouthHalf:c.mouthHalf,design:c.design}))};});
if(!before)assert.deepEqual(state,JSON.parse(fs.readFileSync(out+'/before-checks.json')).state,'History and cave layout unchanged');
const views=[['entrance',null,[3,8,16],[0,1.5,0]],['threshold',null,[1,3.3,7.8],[0,1.45,-.3]],['timbers','mine-timbers',[4,3.5,5],[0,1.6,0]],['cut-bars','mine-bars-cut',[3,2.1,4.5],[0,.75,0]],['warning','iron-below',[1.8,1.9,3.4],[0,.8,0]],['hikers','hikers-cache',[2.8,2.8,3.8],[.1,.4,0]],['rope-route',null,[-5,6,8],[-1.8,.4,1.2]]];
for(const [id,name,eye,target]of views){await p.evaluate(({name,eye,target})=>{const {T,cave:c}=MR;let e,t;if(name){const o=TT.historyProps.parts[name];o.updateWorldMatrix(true,true);e=o.localToWorld(new T.Vector3(...eye));t=o.localToWorld(new T.Vector3(...target));}else{const world=v=>new T.Vector3(c.x+Math.cos(c.yaw)*v[0]+Math.sin(c.yaw)*v[2],c.gy+v[1],c.z-Math.sin(c.yaw)*v[0]+Math.cos(c.yaw)*v[2]);e=world(eye);t=world(target);}TT.setShotView({x:e.x,y:e.y,z:e.z,tx:t.x,ty:t.y,tz:t.z,fov:48});},{name,eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
const details=await p.evaluate(()=>{const names=['mine-timbers','mine-bars-cut','iron-below','hikers-cache'];return names.map(name=>{const o=TT.historyProps.parts[name];let meshes=0,vertices=0;o.traverse(m=>{if(m.isMesh){meshes++;vertices+=m.geometry.attributes.position.count;}});return{name,meshes,vertices};});});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors,details},null,2));console.log('PASS '+prefix+': seven real-renderer views, no page errors; '+(before?'baseline recorded':'all history/cave layout and reservations identical'));console.log(JSON.stringify(details));
}finally{clearTimeout(stop);await b?.close();s.close();}
