import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/relay',before=process.argv.includes('--before'),prefix=before?'before':'after';
const server=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(server.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(()=>{TT.lightningDbg.boots();window.RL={m:TT.POI.mast,radio:TT.getObjectiveProps().props['objective:radio-repair'],boots:TT.scene.getObjectByName('insulated-boots')};const{m,radio,boots}=RL;const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);return{mast:{x:m.x,z:m.z},sites:TT.getObjectiveProps().sites,boots:boots.position.toArray(),solids:TT.worldSolids.filter(s=>Math.hypot(s.x-m.x,s.z-m.z)<12).map(s=>({x:s.x,z:s.z,r:s.radius,y0:s.y0,y1:s.y1}))};});
if(!before)assert.deepEqual(state,JSON.parse(fs.readFileSync(out+'/before-checks.json')).state);
for(const[id,eye,target]of[['whole',[18,12,20],[0,6,0]],['station',[8,6,9],[.5,.6,1]],['rack',[-5,3.4,5],[-2.1,.85,.6]],['grounding',[-6,4,-5],[-2,.3,-1.5]]]){await p.evaluate(({eye,target})=>{const{m}=RL,y=m.mesh.position.y;TT.setShotView({x:m.x+eye[0],y:y+eye[1],z:m.z+eye[2],tx:m.x+target[0],ty:y+target[1],tz:m.z+target[2],fov:48});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
for(const state of['broken','repaired']){await p.evaluate(state=>{const r=RL.radio;r.setState(state);const g=r.group,s=Math.sin(g.rotation.y),c=Math.cos(g.rotation.y);TT.setShotView({x:g.position.x+c*1.6+s*2.9,y:g.position.y+1.9,z:g.position.z-s*1.6+c*2.9,tx:g.position.x,ty:g.position.y+.6,tz:g.position.z,fov:45});},state);await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+state+'.jpg',type:'jpeg',quality:93});}
await p.evaluate(()=>{const b=RL.boots,p=b.position;TT.setShotView({x:p.x+2,y:p.y+2,z:p.z+2,tx:p.x,ty:p.y+.08,tz:p.z,fov:42});});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-boots.jpg',type:'jpeg',quality:93});
if(!before){
const result=await p.evaluate(fs.readFileSync('tools/tests/t52.js','utf8'));fs.writeFileSync(out+'/objective-checks.txt',result);console.log(result);assert.ok(!result.includes('FAIL '));
const bootsCheck=await p.evaluate(()=>{const count=()=>{let n=0;TT.scene.traverse(o=>{if(o.name==='relay-work-mat')n++;});return n;};TT.lightningDbg.wear();const picked=TT.lightningDbg.worn()&&!RL.boots.visible&&TT.scene.getObjectByName('relay-work-mat').visible;TT.lightningDbg.reset();TT.lightningDbg.boots();return{picked,reset:RL.boots.visible&&!TT.lightningDbg.worn(),matCount:count()};});assert.deepEqual(bootsCheck,{picked:true,reset:true,matCount:1});fs.writeFileSync(out+'/boots-checks.json',JSON.stringify(bootsCheck,null,2));console.log('PASS boots pickup/reset: work mat remains and is not duplicated');
}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': seven real-renderer relay views; no page errors; '+(before?'baseline saved':'sites, boots and all nearby solids identical'));
}finally{clearTimeout(stop);await b?.close();server.close();}
