// UI contract checks plus actual production playback. No combat patches in this test.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {serve} from '../tools/serve.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
const root=fileURLToPath(new URL('..',import.meta.url)),shots=path.join(root,'Claude outputs/shots/gp13');
fs.mkdirSync(shots,{recursive:true});
const src=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script type="importmap">[\s\S]*?<\/script>/,()=>'<script type="importmap">{"imports":{"three":"/tools/tests/fakethree.mjs","three/webgpu":"/tools/tests/fakethree.mjs","three/tsl":"/tools/tests/faketsl.mjs","three/addons/":"/tools/tests/addons/"}}</script>');
const fixture=`<!doctype html><link rel="stylesheet" href="/ui/replays.css"><div id="win" class="show"><div class="card"><p id="winMsg"><span class="deathlog"><span class="dl"><b class="d got" data-death-cause="caveguard">Cave guardian</b><b class="d got" data-death-cause="tentacles">Tentacles</b></span></span></p><button id="again">Try again</button></div></div><script type="module">
import {mountDeathReplays} from '/ui/replays.js';
const rows=[{id:'cave',causeKey:'caveguard',unlocked:false,labelKey:'replay.cave.title',descriptionKey:'replay.cave.blurb'},{id:'tentacle',causeKey:'tentacles',unlocked:false,labelKey:'replay.tentacle.title',descriptionKey:'replay.tentacle.blurb'}];
let playing=false;window.starts=[];
window.finish=phase=>{playing=false;dispatchEvent(new CustomEvent('dw-game',{detail:{type:'scripted-death-replay',id:'cave',phase}}));};
window.unlock=()=>{rows.forEach(r=>r.unlocked=true);ui.update({cause:'caveguard',victory:false});};
window.ui=mountDeathReplays({panel:document.querySelector('#win'),again:document.querySelector('#again'),list:()=>rows,canReplay:id=>rows.some(r=>r.id===id&&r.unlocked)&&!playing,isPlaying:()=>playing,begin:id=>{playing=true;starts.push(id);dispatchEvent(new CustomEvent('dw-game',{detail:{type:'scripted-death-replay',id,phase:'start'}}));return {ok:true};}});
ui.update({cause:'caveguard',victory:false});
</script>`;
const server=await serve(root,0);let browser;
try{
 browser=await chromium.launch({executablePath:process.env.UI_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/ui/replay-contract-fixture.html',route=>route.fulfill({body:fixture,contentType:'text/html'}));
 await page.goto(server.origin+'/ui/replay-contract-fixture.html');await page.waitForFunction(()=>window.ui);
 assert(await page.locator('#watchAgain').isHidden());assert.equal(await page.locator('button.replay-tile').count(),0);
 await page.evaluate(()=>unlock());assert(await page.locator('#watchAgain').isVisible());
 assert.equal(await page.locator('button.replay-tile').count(),2);
 await page.locator('#watchAgain').focus();await page.keyboard.press('Enter');
 assert.deepEqual(await page.evaluate(()=>starts),['cave']);
 assert(await page.locator('#win').isHidden());assert(await page.locator('#again').isDisabled());
 assert(await page.evaluate(()=>document.getElementById('win').inert));
 await page.evaluate(()=>finish('end'));
 assert(await page.locator('#again').isEnabled());assert(await page.locator('#watchAgain').evaluate(el=>el===document.activeElement));
 await page.locator('[data-replay="tentacle"]').click();await page.evaluate(()=>finish('abort'));
 assert(await page.locator('[data-replay="tentacle"]').evaluate(el=>el===document.activeElement));
 await page.evaluate(()=>ui.update({cause:'shambler',victory:false}));assert(await page.locator('#watchAgain').isHidden());
 assert(await page.locator('[data-replay="tentacle"]').isEnabled());
 await page.evaluate(()=>ui.update({cause:'caveguard',victory:true}));assert(await page.locator('#watchAgain').isHidden());
 assert(await page.locator('[data-replay="cave"]').isDisabled());
 console.log('PASS GP-13 UI contract fixture: locked, current death, discovered tiles, keyboard activation, hidden/inert panel, finish/abort focus restore, ordinary death and victory.');

 await page.route('**/index.html?*',route=>route.fulfill({body:src,contentType:'text/html'}));
 await page.goto(server.origin+'/index.html?debug=1&raf=timer');
 await page.waitForFunction(()=>window.TT&&window.DWLoad?.snapshot().state==='ready',null,{timeout:120000});
 await page.evaluate(()=>{document.getElementById('openingSkip').click();document.getElementById('openingSkip').click();});
 await page.waitForFunction(()=>document.getElementById('opening').hidden);
 await page.fill('#playerName','Replay Tester');await page.click('#modeHunt');
 await page.waitForFunction(()=>TT.getPhase()==='prep'&&!document.body.classList.contains('deploying'),null,{timeout:30000});
 // Previous-profile pit unlock is a fixture; current cave unlock uses the real death path.
 await page.evaluate(()=>{localStorage.setItem('tt_death_log',JSON.stringify(['tentacles']));TT.beginScriptedKill('cave',TT.POI.caves.find(c=>c.theme==='chalk'));TT.finishScriptedKill();});
 await page.keyboard.press('Space');await page.waitForFunction(()=>document.querySelector('#win.show'));
 assert(await page.locator('#watchAgain').isVisible());assert.equal(await page.locator('button.replay-tile').count(),2);
 await page.screenshot({path:path.join(shots,'death-screen.png')});
 const before=await page.evaluate(()=>({day:TT.getDay(),bank:TT.getBank(),log:localStorage.getItem('tt_death_log'),body:document.body.className}));
 await page.evaluate(()=>{window.replayPhases=[];window.addEventListener('dw-game',({detail:d})=>{if(d.type==='scripted-death-replay')replayPhases.push(d.phase);});document.getElementById('watchAgain').click();});
 await page.waitForTimeout(400);
 const playback=await page.evaluate(()=>({playing:TT.isScriptedDeathReplay(),time:TT.getScriptedKill()?.t,phases:replayPhases}));
 console.log('Production playback after 400ms:',JSON.stringify(playback));
 await page.screenshot({path:path.join(shots,'playback.png')});
 assert(playback.playing&&playback.time>0,'production replay survives normal frames and advances');
 await page.waitForFunction(()=>!TT.isScriptedDeathReplay(),null,{timeout:20000});
 assert.deepEqual(await page.evaluate(()=>replayPhases),['start','end']);
 assert(await page.locator('#win').isVisible());
 const after=await page.evaluate(()=>({day:TT.getDay(),bank:TT.getBank(),log:localStorage.getItem('tt_death_log'),body:document.body.className}));
 assert.deepEqual(after,before);assert.deepEqual(errors,[]);
 await page.screenshot({path:path.join(shots,'restored.png')});
 await page.locator('[data-replay="tentacle"]').click();await page.waitForTimeout(400);
 assert(await page.evaluate(()=>TT.isScriptedDeathReplay()&&TT.getScriptedKill().t>0),'catalogue starts actual pit replay');
 await page.evaluate(()=>TT.abortScriptedKill());
 assert(await page.locator('#win').isVisible());
 assert(await page.locator('[data-replay="tentacle"]').evaluate(el=>el===document.activeElement));
 assert.deepEqual(await page.evaluate(()=>({day:TT.getDay(),bank:TT.getBank(),log:localStorage.getItem('tt_death_log'),body:document.body.className})),before);
 console.log('PASS GP-13 production UI and natural playback, no bank/day/profile changes. Stand-in renderer; real graphics need crew QA.');
}finally{if(browser)await browser.close();server.close();}
