/**
 * Dead-Wave player copy — GP-1, 2026-09-23. ChatGPT owns this catalogue.
 * Native ES module; no imports, DOM/storage/audio access, timers or Three.js.
 * Wired into the player UI. Owners migrate remaining callers through these keys.
 *
 * Usage: text('hq.deposit', { count: 2, interact: 'E' }).
 * Returns PLAIN TEXT. Use textContent/canvas text; never insert it as HTML.
 * Parameters are substituted once, so a callsign containing {name} stays literal.
 * Missing keys/parameters and invalid counts throw; test callers before wiring.
 * Input labels default to today's controls, but callers can override by action.
 * Supply numeric formatting (clock/precision) at the call site, never markup.
 *
 * Keys follow semantic namespaces, not DOM IDs or source line numbers. Keep
 * existing keys until all owners migrate. Tier numbers are stable game tiers.
 * legacy.* is migration-only copy: retire Skip prep in GP-2; do not use the
 * legacy menu description in the simplified menu. Other GP-2/3/4/5 and objective
 * entries are copy only, not implementations or promises those features exist.
 * World cave names preserve the current cardinal names; Claude owns later IDs.
 *
 * Inventory: shell/accessibility, HUD/maps, settings/tips, shop and catalogues,
 * builds/fortification/errors, combat/waves, interaction, deaths, debug UI;
 * plus the approved UI spec. Internal IDs, shader source, styles, logs and SVG
 * paths are deliberately not player copy. Snapshot SHA-256:
 * 96f0d03f2370c6df191b6346fcdcc06162732cbca11b162719681404ec3da7f3
 */

export const DEFAULT_INPUT_LABELS = Object.freeze({
  "fire": "LMB",
  "aim": "RMB",
  "move": "WASD",
  "forward": "W",
  "pause": "Esc",
  "map": "Tab",
  "run": "Shift",
  "jump": "Space",
  "fullscreen": "F11",
  "confirm": "Enter",
  "reload": "R",
  "rotate": "R",
  "melee": "F",
  "grenade": "G",
  "heal": "H",
  "weaponWheel": "Q",
  "interact": "E",
  "buildWheel": "B",
  "repair": "T",
  "carry": "T",
  "scrap": "X",
  "nightVision": "N",
  "akimbo": "Y",
  "laser": "Z",
  "flashlight": "L",
  "mute": "M",
  "dodge": "V",
  "crouch": "C",
});

const messages = {
  "quest.tune": "Tune",
  "quest.hint": "Five marks. Send them in order. One try a day.",
  "quest.send": "Send",
  "quest.clear": "Clear",
  "quest.north": "N",
  "quest.empty": "Unknown mark {place}",
  "quest.slot": "Mark {place}: {glyph}",
  "quest.wrong": "The tone swallows it. Tomorrow.",
  "quest.right": "The tone stops. The lake holds its breath.",
  "quest.silenced": "SILENCED · Until dawn",
  "quest.extraction": "Heron is due. The radio stays on her channel.",
  "quest.done": "The lake is quiet.",
  "quest.title": "The lake is quiet.",
  "quest.endedDay": "The tone stopped on day {day}.",
  "quest.glyph.0": "Eye",
  "quest.glyph.1": "Cup",
  "quest.glyph.2": "Moon",
  "quest.glyph.3": "Star",
  "quest.glyph.4": "Ladder",
  "quest.glyph.5": "Crown",
  "quest.glyph.6": "Drop",
  "quest.glyph.7": "Gate",
  "quest.door.shut": "It's warm. It's singing.",
  "quest.door.open": "The rune door is open.",
  "quest.door.elsewhere": "It's open. Somewhere.",
  "quest.runePistol": "{interact} · Take the rune pistol",
  "quest.runeFinish": "Rune finish",
  "haul.tags": "Tags {count} / 9",
  "haul.tagCollected": "Tag recovered · {count} / 9",
  "haul.strongbox": "Strongbox",
  "haul.open": "{interact} · Open strongbox",
  "haul.crate": "{interact} · Take supplies",
  "haul.tag": "{interact} · Recover tag",
  "haul.shard": "Rune shard recovered",
  "haul.full": "Make room for the supplies.",
  "badges.broughtThemHome.name": "Brought them home",
  "badges.broughtThemHome.description": "Recover all nine Gravewalker tags.",
  "badges.silence.name": "Silence",
  "badges.silence.description": "Silence the heart in the Marrow.",
  "records.trueEnding": "Silenced the tone on day {day}",
  "guide.map.title": "Know your way back",
  "guide.map.body": "{map} opens the map. It stays live, so find cover before looking around.",
  "guide.movement.title": "Keep moving",
  "guide.movement.body": "{move} move · {run} run · {jump} jump · {dodge} roll · hold {crouch} to crouch.",
  "guide.weapons.title": "Your weapon controls",
  "guide.weapons.body": "{fire} fire · {aim} aim · {reload} reload. Hold {weaponWheel} for the weapon wheel; tap to switch.",
  "guide.support.title": "Close-range options",
  "guide.support.body": "{melee} uses your blade. {grenade} throws a carried grenade; {heal} uses a carried MedPen. Your blast can hurt you.",
  "guide.gear.title": "Use the gear you own",
  "guide.gear.body": "Every gun starts with a flashlight ({flashlight}). Buy the helmet before night vision ({nightVision}); buy the laser ({laser}) separately. {akimbo} switches to an owned pair.",
  "guide.build.title": "Work on your defenses",
  "guide.build.body": "Hold {buildWheel} to choose a build; {fire} places it. {rotate} rotates, {repair} repairs, {scrap} scraps. Follow the build bar for targeting.",
  "guide.mortar.title": "Crew the mortar",
  "guide.mortar.body": "At a mortar, {interact} mounts or leaves it. {fire} fires; {carry} shoulders it. While carrying, {fire} or {interact} sets it down.",
  "guide.camera.title": "Look around",
  "guide.camera.body": "Scroll to zoom. Middle-drag turns the camera. In a sniper scope, scroll or middle-click changes magnification.",
  "guide.menus.title": "Keep the controls handy",
  "guide.menus.body": "{pause} pauses and opens Settings and Tips. {mute} mutes sound; {fullscreen} toggles fullscreen.",
  "streak.healSuffix": " · kills heal",
  "badges.summary": "Badges · {count}/{total}",
  "badges.new": "New",
  "badges.earned": "Earned",
  "badges.locked": "Locked",
  "badges.newList": "Earned this run: {names}",
  "badges.firstBank.name": "First deposit",
  "badges.firstBank.description": "Bank skulls at the HQ window.",
  "badges.relayOnline.name": "Relay online",
  "badges.relayOnline.description": "Repair the radio mast.",
  "badges.nightFive.name": "Night five",
  "badges.nightFive.description": "Reach night 5 in a completed run.",
  "badges.nightTen.name": "Night ten",
  "badges.nightTen.description": "Reach night 10 in a completed run.",
  "badges.nightTwenty.name": "Night twenty",
  "badges.nightTwenty.description": "Reach night 20 in a completed run.",
  "badges.fogSurvivor.name": "Through the fog",
  "badges.fogSurvivor.description": "Survive Fog Night.",
  "badges.kickedFree.name": "Kicked free",
  "badges.kickedFree.description": "Escape the guardian’s grasp.",
  "badges.outOnTheBoat.name": "Aboard Heron",
  "badges.outOnTheBoat.description": "Board Heron at the dock.",
  "badges.thousandSkulls.name": "A thousand banked",
  "badges.thousandSkulls.description": "Bank 1,000 skulls in one run.",
  "badges.thousandKills.name": "A thousand down",
  "badges.thousandKills.description": "Kill 1,000 zombies in one run.",
  "badges.hundredHeadshots.name": "Steady aim",
  "badges.hundredHeadshots.description": "Land 100 headshots in one run.",
  "badges.streakTwenty.name": "Twenty in a row",
  "badges.streakTwenty.description": "Reach a 20-kill streak in one run.",
  "cache.title": "Restocked today",
  "cache.row": "{site} · {reward}",
  "cache.collected": "Collected",
  "cache.medicalConvoy": "Threshold supply wreck",
  "cache.mapLegend": "Green supply squares mark these caches on your minimap.",
  "radioCall.title": "Tonight's call",
  "radioCall.down": "Relay down. Repair the radio mast to call for support.",
  "radioCall.closed": "The relay takes calls before the alarm.",
  "radioCall.ready": "Relay ready. One call tonight.",
  "radioCall.empty": "Nothing to call in tonight.",
  "radioCall.requested": "Requested: {card}",
  "radioCall.intelGranted": "Scout's eye received. Full Field Intel is now available.",
  "radioCall.ammo.name": "Ammo crate",
  "radioCall.ammo.description": "Call for ammunition at the radio mast.",
  "radioCall.medical.name": "Medical crate",
  "radioCall.medical.description": "2 MedPens and 2 grenades at the radio mast.",
  "radioCall.hardware.name": "Hardware crate",
  "radioCall.hardware.description": "Blueprint: {blueprint}. Collect it at the radio mast.",
  "radioCall.intel.name": "Scout's eye",
  "radioCall.intel.description": "Unlock full Field Intel for this run, free.",
  "radioCall.blackout.name": "Lights out",
  "radioCall.blackout.description": "Keep the HQ lamp dark tonight for 25% more skull value from kills.",

  // GP-94 (D-70): Ridgeline on the repaired relay, one unheard line each morning.
  "story.relay.delve": "Your trip below lit up our board. The tone's loudest under the white rock. We're calling it the Marrow.",
  "story.ending.secretRelay": "Ridgeline. Your tone's gone. Everyone's tone is gone. Heron's coming to get you. Walk to the dock.",
  "story.prop.graveyard": "Every coffin here is banded with iron. One's open. From the inside. — B.",
  "story.prop.mine": "Somebody cut the old bars off this mine. Recently. Bolt cutters. — Pike",
  "story.prop.trailhead": "MISSING · HIKERS · If you saw them on the trail, tell the rangers.",
  "story.prop.cordon": "CORDON · PGB · NOTHING LEAVES",
  "story.prop.warrenRoot": "SURVEY · WARREN 1 · ROOT · DO NOT ENTER",
  "story.prop.warrenShale": "SURVEY · WARREN 2 · SHALE · DO NOT ENTER",
  "story.prop.warrenIron": "SURVEY · WARREN 3 · IRON · DO NOT ENTER",
  "story.prop.warrenWet": "SURVEY · WARREN 4 · WET · DO NOT ENTER",
  "story.prop.warrenHill": "SURVEY · WARREN 5 · HILL · DO NOT ENTER",
  "story.branch": "PGB · Paranormal Ground Branch",
  "story.unit": "Gravewalkers",
  "story.relay.title": "Ridgeline · Relay",
  "story.relay.silent": "RELAY · SILENT",
  "story.relay.awaiting": "RELAY · ONLINE. Listening for Ridgeline.",
  "story.relay.1": "Relay's up. This is Ridgeline. We lost FOB Threshold three weeks ago. All twelve. Good to hear anything. Hold where you are.",
  "story.relay.2": "Threshold was a lockdown, nothing more. Wall up, look around, report. They had four quiet days.",
  "story.relay.3": "Their last log: 02:14, a tone on every channel. Then the relay went dead. Somebody pulled the fuse.",
  "story.relay.4": "That tone is still under your traffic. Low, on no band we use. It doesn't come through the air.",
  "story.relay.5": "Night shift says it gets louder after dark. Your nights getting worse? Thought so.",
  "story.relay.6": "Supply's stretched thin. One call a day, that's what we can spare. Make it count.",
  "story.relay.7": "The skulls you're sending all carry the same mark. Research is very happy with you. Keep them coming.",
  "story.relay.8": "We triangulated the tone. It's coming from under your lake. Through the water. Through the rock.",
  "story.relay.9": "Our file on that valley is a hundred years old. A mining town, Coldwater. Empty in one winter. They buried their dead in iron.",
  "story.relay.10": "The dead walk toward the tone like moths to a lamp. Every night it's stronger, every night there are more. That's your wave.",
  "story.relay.11": "Six caves, all running down toward the lake. The white one's sealed with carved stone older than our files. Leave it shut.",
  "story.relay.12": "We can't send a team in. We sent one. We can send a plane. Night twenty. Stay alive until then.",
  "story.relay.13": "When the lake breathes out, the fog comes with it. Keep your back to a wall and your ears open.",
  "story.relay.14": "The tone has a rhythm. It repeats, over and over. Our tech swears it's almost a word.",
  "story.relay.15": "Something big is walking your trails by day. Tracks the size of a truck. Give it room, or give it everything.",
  "story.relay.16": "If anything could shut that tone off, it's down where it starts. We don't know how. We're sorry.",
  "story.relay.17": "Heron's crew volunteered. All of them. Don't make them wait.",
  "story.relay.18": "Heron's fuelled. Two nights out. The dead will throw everything at your walls tonight; they can hear her coming too.",
  "story.relay.19": "One night left. When she's due, call us from the board. Flares at the dock, she sets down on the lake and taxis in. Get aboard.",
  "story.relay.20": "Tonight's the night. Call Heron when you're ready. Or stay. Some do. Ridgeline, out.",
  "story.prop.relayBroken": "Maintenance tag: Tone on all channels 02:14. Pulled the fuse to make it stop. Didn't. — Okafor",
  "story.prop.title": "FIELD NOTE",
  "story.prop.convoy": "Threshold's stores. Signed for: twelve. Need: fewer every night.",
  "story.prop.utilityTruck": "Threshold's stores. Signed for: twelve. Need: fewer every night.",
  "story.prop.ranger": "Rangers' search base. Their board says six hikers missing. We've found none of them. — B.",
  "story.prop.hikers": "Six tents, six packs, nobody. Camera's last clip: the mine, a rope, everyone laughing. — Pike",
  "story.prop.trapper": "Horseshoes on every door. Iron in the cellar walls. The old man knew something. — Okafor",
  "story.prop.fuel": "Threshold's stores. Signed for: twelve. Need: fewer every night.",
  "story.prop.dock": "EXTRACTION POINT · HERON · EVERY 6 HRS. Someone has crossed out every time.",
  "story.dock.signTitle": "EXTRACTION POINT",
  "story.dock.signCraft": "HERON",
  "story.dock.signInterval": "EVERY 6 HRS",
  "story.dock.signTimes": "00:00     06:00\n12:00     18:00",
  "story.prop.watchtower": "Pencil on the rail: Count them from the tower. Five.",
  "story.tower.railClue": "Count them from the tower. Five.",
  "story.prop.hq": "THRESHOLD · LOCKDOWN · DO NOT OPEN",
  "story.survivor.reyes.found": "Don't shoot. I've been mud for three weeks.",
  "story.survivor.reyes.morning": "I built that wall. Built it to keep things out. Turns out it keeps us in.",
  "story.survivor.reyes.aboard": "Spc. Pike, mechanic. Wants to see the wall from the outside.",
  "story.survivor.voss.found": "I watched it happen from up there. Couldn't hit enough of them. Got one more rifle if you want it.",
  "story.survivor.voss.morning": "From the tower the stones under the lake blink. In order. Every night. I wrote it down somewhere.",
  "story.survivor.voss.aboard": "Sgt. Brandt. Counted every shot. Says he still owes nine.",
  "story.survivor.kettle.found": "Iron walls. They walk straight past. Took me three weeks to believe it.",
  "story.survivor.kettle.morning": "I pulled the relay's fuse that night. Thought I was shutting the tone out. I was shutting us out.",
  "story.survivor.kettle.aboard": "Cpl. Okafor, signals. She'll be the one explaining it to Ridgeline.",
  "story.ending.boat": "Heron took you out on night {night}.",
  "story.ending.hot": "Heron took you out on night {night}, with the dead still on the dock.",
  "story.ending.secret": "The lake is quiet.",

  // common
  "common.on": "on",
  "common.off": "off",
  "common.down": "down",
  "common.enabled": "ON",
  "common.unknown": "—",
  "common.infinity": "∞",
  "common.ellipsis": "…",
  "common.back": "Back",
  "common.close": "Close",
  "common.ready": "Ready",
  "common.new": "NEW",
  "common.and": "{first} and {second}",
  "common.or": "{first} or {second}",
  "common.list": "{first} · {second}",
  "common.fraction": "{value} / {max}",
  "common.percent": "{value}%",
  "common.seconds": "{value}s",
  "common.metres": "{value} m",
  "common.multiplier": "{value}×",
  "common.price": "{amount} Cash",
  "common.priceCompact": "${amount}",
  "common.empty": "",
  "common.unavailable": "Unavailable",

  // GP-95: canonical Story v2 survivor copy; legacy IDs remain compatible.
  "menu.motto": "Against What Should Not Be.",
  "hq.designation.branch": "PGB",
  "hq.rear.lockdown": "LOCKDOWN",
  "hq.rear.sealed": "DO NOT OPEN",
  "hq.designation.kind": "GRAVEPOST",
  "hq.designation.name": "THRESHOLD",
  "hq.legacy.program": "PROJECT",
  "hq.legacy.name": "NIGHTGLASS",
  "hq.legacy.current": "FIELD EQUIPMENT",
  "hq.mural.title": "DEADWALKERS",
  "hq.mural.motto": "Against What Should Not Be",
  "survivor.heal": "{interact} · {name}: patch you up",
  "survivor.close": "Close",
  "survivor.talk": "{interact} · Talk to {name}",
  "survivor.talkTitle": "{name}",
  "badges.nobodyLeftBehind.name": "Nobody left behind",
  "badges.nobodyLeftBehind.description": "Bring Okafor, Brandt and Pike aboard Heron.",
  "story.survivor.okafor.name": "Cpl. Dana Okafor",
  "story.survivor.okafor.found": "Iron walls. They walk straight past. Took me three weeks to believe it.",
  "story.survivor.okafor.roof": "I pulled the relay's fuse that night. Thought I was shutting the tone out. I was shutting us out.",
  "story.survivor.okafor.aboard": "Cpl. Okafor, signals. She'll be the one explaining it to Ridgeline.",
  "story.survivor.brandt.name": "Sgt. Eli Brandt",
  "story.survivor.brandt.found": "I watched it happen from up there. Couldn't hit enough of them. Got one more rifle if you want it.",
  "story.survivor.brandt.roof": "From the tower the stones under the lake blink. In order. Every night. I wrote it down somewhere.",
  "story.survivor.brandt.aboard": "Sgt. Brandt. Counted every shot. Says he still owes nine.",
  "story.survivor.pike.name": "Spc. Pike",
  "story.survivor.pike.found": "Don't shoot. I've been mud for three weeks.",
  "story.survivor.pike.roof": "I built that wall. Built it to keep things out. Turns out it keeps us in.",
  "story.survivor.pike.aboard": "Spc. Pike, mechanic. Wants to see the wall from the outside.",

  // menu
  "menu.title": "Dead Wave",
  "menu.titleFirst": "Dead",
  "menu.titleSecond": "Wave",
  "menu.play": "Play",
  "menu.settings": "Settings",
  "menu.credits": "Credits",
  "menu.quit": "Quit",
  "menu.callsign": "Callsign",
  "menu.namePlaceholder": "Enter your name",
  "menu.nameRequired": "Enter your name to play.",
  "menu.signal": "Signal established",
  "menu.closeWindow": "You can close this window.",
  "credits.title": "Credits",
  "credits.creator.label": "Created by",
  "credits.creator.name": "Jerry Koller",
  "credits.crew.label": "Dead-Wave crew",
  "credits.crew.names": "Claude · Cursor · ChatGPT · Grokbot · Antigravity",
  "credits.animation.label": "Animation reference",
  "credits.animation.body": "Universal Animation Library 1 and 2 by Quaternius · CC0 1.0",
  "credits.music.label": "Music",
  "credits.music.body": "Songs and source tracks from Jerry · Music direction and arrangements by Claude",

  // opening
  "opening.label": "Dead Wave opening",
  "opening.videoLabel": "Caracal studio intro",
  "opening.play": "Play intro with sound",
  "opening.connecting": "Connecting",
  "opening.reload": "Reload",
  "opening.soundOn": "Sound on",
  "opening.soundOff": "Sound off",
  "opening.skip": "Skip · {pause}",

  // loading
  "loading.terrain": "Preparing terrain…",
  "loading.world": "Preparing the world…",
  "loading.zombies": "Preparing enemies…",
  "loading.shaders": "Preparing graphics…",
  "loading.ready": "Ready",
  "loading.waiting": "Still working: {stage}",
  "loading.failed": "Couldn't finish loading.",
  "loading.retry": "Try again",
  "loading.unknown": "Preparing game…",
  "loading.units": "{completed} / {total} {unit}",
  "loading.error": "Unable to load",
  "loading.complete": "Complete",
  "loading.pending": "Waiting",
  "loading.active": "In progress",
  "loading.substage.terrain": "Terrain",
  "loading.substage.rocks": "Rocks",
  "loading.substage.trees": "Trees",
  "loading.substage.actors": "Gravewalker, weapons and enemies",
  "loading.substage.foliage": "Ground cover",
  "loading.substage.pois": "Landmarks and map",
  "loading.substage.setup": "Scene setup",
  "loading.substage.compile": "Graphics preparation",
  "loading.substage.loop": "Renderer startup",
  "loading.substage.warmup": "First-frame preparation",
  "loading.substage.bake": "Reading the world",
  "loading.substage.generate": "Generating the world",
  "loading.stage.terrain": "Terrain",
  "loading.stage.world": "World",
  "loading.stage.zombies": "Enemies",
  "loading.stage.shaders": "Graphics",
  "loading.stage.ready": "Ready",
  "loading.stage.load": "Game loading",

  // legacy
  "legacy.loading.world": "Loading world",
  "legacy.loading.equipment": "Preparing equipment",
  "legacy.loading.scene": "Preparing scene",
  "legacy.loading.finishing": "Finishing up",
  "legacy.loading.still": "Still loading",
  "legacy.settings.skipPrep": "Skip prep time: {state}",

  // error
  "error.rendererTitle": "Dead Wave can’t start",
  "error.rendererUnsupported": "This machine reported neither WebGPU nor WebGL2.",
  "error.rendererHelp": "Update your browser or enable hardware acceleration, then reload.",
  "error.unknown": "Unknown error",
  "error.briefing": "Briefing unavailable",
  "error.generic": "Something went wrong. Try again.",

  // settings
  "settings.title": "Settings",
  "settings.music": "Music",
  "settings.sfx": "SFX",
  "settings.look": "Look",
  "settings.graphics": "Graphics",
  "settings.low": "Low",
  "settings.medium": "Medium",
  "settings.high": "High",
  "settings.max": "Max",
  "settings.camera": "Camera",
  "settings.followCursor": "Follow cursor: {state}",
  "settings.autoTilt": "Auto tilt",
  "settings.tiltOff": "Off",
  "settings.tiltGentle": "Gentle",
  "settings.tiltStrong": "Strong",
  "settings.screen": "Screen",
  "settings.fullscreen": "Fullscreen: {state}",
  "settings.fullscreenUnavailable": "Fullscreen unavailable",
  "settings.overlay": "Overlay",
  "settings.performance": "FPS & hardware: {state}",
  "settings.ragdoll": "Ragdoll",
  "settings.ragdollState": "Physics reactions: {state}",
  "settings.prep": "Prep",
  "settings.prepHelp": "Start the next wave at the HQ panel.",
  "settings.sensitivity": "{value}x",

  // pause
  "pause.title": "Paused",
  "pause.description": "Game paused. Quitting ends this run. Play starts a new run.",
  "pause.resume": "Resume",
  "pause.tips": "Tips",
  "pause.quit": "End run & quit to menu",

  // hud
  "hud.cash": "Cash",
  "hud.skulls": "Skulls",
  "hud.skullRecall": {"one":"+{count} skull","other":"+{count} skulls"},
  "guardian.escape.prompt": "Kick free! ({interact})",
  "guardian.escape.coach": "Tap {interact} before it reaches the cave · {presses}/{need}",
  "guardian.escape.lostSkulls": "It took your skulls.",
  "guardian.escape.free": "You kicked free.",
  "hud.skullValue": "Skull value: {value}",
  "hud.skullBag": "{count} ({value} skull value)",
  "hud.health": "Health",
  "hud.armor": "Armor",
  "hud.killStreak": "Kill streak",
  "hud.land": "Land r{radius}",
  "hud.landOpen": "{radius} · Land open",
  "hud.time": "{period} · {time}",
  "hud.day": "Daylight",
  "hud.night": "Night",
  "hud.rain": "Rain",
  "hud.grace": "Grace",
  "hud.bloodMoon": "Ember Night",
  "hud.tactical": "NVG {nvg} · Laser {laser} · Light {light}",
  "hud.scopeZoom": "{zoom}X",
  "hud.headshot": "HEADSHOT",
  "hud.critical": "CRIT",
  "hud.house": "House {hp} / {max}",
  "hud.ammo": "{loaded} / {magazine} · {reserve} spare",
  "hud.grenades": "{grenade}×{count}",
  "hud.medpens": "{heal}×{count}",
  "hud.reloading": "Reloading",
  "hud.reload": "Reload · {reload}",
  "hud.noFuel": "No fuel",
  "hud.noAmmo": "No ammo · supply terminal",
  "hud.sawFuel": "Gas {fuel} / {max}",
  "hud.sawRunning": "Gas {fuel} / {max} · Running",
  "hud.sawEmpty": "Gas {fuel} / {max} · EMPTY",
  "hud.streakPower": "x{multiplier} skull value · {power}",
  "hud.wave.initial": "Day — · Prep",
  "hud.wave.menu": "Wave Day — · Press Play",
  "hud.wave.disabled": "Wave Day {day} · No waves (nodead)",
  "hud.wave.prep": "Wave Day {day} · Prep · Next: {total} · start at the HQ",
  "hud.wave.active": "Wave Day {day} · Zombies left: {remaining}",
  "hud.wave.idle": "Wave Day {day}",
  "hud.wave.grace": "{line} · Z-Grace",

  // map
  "map.close": "{map} close",
  "map.zombies": "zombies",
  "map.kiosk": "supply terminal",
  "map.hq": "HQ",
  "map.builds": "builds",
  "map.reach": "dashed ring: minimap reach ({distance} m)",
  "map.ranger": "RANGER CAMP",
  "map.hikers": "HIKERS CAMP",
  "map.trapper": "TRAPPER CAMP",
  "map.campsite": "CAMPSITE",
  "map.cabin": "CABIN",
  "map.tower": "WATCHTOWER",
  "map.graveyard": "GRAVEYARD",
  "map.mast": "RADIO MAST",
  "map.dock": "DOCK",
  "map.shed": "HUT",
  "map.bridge": "BRIDGE",
  "map.pit": "UNDERWATER PIT",

  // compass
  "compass.n": "N",
  "compass.ne": "NE",
  "compass.e": "E",
  "compass.se": "SE",
  "compass.s": "S",
  "compass.sw": "SW",
  "compass.w": "W",
  "compass.nw": "NW",

  // world
  "world.hq": "FOB Threshold",
  "world.hqWindow": "HQ sample window",
  "world.dock": "Dock",
  "world.mast": "Radio mast",
  "world.tower": "Watchtower",
  "world.graveyard": "Graveyard",
  "world.pit": "Underwater Pit",
  "world.campsite": "Campsite",
  "world.ranger": "Ranger Camp",
  "world.hikers": "Hikers Camp",
  "world.trapper": "Trapper Camp",
  "world.cabin": "Cabin",
  "world.shed": "Hut",
  "world.wreck": "Truck wreck",
  "world.wanderer": "Wandering colossus",
  "world.bridge": "Bridge",
  "world.cave.north": "North Cave",
  "world.cave.northeast": "Northeast Cave",
  "world.cave.east": "East Cave",
  "world.cave.southeast": "Southeast Cave",
  "world.cave.south": "South Cave",
  "world.cave.southwest": "Southwest Cave",
  "world.cave.west": "West Cave",
  "world.cave.northwest": "Northwest Cave",
  "world.cave.outer": "Outer Rim Cave",

  // hq
  "hq.deposit": {"one":"{interact} — Bank {count} skull","other":"{interact} — Bank {count} skulls"},
  "hq.depositValue": {"one":"{interact} — Bank {count} skull ({value} skull value)","other":"{interact} — Bank {count} skulls ({value} skull value)"},
  "hq.processing": "Processing skull samples…",
  "hq.banked": "Banked {amount} Cash",
  "hq.processed": {"one":"{count} skull processed — spend the Cash at the supply terminal","other":"{count} skulls processed — spend the Cash at the supply terminal"},
  "hq.empty": "Bring skull samples to the HQ sample window.",
  "hq.busyTitle": "HQ BUSY",
  "hq.busy": "Wait for the ding",
  "hq.emptyTitle": "NO SKULLS",
  "hq.alarm": "ALARM",
  "hq.alarmSounding": "Alarm sounding…",
  "hq.start": "{interact} — Sound the alarm: start the wave",
  "hq.inProgress": "Wave under way",
  "hq.waveTitle": "WAVE UNDER WAY",
  "hq.betweenWaves": "The panel works between waves",
  "hq.disabledTitle": "NODEAD IS ON",
  "hq.disabled": "Waves are switched off",
  "hq.heard": "Day {day} — they heard that",
  "hq.startReminderTitle": "START AT THE HQ",
  "hq.startReminder": "Sound the alarm on the panel by the HQ’s front wall",

  // interaction
  "interaction.kiosk": "{interact} — Supply Terminal",
  "interaction.kioskLocked": "Supply terminal locked — opens during prep",
  "interaction.mortar": "{interact} — Man the mortar",
  "interaction.mortarLeave": "{interact} — Leave the mortar · {carry} — Shoulder it",
  "interaction.closeDoor": "{interact} — Close the door",
  "interaction.openDoor": "{interact} — Open the door",
  "interaction.lowerStairs": "{interact} — Lower the stairs",
  "interaction.raiseStairs": "{interact} — Raise the stairs",
  "interaction.grave": "Here lies {name} — fell on Day {day}",

  // CIF: the camouflage window at the HQ (CU-61, Jerry direct). Swaps are free.
  // GP-93: CU-70 dressing-room labels, including CL-97 style choices.
  "cif.menu.eyebrow": "FOB THRESHOLD / PERSONAL EQUIPMENT",
  "cif.menu.preview": "Your Gravewalker",
  "cif.menu.drag": "Drag the Gravewalker to turn. Changes are saved as you choose.",
  "cif.menu.gunNote": "Finishes apply to the selected weapon. This preview shows your Gravewalker.",
  "cif.menu.pause": "Pause rotation",
  "cif.menu.rotate": "Rotate",
  "cif.menu.front": "Front view",
  "cif.menu.available": "Available",
  "cif.menu.locked": "Locked",
  "cif.menu.all": "All",
  "cif.menu.count": "{label} · {count}",
  "cif.menu.current": "Equipped: {finish}",
  "cif.menu.factory": "Factory finish",
  "cif.menu.choose": "Choose your options below.",
  "cif.menu.reset": "Reset {category}",
  "cif.pattern.rune": "Rune finish",
  "cif.menu.special": "Special finishes",
  "cif.menu.patterns": "Patterns",
  "cif.menu.equipped": "Equipped",
  "cif.menu.issued": "Issued",
  "cif.menu.earned": "Earned",
  "cif.menu.empty": "All finishes earned. Your full collection is available.",
  "cif.menu.close": "Done · E / Esc",
  "cif.menu.saved": "Saved automatically",
  "cif.tab.head": "Head",
  "cif.tab.body": "Clothing",
  "cif.tab.kit": "Equipment",
  "cif.tab.him": "Appearance",
  "cif.tab.guns": "Weapons",
  "cif.item.cap": "Hat",
  "cif.item.helmet": "Helmet",
  "cif.item.mask": "Balaclava",
  "cif.item.eyewear": "Eyewear",
  "cif.item.shirt": "Shirt",
  "cif.item.trousers": "Trousers",
  "cif.item.gloves": "Gloves",
  "cif.item.boots": "Boots",
  "cif.item.carrier": "Armour",
  "cif.item.pads": "Pads",
  "cif.item.holster": "Holsters",
  "cif.item.belt": "Belt",
  "cif.item.pack": "Backpack",
  "cif.boot.black": "Black",
  "cif.boot.brown": "Brown",
  "cif.boot.tan": "Tan",
  "cif.dress.hint": "Dress each piece separately. Four camos issued. Earn the rest in the field.",
  "cif.dress.reset": "Reset this tab",
  "cif.him.hair": "Hair",
  "cif.him.eyes": "Eyes",
  "cif.him.skin": "Skin",
  "cif.him.black": "Black",
  "cif.him.darkBrown": "Dark brown",
  "cif.him.brown": "Brown",
  "cif.him.auburn": "Auburn",
  "cif.him.blond": "Blond",
  "cif.him.grey": "Grey",
  "cif.him.hazel": "Hazel",
  "cif.him.green": "Green",
  "cif.him.blue": "Blue",
  "cif.him.skin0": "Tone 1",
  "cif.him.skin1": "Tone 2",
  "cif.him.skin2": "Tone 3",
  "cif.him.skin3": "Tone 4",
  "cif.him.skin4": "Tone 5",
  "cif.him.skin5": "Tone 6",
  "cif.style.cover": "Cover",
  "cif.style.boonie": "Boonie",
  "cif.style.ballcap": "Ballcap",
  "cif.style.ballcapBack": "Ballcap, backwards",
  "cif.style.none": "None",
  "cif.style.aviators": "Teardrop shades",
  "cif.style.pitViper": "Wraparounds",
  "cif.style.wayfarer": "Classic shades",
  "cif.style.goggles": "Ballistic goggles",
  "cif.style.down": "Sleeves down",
  "cif.style.rolled": "Sleeves rolled",
  "cif.style.trousers": "Trousers",
  "cif.style.shorts": "Shorts",
  "cif.style.true": "Gloves on",
  "cif.style.false": "Bare hands",
  "cif.title": "CIF",
  "cif.subtitle": "Central Issue Facility",
  "cif.hint": "Pick a pattern. Swapping is free, as often as you like.",
  "cif.prompt": "E — CIF (swap your camo)",
  "armory.prompt": "E — Armory (set your loadout)",
  "cif.wearing": "Wearing",
  "cif.free": "Free",
  "cif.close": "Back to the fight (E / Esc)",
  "armory.open": "Armory",
  "armory.title": "Armory",
  "armory.hint": "Pick a slot, then choose a stored gun. Your sidearm stays on your hip.",
  "armory.hip": "Hip holster · {gun}",
  "armory.primary": "Primary {number}",
  "armory.secondary": "Secondary {number}",
  "armory.empty": "Empty slot",
  "armory.shelf": "Stored guns",
  "armory.shelfEmpty": "No guns stored",
  "armory.loaded": "{count} loaded",
  "armory.magazines": {"one":"{count} magazine","other":"{count} magazines"},
  "armory.rounds": {"one":"{count} loose round","other":"{count} loose rounds"},
  "armory.stow": "Move to shelf",
  "armory.done": "Done",
  "cif.issued": "CAMO ISSUED",
  "cif.pattern.m81": "Classic Woodland",
  "cif.pattern.flecktarn": "Flecktarn",
  "cif.pattern.ucp": "UCP",
  "cif.pattern.multicam": "Arid Blend",
  "cif.pattern.mccuu": "Desert Digital",
  "cif.pattern.marpat": "Digital Woodland",
  "cif.pattern.french": "French Woodland",
  "cif.pattern.dpmWoodland": "DPM Woodland",
  "cif.pattern.dpmDesert": "DPM Desert",
  "cif.pattern.m14Woodland": "M14 Nigeria Woodland",
  "cif.pattern.m14Desert": "M14 Nigeria Desert",
  "cif.pattern.greenMulticam": "Jungle Blend",
  "cif.pattern.dcu": "DCU",
  "cif.pattern.dbdu": "DBDU",
  "cif.pattern.cadpat": "Boreal Digital",
  "cif.pattern.giraffe": "South African Giraffe",
  "cif.pattern.swissTaz": "Swiss TAZ 07",
  "cif.pattern.zaireLeopard": "Zaire Green Leopard",
  "cif.pattern.cactus": "Sri Lankan Cactus",
  "cif.pattern.serbianKarst": "Serbian Karst",
  "cif.pattern.papDigital": "PAP Digital (trial)",
  "cif.pattern.teloMimetico": "M1929 Telo Mimetico",
  "cif.pattern.sumpftarn": "Sumpftarnmuster",
  "cif.pattern.tigerStripe": "Tiger Stripe",
  "cif.pattern.oliveDrab": "Olive Drab",
  "cif.pattern.armyGreen": "Army Green",
  "cif.pattern.fieldDrab": "Field Drab",
  "cif.pattern.drab": "Drab",
  "cif.pattern.camouflageGreen": "Camouflage Green",
  "cif.pattern.foliageGreen": "Foliage Green",
  "cif.pattern.rifleGreen": "Rifle Green",
  "cif.pattern.darkOliveGreen": "Dark Olive Green",
  "cif.pattern.olive": "Olive",
  "cif.pattern.khaki": "Khaki",
  "cif.pattern.darkKhaki": "Dark Khaki",
  "cif.pattern.desertSand": "Desert Sand",
  "cif.pattern.ecru": "Ecru",
  "cif.pattern.tan": "Tan",
  "cif.pattern.coyoteBrown": "Coyote Brown",
  "cif.pattern.sandyBrown": "Sandy Brown",
  "cif.pattern.feldgrau": "Feldgrau",
  "cif.pattern.battleshipGrey": "Battleship Grey",
  "cif.pattern.gunmetal": "Gunmetal",
  "cif.pattern.charcoal": "Charcoal",
  "cif.pattern.navyBlue": "Navy Blue",
  "cif.pattern.airForceBlueRaf": "Air Force Blue (RAF)",
  "cif.pattern.airForceBlueUsaf": "Air Force Blue (USAF)",
  "cif.pattern.prussianBlue": "Prussian Blue",
  "cif.pattern.forestGreen": "Forest Green",
  "cif.solids": "Plain colours",
  "unlocks.free": "Available from the start",
  "unlocks.day": "Survive to night {count}",
  "unlocks.runs": "Finish {count} runs",
  "unlocks.streak": "Reach a streak of {count}",
  "unlocks.kills": "Kill {count} zombies in one run",
  "unlocks.headshots": "Land {count} headshots in one run",
  "unlocks.skulls": "Bank {count} skulls in one run",
  "unlocks.evacuated": {"one":"Get out on Heron once","other":"Get out on Heron {count} times"},
  "unlocks.badge": "Earn the {name} badge",
  "unlocks.toastOne": "New camo: {name}",
  "unlocks.toastMany": "New camos: {name} +{more} more",
  "unlocks.cheatTitle": "Dapper Dan",
  "unlocks.cheatDetail": "Every camo unlocked for this profile",

  // shop
  "shop.title": "Supply Terminal",
  "shop.balance": "Cash ${amount}",
  "shop.buy": "Buy — {price} Cash",
  "shop.owned": "Owned",
  "shop.ownedButton": "OWNED",
  "shop.full": "Full",
  "shop.fullButton": "FULL",
  "shop.locked": "LOCKED",
  "shop.maxed": "MAXED",
  "shop.shortfall": "Need {amount} more Cash",
  "shop.noCash": "NO CASH",
  "shop.close": "Back to the fight ({interact} / {pause})",
  "shop.blueprint": "{name} blueprint",
  "shop.blueprintCost": "Places for {cost} Cash.",
  "shop.armorBonus": "+{amount} armor",
  "shop.carried": "{count} / {capacity} carried",
  "shop.rank": "rank {rank}",
  "shop.findTitle": "FIND THE KIOSK",
  "shop.find": "The supply hatch in the east wall of the HQ (yellow square on the map)",
  "shop.lockedTitle": "KIOSK LOCKED",
  "shop.lockedReason": "It only trades during prep — clear the wave first",
  "shop.blueprintsHelp": "Unlock a build here. Each placed piece costs Cash.",
  "shop.tabs.weapons": "Weapons",
  "shop.tabs.ammo": "Ammo",
  "shop.tabs.gear": "Gear",
  "shop.tabs.upgrades": "Upgrades",
  "shop.tabs.build": "Blueprints",
  "shop.tabs.builds": "Builds",
  "shop.tabs.fortify": "Fortify",
  "shop.hint.weapons": "One-time unlocks. Bought guns join the {weaponWheel} rotation and come with full ammo: a loaded magazine and a full reserve.",
  "shop.weaponArrives": "Arrives night {night}",
  "shop.hint.ammo": "Buy full magazines, drums, belt boxes or tanks for each gun. Shotgun shells and launcher grenades are loose. {reload} loads from what you carry; tap twice to drop a magazine and reload faster.",
  "shop.hint.gear": "Tactical kit. Nothing here is issued; the nights are dark until you pay for eyes.",
  "shop.hint.upgrades": "Improve guns you own. Each gun fits one barrel or magazine mod at a time; switch between owned mods for free.",
  "shop.hint.build": "Blueprints put a build type into the {buildWheel} menu. Placing each piece still costs Cash on the spot.",
  "shop.hint.fortify": "Upgrade blueprints, tier by tier. Then take the Upgrade tool ({buildWheel} menu, Structure) to anything you have built and click it: each piece is upgraded one at a time, for the price shown.",
  "shop.ammo.restock": "Restock all",
  "shop.ammo.restockWeapon": "Restock",
  "shop.ammo.restockPrice": "Restock ${price}",
  "shop.ammo.restockFull": "Restock · Full",
  "shop.ammo.restockGunHelp": "Fill the {calibre} reserve to {capacity}. Whole-pack prices; {reload} reloads the gun.",
  "shop.ammo.restockFuelHelp": "Fill the chainsaw tank to {capacity}s at whole-pack prices.",
  "shop.ammo.short": "{count} short",
  "shop.ammo.allFull": "all full",
  "shop.ammo.restockHelp": "Fill carried magazines, loose ammo and chainsaw fuel. Hand grenades: {grenadePrice} Cash each, up to your carrying limit. {reload} reloads your gun.",
  "shop.ammo.fullHelp": "All ammo, fuel and hand grenades are full.",
  "shop.ammo.feedsMortar": "Feeds the mortar.",
  "shop.ammo.feeds": "Feeds {weapons}.",
  "shop.ammo.reserve": "{reserve} / {capacity} spare",
  "shop.ammo.magCount": "{count} / {capacity} carried",
  "shop.ammo.magPack": "Full · {count} {unit}",
  "hud.ammo.mags": "mags",
  "hud.ammo.loaders": "loaders",
  "hud.ammo.shells": "shells",
  "hud.ammo.rounds": "rounds",
  "hud.ammo.count": "{loaded} / {capacity} · {reserve} {unit}",
  "hud.ammo.reloading": "Reloading · {reserve} {unit}",
  "hud.ammo.magFill": "{rounds} of {size} rounds",
  "shop.ammo.pack": "+{quantity} {unit} to the reserve.",
  "shop.ammo.reserveFull": "Reserve is full.",
  "shop.ammo.packFeeds": "+{quantity} {unit} to the reserve. Feeds {weapons}.",
  "shop.ammo.packFeedsFull": "+{quantity} {unit} to the reserve. Feeds {weapons}. Reserve is full.",
  "shop.ammo.chainsaw": "Chainsaw gas",
  "shop.ammo.fuel": "{fuel}s / {capacity}s",
  "shop.ammo.fuelHelp": "+{seconds} seconds of cutting. Tops off at the tank cap.",
  "shop.ammo.nothing": "Nothing to feed",
  "shop.ammo.buyFirst": "Buy a gun first.",
  "shop.upgrade.machete": "Machete",
  "shop.upgrade.replacesKnife": "replaces the knife",
  "shop.upgrade.macheteHelp": "A proper blade for {melee}: {reach}m reach, {damage} damage and a wider arc (knife: {knifeReach}m, {knifeDamage}). Swings a touch slower.",
  "shop.upgrade.tank": "Bigger gas tank",
  "shop.upgrade.tankHelp": "+50% chainsaw fuel capacity ({seconds}s).",
  "shop.upgrade.pair": "{weapon} pair",
  "shop.upgrade.akimbo": "akimbo",
  "shop.upgrade.pairHelp": "A second {weapon} for the off hand. {akimbo} switches between one and two: twice the rate of fire and twice the loaded rounds, for a wider group, a slower reload, and no hand free for a grenade or the blade.",
  "shop.upgrade.biggerTank": "{weapon} bigger tank",
  "shop.upgrade.extendedMag": "{weapon} extended mag",
  "shop.upgrade.heavyBarrel": "{weapon} heavy barrel",
  "shop.upgrade.heavyBarrelHelp": "Halves recoil climb, but takes longer to ready and spreads shots wider while moving.",
  "shop.upgrade.fitted": "fitted",
  "shop.upgrade.fittedButton": "FITTED",
  "shop.upgrade.fit": "Fit free",
  "shop.upgrade.magHelp": "Magazine {before} → {after}, and a bigger reserve to match.",
  "shop.upgrade.fuelHelp": "Tank {before} → {after}, and a bigger reserve to match.",
  "shop.upgrade.nothing": "Nothing to upgrade yet",
  "shop.upgrade.buyFirst": "Buy a gun that takes an extended mag (or the chainsaw).",
  "shop.upgrade.fieldIntel": "Field Intel",
  "shop.upgrade.fieldIntelHelp": "See every enemy type, count and approach at the HQ panel.",
  "shop.fortify.toughness": "{hp} toughness (from {base}).",
  "shop.fortify.door": "+{hp} toughness on the wall it hangs in.",
  "shop.fortify.turret": "Damage ×{damage}, reach ×{range}, fire rate ×{rate}, toughness ×{hp}.",
  "shop.fortify.pieceCost": "Upgrading each piece: {cost} Cash.",
  "shop.fortify.requires": "Needs the {blueprint} blueprint first.",
  "shop.fortify.description": "{description} {stats} Upgrading each piece: {cost} Cash.",
  "shop.fortify.lockedDescription": "{description} {stats} Upgrading each piece: {cost} Cash. Needs the {blueprint} blueprint first.",
  "shop.gear.medpen": "MedPen",
  "shop.gear.medpenHelp": "Auto-injector. {heal} to jab one: heals 60% of max health. Natural regen only ever climbs back to 40%.",
  "shop.gear.repairArmor": "Repair armor",
  "shop.gear.repairArmorHelp": "Patch the plates back up to full. Armor also comes back to full at the start of each day.",
  "shop.gear.armorFull": "Everything is in one piece.",

  // weapon
  "weapon.minigun.name": "Rotary Gun",
  "weapon.m4.name": "GW-4 Carbine",
  "weapon.ak.name": "KR-7 Rifle",
  "weapon.aa12.name": "Breacher-12",
  "weapon.pistol.name": "Pistol",
  "weapon.uzi.name": "Wasp SMG",
  "weapon.shotgun.name": "Shotgun",
  "weapon.revolver.name": "Revolver",
  "weapon.sniper.name": "Sniper",
  "weapon.launcher.name": "Launcher",
  "weapon.flamer.name": "Flamethrower",
  "weapon.chainsaw.name": "Chainsaw",
  "weapon.pistol.description": "Sidearm. Reliable, slow.",
  "weapon.uzi.description": "Spray-and-pray SMG. Short range, fast.",
  "weapon.shotgun.description": "Seven-pellet pump. Devastating up close.",
  "weapon.m4.description": "Full-auto rifle. The workhorse.",
  "weapon.revolver.description": "Six heavy rounds. One-taps most things.",
  "weapon.sniper.description": "True scope, 2X/4X/6X. Headshots from across the map.",
  "weapon.ak.description": "Harder-hitting full-auto rifle. Slower and looser than the GW-4, but every round counts for more.",
  "weapon.aa12.description": "Full-auto shotgun off a 20-round drum. Five pellets a shell and no pump to work — it hoses a corridor.",
  "weapon.launcher.description": "40mm contact-fused grenades. Six in the drum.",
  "weapon.minigun.description": "300-round spin-up. Melts hordes.",
  "weapon.chainsaw.description": "No ammo, just gas. Hold to cut.",
  "weapon.flamer.description": "Hold to hose a stream of burning fuel, about 7m. It sticks to what it hits, sets the ground alight — including under you — and fizzles out in water. Burning zombies spread it to whatever they touch.",

  // blade
  "blade.knife.name": "Knife",
  "blade.machete.name": "Machete",

  // calibre
  "calibre.9mm": "9mm",
  "calibre.45": ".45",
  "calibre.556": "5.56mm",
  "calibre.762": "7.62mm",
  "calibre.44": ".44",
  "calibre.338": ".338",
  "calibre.12ga": "12ga",
  "calibre.40mm": "40mm",
  "calibre.belt762": "7.62 belt",
  "calibre.fuel": "Fuel",
  "calibre.60mm": "60mm",

  // ammo
  "ammo.unit.fuel": "fuel",
  "ammo.unit.shells": "shells",
  "ammo.unit.grenades": "grenades",
  "ammo.unit.rounds": "rounds",

  // gear
  "gear.helmet.name": "Combat helmet",
  "gear.helmet.description": "Ballistic helmet: +25 armor. Its rails are where the night-vision mount goes.",
  "gear.vest.name": "Plate carrier",
  "gear.vest.description": "Front and back plates with mag pouches: +50 armor.",
  "gear.pads.name": "Knee & elbow pads",
  "gear.pads.description": "+15 armor, and you are back on your feet from a dodge roll sooner.",
  "gear.nvg.name": "Night vision",
  "gear.nvg.description": "Flip-down NVGs ({nightVision}) on the helmet rails. The nights get very dark without them.",
  "gear.nvg.requires": "Needs the helmet",
  "gear.laser.name": "Laser sight",
  "gear.laser.description": "Aiming laser on every gun ({laser}). Tighter groups, easier tracking.",
  "gear.flashlight.name": "Gun flashlight",
  "gear.flashlight.description": "Weapon-mounted light ({flashlight}). A cone of visibility at night.",

  // Earned skills
  "skills.title": "Skills",
  "skills.rank": "Rank {rank}",
  "skills.progress": "{xp} / {next} XP",
  "skills.max": "Max rank",
  "skills.rankToast": "{name} · rank {rank}",
  "skills.vitality.name": "Vitality",
  "skills.power.name": "Stopping power",
  "skills.hands.name": "Quick hands",
  "skills.legs.name": "Fleet foot",
  "skills.scavenger.name": "Scavenger",
  "skills.grenadier.name": "Grenadier",

  // weapon
  "weapon.message.notOwned": "{name} NOT OWNED",
  "weapon.message.buyGear": "Buy it at the supply terminal (Gear tab)",
  "weapon.message.noSecond": "NO SECOND GUN",
  "weapon.message.twoHanded": "{weapon} is a two-handed weapon",
  "weapon.message.akimboLocked": "AKIMBO NOT BOUGHT",
  "weapon.message.pairCost": "{weapon} pair costs {price} Cash (supply terminal, Upgrades)",
  "weapon.message.akimbo": "AKIMBO",
  "weapon.message.single": "SINGLE",
  "weapon.message.twoGuns": "Two guns up — no grenades, no blade",
  "weapon.message.oneGun": "Back to one gun",
  "weapon.message.acquired": "{weapon} ACQUIRED",
  "weapon.message.draw": "{weaponWheel} to bring it up",
  "weapon.message.pair": "{weapon} PAIR",
  "weapon.message.switchPair": "{akimbo} switches between one gun and two",
  "weapon.message.outOfAmmo": "OUT OF AMMO",
  "weapon.message.restock": "Restock at the supply terminal (Ammo tab)",
  "weapon.message.handsFull": "BOTH HANDS FULL",
  "weapon.message.freeHand": "{akimbo} goes back to one gun",
  "weapon.message.notBought": "{weapon} — NOT BOUGHT",
  "weapon.message.buy": "Buy it at the supply terminal ({price} Cash)",

  // build
  "build.upgrade.name": "Upgrade",
  "build.gate.name": "Gate",
  "build.pillar.name": "Structural pillar",
  "build.shovel.name": "Shovel",
  "build.window.name": "Window",
  "build.door.name": "Door",
  "build.platform.name": "Platform",
  "build.floor.name": "Floor",
  "build.stairs.name": "Stairs",
  "build.wire.name": "Barbed wire",
  "build.railing.name": "Railing",
  "build.barricade.name": "Barricade",
  "build.wall.name": "Wall",
  "build.spikes.name": "Spike trap",
  "build.sandbag.name": "Sandbag wall",
  "build.barrel.name": "Fuel drum",
  "build.mine.name": "Land mine",
  "build.lure.name": "Decoy beacon",
  "build.light.name": "Light turret",
  "build.flame.name": "Flame turret",
  "build.heavy.name": "Heavy turret",
  "build.mortar.name": "Mortar",
  "build.upgrade.description": "Point at something you built and click to take it up a tier: walls to stone and steel, doors to iron, turrets to Mk II and III, floors, gates, bars for windows. Each tier's blueprint is bought in the supply terminal's Fortify tab; {rotate} picks which part of a wall (its door or window, or the wall itself).",
  "build.gate.description": "Cuts a gate into a run of barbed wire, a barricade or a railing — point at it. {interact} opens and shuts it like a door. Shut, it holds like the run it replaced; upgrade it to iron and steel.",
  "build.pillar.description": "Steel post for the corner where four squares meet. On its own it holds up a floor or platform in each of those four squares; with a wall within three squares, in twelve. Its cap takes a turret.",
  "build.shovel.description": "Levels the cell you point at, and fills in any rabbit burrow in it, blending it into the ground around it. Rough or sloping ground refuses a build; this is how you fix it. Works on a cell that already has something standing in it.",
  "build.window.description": "Cuts a firing window in a wall. Ground-level windows let smaller zombies climb inside: fit steel mesh in Fortify to stop them. Weakens the wall.",
  "build.door.description": "Hangs a pair of doors in a wall — point at the wall. {interact} opens and shuts them: shut, they are as solid as the wall; open, anything can walk through — so close them behind you. Weakens the wall more than a window does.",
  "build.platform.description": "Steel deck on the walls of its square — or bolted onto a wooden floor as a gun mount (one per floor). Its raised middle lifts a turret over the rail line, and all four edges can take a railing.",
  "build.floor.description": "Wooden boards on the walls of its square, or bridging out from the wall of the square next door: a floor for the storey above and a roof for the one below. A platform can go on a floor; a floor never goes on a platform.",
  "build.stairs.description": "Takes the whole cell and ramps up a storey. Anything that walks can use them — including the horde, so mind where you put them.",
  "build.wire.description": "Half height, so you shoot straight over it. Runs along a square’s edge like a wall: on the ground, a deck’s rim, or strung along the top of a wall, sandbags or a barricade (point at it). Cuts anything that comes through it, and comes apart quickly.",
  "build.railing.description": "Low rail for a deck edge: {rotate} picks the edge, and a deck can be railed on all four with a turret in the middle. Your rounds go between the bars.",
  "build.barricade.description": "Cheap steel beams along a square’s edge. Slows and soaks. Goes on the ground, a deck, or along the top of a wall.",
  "build.wall.description": "Solid log wall along the edge of a square — {rotate} picks the edge, two in one square make a corner. Real stopping power.",
  "build.sandbag.description": "Low, tough cover along a square’s edge, or heaped along the top of a wall. Cheap to line a lane with.",
  "build.spikes.description": "Buried spike bed. Springs once when something steps into its square: spikes through everything standing on it, then it is spent and the square is free again.",
  "build.barrel.description": "Fuel drum. Shoot it when the pack is beside it; chains into its neighbours.",
  "build.mine.description": "Buried charge. Goes off under the first thing that steps on it.",
  "build.lure.description": "Flashing, screaming beacon. The horde chases it instead of you for 20s, then it burns out.",
  "build.light.description": "Auto-turret. Cheap, chattery, fine vs. shamblers.",
  "build.flame.description": "Short-range fire cone. Crowds hate it.",
  "build.heavy.description": "Slow, hard-hitting sentry gun.",
  "build.mortar.description": "Crew-served tube. {interact} to mount, {fire} lobs a shell at the reticle (arc shown), {carry} to shoulder it and carry it elsewhere. Shells sold under Ammo.",

  // fortify
  "fortify.wall.category": "Walls",
  "fortify.wall.tier0.name": "Wood wall",
  "fortify.wall.tier1.name": "Reinforced wood wall",
  "fortify.wall.tier2.name": "Stone wall",
  "fortify.wall.tier3.name": "Reinforced stone wall",
  "fortify.wall.tier4.name": "Steel wall",
  "fortify.door.category": "Doors",
  "fortify.door.tier0.name": "Wood door",
  "fortify.door.tier1.name": "Reinforced wood door",
  "fortify.door.tier2.name": "Iron door",
  "fortify.door.tier3.name": "Reinforced iron door",
  "fortify.door.tier4.name": "Steel door",
  "fortify.floor.category": "Floors",
  "fortify.floor.tier0.name": "Wood floor",
  "fortify.floor.tier1.name": "Stone floor",
  "fortify.floor.tier2.name": "Steel floor",
  "fortify.light.category": "Light turrets",
  "fortify.light.tier0.name": "Light turret",
  "fortify.light.tier1.name": "Light turret Mk II",
  "fortify.light.tier2.name": "Light turret Mk III",
  "fortify.flame.category": "Flame turrets",
  "fortify.flame.tier0.name": "Flame turret",
  "fortify.flame.tier1.name": "Flame turret Mk II",
  "fortify.flame.tier2.name": "Flame turret Mk III",
  "fortify.heavy.category": "Heavy turrets",
  "fortify.heavy.tier0.name": "Heavy turret",
  "fortify.heavy.tier1.name": "Heavy turret Mk II",
  "fortify.heavy.tier2.name": "Heavy turret Mk III",
  "fortify.gate.category": "Gates",
  "fortify.gate.tier0.name": "Wooden gate",
  "fortify.gate.tier1.name": "Iron gate",
  "fortify.gate.tier2.name": "Steel gate",
  "fortify.bars.category": "Window mesh",
  "fortify.bars.tier0.name": "Window",
  "fortify.bars.tier1.name": "Steel mesh window",
  "fortify.barricade.category": "Barricades",
  "fortify.barricade.tier0.name": "Barricade",
  "fortify.barricade.tier1.name": "Braced barricade",
  "fortify.barricade.tier2.name": "Czech hedgehog",
  "fortify.sandbag.category": "Sandbag walls",
  "fortify.sandbag.tier0.name": "Sandbag wall",
  "fortify.sandbag.tier1.name": "Double-stacked sandbags",
  "fortify.sandbag.tier2.name": "Gabion wall",
  "fortify.wire.category": "Barbed wire",
  "fortify.wire.tier0.name": "Barbed wire",
  "fortify.wire.tier1.name": "Concertina wire",
  "fortify.wire.tier2.name": "Razor wire",
  "fortify.railing.category": "Railings",
  "fortify.railing.tier0.name": "Railing",
  "fortify.railing.tier1.name": "Mesh railing",
  "fortify.railing.tier2.name": "Armoured parapet",
  "fortify.platform.category": "Platforms",
  "fortify.platform.tier0.name": "Platform",
  "fortify.platform.tier1.name": "Plated platform",
  "fortify.platform.tier2.name": "Gun emplacement",
  "fortify.pillar.category": "Pillars",
  "fortify.pillar.tier0.name": "Structural pillar",
  "fortify.pillar.tier1.name": "Concrete pillar",
  "fortify.pillar.tier2.name": "Steel column",
  "fortify.stairs.category": "Stairs",
  "fortify.stairs.tier0.name": "Stairs",
  "fortify.stairs.tier1.name": "Steel stairs",
  "fortify.stairs.tier2.name": "Retractable stairs",
  "fortify.mortar.category": "Mortars",
  "fortify.mortar.tier0.name": "Mortar",
  "fortify.mortar.tier1.name": "Mortar Mk II",
  "fortify.mortar.tier2.name": "Mortar Mk III",
  "fortify.spikes.category": "Spike traps",
  "fortify.spikes.tier0.name": "Spike trap",
  "fortify.spikes.tier1.name": "Resetting spikes",
  "fortify.spikes.tier2.name": "Steel spike bed",
  "fortify.mine.category": "Land mines",
  "fortify.mine.tier0.name": "Land mine",
  "fortify.mine.tier1.name": "Frag mine",
  "fortify.mine.tier2.name": "Bounding mine",
  "fortify.lure.category": "Decoy beacons",
  "fortify.lure.tier0.name": "Decoy beacon",
  "fortify.lure.tier1.name": "Siren beacon",
  "fortify.lure.tier2.name": "Shock beacon",
  "fortify.barrel.category": "Fuel drums",
  "fortify.barrel.tier0.name": "Fuel drum",
  "fortify.barrel.tier1.name": "Napalm drum",
  "fortify.wall.tier1.description": "Steel straps both faces and an X-brace: tougher, same timber.",
  "fortify.wall.tier2.description": "Dressed stone courses. A real wall.",
  "fortify.wall.tier3.description": "Stone girdled with iron bands and plated corners.",
  "fortify.wall.tier4.description": "Ribbed, riveted steel plate on I-beam posts. The last word.",
  "fortify.door.tier1.description": "Iron-edged, strapped and studded.",
  "fortify.door.tier2.description": "A ribbed iron plate door.",
  "fortify.door.tier3.description": "Iron, cross-braced and bolted.",
  "fortify.door.tier4.description": "A steel vault door with a wheel lock.",
  "fortify.floor.tier1.description": "Stone flags on a mortar bed.",
  "fortify.floor.tier2.description": "Riveted steel tread plate.",
  "fortify.light.tier1.description": "Twin barrels and side armour.",
  "fortify.light.tier2.description": "Triple barrels, a gun shield and a sensor eye.",
  "fortify.flame.tier1.description": "A second tank and a heat shield.",
  "fortify.flame.tier2.description": "Three tanks, a flared nozzle, blue-hot.",
  "fortify.heavy.tier1.description": "Twin cannon and armour skirts.",
  "fortify.heavy.tier2.description": "An armoured hood and a radar dish.",
  "fortify.gate.tier1.description": "Wrought iron bars with spear tips.",
  "fortify.gate.tier2.description": "A steel gate: solid below, grilled above.",
  "fortify.bars.tier1.description": "Steel mesh across the window: fire out while stopping zombie climbs and claws.",
  "fortify.barricade.tier1.description": "A welded plate and a second brace.",
  "fortify.barricade.tier2.description": "Crossed steel beams. Anything that swings at it is knocked back a step.",
  "fortify.sandbag.tier1.description": "A fifth course and a plank on top. Armours what it stands on by 40.",
  "fortify.sandbag.tier2.description": "Wire baskets packed with rock. Armours what it stands on by 60.",
  "fortify.wire.tier1.description": "A coiled spiral: 12 damage to whatever tears at it.",
  "fortify.wire.tier2.description": "Razor tape on steel pickets: 18 damage, and it leaves them slowed.",
  "fortify.railing.tier1.description": "Welded mesh panels.",
  "fortify.railing.tier2.description": "Steel plate to the waist with a firing ledge. Acid and spit no longer reach you through it.",
  "fortify.platform.tier1.description": "A steel skirt round the rim.",
  "fortify.platform.tier2.description": "Sandbagged rim and an ammo locker: the gun on it fires 10% faster.",
  "fortify.pillar.tier1.description": "Poured concrete: braced by a wall within four squares.",
  "fortify.pillar.tier2.description": "A steel column: braced within five squares.",
  "fortify.stairs.tier1.description": "Checker-plate treads on steel stringers.",
  "fortify.stairs.tier2.description": "Steel, and it folds: press {interact} to pull the flight up behind you.",
  "fortify.mortar.tier1.description": "Sandbagged base and a second crate: 25% more blast, reloads 20% faster.",
  "fortify.mortar.tier2.description": "A long tube on a turntable: 50% more blast, reloads 35% faster.",
  "fortify.spikes.tier1.description": "Springs three times, re-arming 20 seconds after each.",
  "fortify.spikes.tier2.description": "A steel bed that never wears out: re-arms in 10 seconds, 200 damage, and leaves them bleeding.",
  "fortify.mine.tier1.description": "Fragmentation casing: 110 damage over a wider blast.",
  "fortify.mine.tier2.description": "Bounding charge: it jumps waist-high first. 150 damage.",
  "fortify.lure.tier1.description": "A siren: calls for 35 seconds, and from half again as far.",
  "fortify.lure.tier2.description": "A shock beacon: 45 seconds, and it zaps anything within 2 m.",
  "fortify.barrel.tier1.description": "Napalm: the blast leaves a burning pool that sets them alight.",

  // build
  "build.category.structure": "Structure",
  "build.category.defenses": "Defenses",
  "build.category.turrets": "Turrets",
  "build.reason.cannotBuild": "Cannot be built",
  "build.reason.runRequired": "Needs a run of wire, a barricade or a railing",
  "build.reason.wallRequired": "Needs a plain wall to cut into",
  "build.reason.pillarTaken": "There is already a pillar there",
  "build.reason.pillarTurretOnly": "A pillar only carries a turret",
  "build.reason.pillarTurretTaken": "That pillar already has a turret",
  "build.reason.nothingUnder": "Nothing under it",
  "build.reason.builtOver": "Built over",
  "build.reason.tooFar": "Too far",
  "build.reason.cellTaken": "Cell taken",
  "build.reason.edgeTaken": "That edge already has one",
  "build.reason.wallTaken": "That wall already has something on it",
  "build.reason.noRoom": "No room",
  "build.reason.openGround": "Needs open ground",
  "build.reason.support": "Needs a {supports} under it",
  "build.reason.occupied": "Something already standing there",
  "build.reason.belowWallTaken": "Something is on top of the wall below",
  "build.reason.standingOn": "Something is standing on the {name}",
  "build.reason.cannotStandOn": "Will not stand on {name}",
  "build.reason.unsupported": "Too far from anything to hold it up",
  "build.reason.stairsCell": "The stairs take the whole cell",
  "build.reason.cannotSitOn": "Will not sit on {name}",
  "build.reason.maxHeight": "Stacked as high as it goes",
  "build.reason.landmark": "{name} in the way — shoot it, knife it or dig it out",
  "build.reason.obstructed": "Something in the way",
  "build.reason.offMap": "Off the map",
  "build.reason.cave": "Too close to the cave",
  "build.reason.water": "In the water",
  "build.reason.nearWater": "Too close to the water",
  "build.reason.cabin": "That is the HQ",
  "build.reason.rough": "Ground too rough",
  "build.reason.player": "You are standing there",
  "build.reason.funds": "Not enough Cash",
  "build.reason.locked": "Blueprint required",
  "build.obstacle.fence": "a fence",
  "build.obstacle.campsite": "a camp",
  "build.obstacle.camp": "a camp",
  "build.obstacle.shed": "a shed",
  "build.obstacle.sign": "a sign",
  "build.obstacle.barrel": "a fuel drum",
  "build.obstacle.graveyard": "the graveyard",
  "build.obstacle.cabin": "a cabin",
  "build.message.noBlueprint": "{name} — NO BLUEPRINT",
  "build.message.buyBlueprint": "Buy the plans at the supply terminal ({price} Cash)",
  "build.message.upgradeControls": "{fire} click one · drag for a box · {rotate} door / window / wall",
  "build.message.scrapControls": "{scrap} hold + release to scrap · {buildWheel} exit build mode",
  "build.message.placeControls": "{rotate} rotate ({bearing}) · {fire} place · {repair} repair · {scrap} hold + release to scrap · hold {scrap} + drag for a box · {buildWheel} exit build mode",
  "build.message.dragControls": "{rotate} rotate ({bearing}) · {fire} place · drag for a line · {repair} repair · {scrap} hold + release to scrap · hold {scrap} + drag for a box · {buildWheel} exit build mode",
  "build.message.price": "{name} — {cost} Cash",
  "build.message.nothing": "NOTHING THERE",
  "build.message.scrapPoint": "Point at the piece you want to scrap",
  "build.message.cannotBuild": "CAN'T BUILD THERE",
  "build.message.shovel": "SHOVEL",
  "build.message.shovelRemaining": "Keep at it — {hp} left",
  "build.message.rubble": "RUBBLE CLEARED",
  "build.message.burrow": "BURROW FILLED IN",
  "build.message.insufficient": "NOT ENOUGH CASH",
  "build.message.cost": "{name} costs {cost} Cash",
  "build.message.stairsUp": "STAIRS UP",
  "build.message.stairsDown": "STAIRS DOWN",
  "build.message.stairsSafe": "Nothing is climbing those",
  "build.message.cannotUpgrade": "CAN'T UPGRADE",
  "build.message.upgradePoint": "Point at something you built",
  "build.message.noUpgrades": "{name} has no upgrades",
  "build.message.maxUpgrade": "{name} — fully upgraded",
  "build.message.requiresUpgrade": "Buy the {name} blueprint at the supply terminal",
  "build.message.upgraded": "UPGRADED",
  "build.message.nothingUpgraded": "NOTHING UPGRADED",
  "build.message.upgradeEmpty": "Nothing in the box to upgrade",
  "build.message.boxUpgradeEmpty": "Nothing in the box can be upgraded",
  "build.message.boxUpgrade": {"one":"Release to upgrade {count} of {total} piece — {cost} Cash","other":"Release to upgrade {count} of {total} pieces — {cost} Cash"},
  "build.message.boxScrap": {"one":"Release the mouse to scrap {count} piece — +{refund} Cash","other":"Release the mouse to scrap {count} pieces — +{refund} Cash"},
  "build.message.upgradeReceipt": {"one":"{count} piece — {cost} Cash","other":"{count} pieces — {cost} Cash"},
  "build.message.outOfCash": "OUT OF CASH",
  "build.message.partial": "Built {built} of {total} — {name} costs {cost} Cash",
  "build.message.built": "BUILT {built} OF {total}",
  "build.message.scrapBox": "Drag over the pieces you want to scrap",
  "build.message.scrapped": "SCRAPPED {count}",
  "build.message.refund": "+{amount} Cash",
  "build.message.scrapHint": "{scrap} scraps: {name} — +{refund} Cash",
  "build.message.scrapSupported": "{scrap} scraps: {name} +{count} on it — +{refund} Cash",
  "build.message.upgradeHint": "{name} — {cost} Cash · {rotate}: {part}",
  "build.message.that": "That",

  "build.obstacle.tree": "a tree",
  "build.obstacle.stump": "a tree stump",
  "build.obstacle.rock": "a rock",
  "build.obstacle.hq": "the HQ",
  "build.reason.natural": "{name} in the way",
  "mortar.noRoom": "NO ROOM BEHIND THE TUBE",
  "mortar.noRoomEdge": "You would step off the edge — turn the tube or set it further in",
  "mortar.noRoomBlocked": "Something you built is where you would kneel",
  "build.message.stairsOccupied": "NOT WHILE YOU ARE ON THEM",
  "build.message.stairsStepOff": "Step off the stairs, then raise them",

  // mortar
  "mortar.manned": "MORTAR MANNED",
  "mortar.controls": "{fire} fire at the reticle · {interact} dismount · {carry} shoulder it · {shells} shells",
  "mortar.overhead": "BLOCKED OVERHEAD",
  "mortar.blocked": "The shell would hit your own {name} — move the tube into the open",
  "mortar.noShells": "NO MORTAR SHELLS",
  "mortar.buyShells": "Sold under Ammo at the supply terminal",
  "mortar.carrying": "Carrying the mortar — {fire} / {interact} to set it down",
  "mortar.shouldered": "MORTAR SHOULDERED",
  "mortar.carryHelp": "No weapons while you carry it. {fire} or {interact} sets it down.",

  // wheel
  "wheel.gas": "{seconds}s gas",
  "wheel.ammo": "{loaded} + {reserve}",
  "wheel.tier": "price per tier",
  "wheel.plans": "plans {price} Cash",
  "wheel.weaponLocked": "Not bought · supply terminal {price} Cash",
  "wheel.buildLocked": "No blueprint · supply terminal {price} Cash",

  // death
  "death.lightning.name": "Lightning",
  "death.lightning.description": "Struck down by lightning",
  "death.rabbit.name": "The rabbit",
  "death.rabbit.description": "Lost his head to a rabbit",
  "pickup.insulatedBoots": "Insulated boots",
  "pickup.insulatedBootsSub": "Storm protection. Yours for this run.",
  "lightning.saved": "Grounded",
  "lightning.savedSub": "The boots took the strike. Keep moving.",
  "pickup.holyGrenade": "Choir grenade",
  "pickup.holyGrenadeSub": "When the rabbit wakes, get close and press {grenade}.",
  "holy.pin": "Pin pulled",
  "holy.pinSub": "Let the choir finish.",
  "rabbit.killed": "The rabbit is dead",
  "rabbit.killedSub": "Small mercy. Loud delivery.",
  "badges.choirPractice.name": "Choir practice",
  "badges.choirPractice.description": "Kill the rabbit with the Choir grenade.",
  "death.shambler.name": "Shambler",
  "death.shambler.description": "Torn apart by a shambler.",
  "death.feral.name": "Feral",
  "death.feral.description": "Run down by a feral.",
  "death.leaper.name": "Leaper",
  "death.leaper.description": "Flattened under a leaper.",
  "death.spider.name": "Spider",
  "death.spider.description": "Wrapped and eaten by a spider.",
  "death.drowned.name": "Drowned",
  "death.drowned.description": "Pulled apart by the drowned.",
  "death.military.name": "Military",
  "death.military.description": "Outfought by a dead soldier.",
  "death.brute.name": "Brute",
  "death.brute.description": "Beaten down by a brute.",
  "death.spitter.name": "Spitter",
  "death.spitter.description": "Smothered by a spitter.",
  "death.screamer.name": "Screamer",
  "death.screamer.description": "Silenced by a screamer.",
  "death.bomber.name": "Bomber",
  "death.bomber.description": "Caught a bomber’s blast point-blank.",
  "death.demon.name": "Demon",
  "death.demon.description": "Gored on a demon’s horns.",
  "death.colossus.name": "Colossus",
  "death.colossus.description": "Crushed under the colossus.",
  "death.blast.name": "Explosion",
  "death.blast.description": "Blown apart by an explosion.",
  "death.fire.name": "Fire",
  "death.fire.description": "Burned to death.",
  "death.acid.name": "Acid",
  "death.acid.description": "Dissolved in spider acid.",
  "death.tree.name": "Falling tree",
  "death.tree.description": "Crushed by a falling tree.",
  "death.towerfall.name": "Tower collapse",
  "death.towerfall.description": "Rode the watchtower down.",
  "death.bird.name": "Birds",
  "death.bird.description": "Pecked to death by carrion birds.",
  "death.caveguard.name": "Cave Guardian",
  "death.caveguard.description": "Dragged into the dark.",
  "death.tentacles.name": "Underwater Pit",
  "death.tentacles.description": "Something in the Underwater Pit was hungry.",

  // enemy
  "enemy.shambler.name": "Shambler",
  "enemy.feral.name": "Feral",
  "enemy.leaper.name": "Leaper",
  "enemy.spider.name": "Spider",
  "enemy.drowned.name": "Drowned",
  "enemy.military.name": "Military",
  "enemy.brute.name": "Brute",
  "enemy.spitter.name": "Spitter",
  "enemy.screamer.name": "Screamer",
  "enemy.bomber.name": "Bomber",
  "enemy.demon.name": "Demon",
  "enemy.colossus.name": "Colossus",
  "enemy.guardian.name": "Guardian",
  "enemy.caveguard.name": "Cave Guardian",

  // streak
  "streak.rampage": "RAMPAGE",
  "streak.rampageHelp": "5 streak · x1.25 skull value · light step · kills heal",
  "streak.massacre": "MASSACRE",
  "streak.massacreHelp": "10 streak · x1.5 skull value · steady hands",
  "streak.unstoppable": "UNSTOPPABLE",
  "streak.unstoppableHelp": "20 streak · x2 skull value · rounds on the house",
  "streak.godlike": "GODLIKE",
  "streak.godlikeHelp": "30 streak · x2.5 skull value · a quarter of all damage shrugged off",
  "streak.lost": "STREAK LOST — {count}",
  "streak.thickSkin": "thick skin",
  "streak.freeRounds": "free rounds",
  "streak.quickHands": "steady hands",
  "streak.fastFeet": "light step",

  // wave
  "wave.cleared": "DAY {day} CLEARED",
  "wave.prep": "Use the prep — repair, build, resupply, turn in skulls",
  "wave.prepBest": "Use the prep — repair, build, resupply, turn in skulls · best streak {streak}",
  "wave.bloodMoon": "EMBER NIGHT",
  "wave.bloodMoonHelp": "Day {day} — the horde runs faster, kills worth x1.5 skull value",
  "wave.inbound": "DAY {day} — HORDE INBOUND",
  "wave.surround": "They're coming from every direction",
  "wave.from": "From {sources}",
  "wave.compassSource": "the {bearing}",
  "wave.boss": "{approach} — something enormous walks with them",
  "wave.colossusDown": "COLOSSUS DOWN",
  "wave.colossusReward": "{value} skull value — turn the skulls in at HQ",

  // prep
  "prep.ready": "Prep — ready when you are",
  "prep.start": "Start the wave at the HQ panel ({interact})",
  "prep.day": "Prep — day {day} · {count} coming",
  "prep.alarmSounding": "Alarm sounding",
  "prep.inbound": "INBOUND",
  "prep.readyStatus": "READY",
  "prep.summary": "Prep {done}/{total}",
  "prep.bank": "Bank your skulls",
  "prep.ammo": "Restock {calibre}",
  "prep.fortify": "Fortify the {bearing} approach",
  "prep.repair": "Repair the damaged {buildName}",
  "prep.alarm": "Start the wave at the HQ panel",
  "prep.unavailable": "No longer available",
  "prep.complete": "Complete",

  // supply
  "supply.inbound": "SUPPLY DROP INBOUND",
  "supply.breatherInbound": "BREATHER CRATE INBOUND",
  "supply.bearingShort": "coming down {bearing} of you",
  "supply.landed": "Supply crate landed",
  "supply.expired": "Supply crate lost",
  "supply.direction": "Plane overhead — crate coming down {bearing} of you",
  "supply.title": "SUPPLY DROP",
  "supply.ammoRestocked": "Ammo restocked",
  "supply.ammoFull": "Ammo full",
  "supply.medpensFull": "MedPens full",
  "supply.medpens": {"one":"+{count} MedPen","other":"+{count} MedPens"},
  "supply.grenades": {"one":"+{count} grenade","other":"+{count} grenades"},
  "supply.blueprintFound": "Turret blueprint found",
  "supply.full": "Supplies full",
  "supply.receipt": "{ammoStatus} · {medpenStatus}",
  "supply.noMedpens": "NO MEDPENS",
  "supply.medpenHelp": "Buy them at the supply terminal, or find one in a supply drop",
  "supply.medpen": "MEDPEN",
  "supply.medpenPickedUp": "+1 MedPen ({count}/{capacity}) · {heal} to use",
  "supply.medpenUsed": "Pockets full — used on the spot, +{percent}% health",

  // world
  "world.message.towerFall": "THE TOWER COLLAPSED!",
  "world.message.towerFallHelp": "You should have climbed down sooner…",
  "world.message.towerCollapsed": "The watchtower has collapsed",
  "world.message.nest": "NEST DESTROYED",
  "world.message.nestHelp": "A bird is furious",
  "world.message.timber": "TIMBER",
  "world.message.timberHelp": "Watch where they fall",
  "world.message.webbed": "WEBBED",
  "world.message.webbedHelp": "Slowed — shake it off",

  // gameOver
  "gameOver.win": "Evacuated",
  "gameOver.title": "Game over",
  "gameOver.winHelp": "Ridgeline has you.",
  "gameOver.retry": "Try again?",
  "gameOver.again": "Play again",
  "gameOver.overrun": "You were overrun…",
  "gameOver.houseLost": "The house was destroyed!",
  "records.best": "Best:",
  "records.day": "Night {count}",
  "records.kills": "{count} kills",
  "records.streak": "streak {count}",
  "records.new": "NEW",
  "records.hotExtraction": "Hot extraction.",
  "gameOver.skulls": "Skulls banked",
  "gameOver.day": "Day",
  "gameOver.nightsSurvived": "Nights survived",
  "gameOver.survivorsAboard": "Survivors aboard: {count}",
  "gameOver.kills": "Kills",
  "gameOver.headshots": "Headshots",
  "gameOver.bestStreak": "Best streak",
  "gameOver.deathLog": "Ways to die · {seen} / {total} found",
  "gameOver.deathLogNew": "Ways to die · {seen} / {total} found · NEW",
  "gameOver.unknownDeath": "Undiscovered way to die",
  "gameOver.cave": "Dragged into {place}.",
  "gameOver.rest": "Rest easy, {name}",
  "gameOver.unknownMarine": "Unknown Gravewalker",

  // extraction (GB-114)
  "extraction.boardPrompt": "Hold {interact} · Board Heron",
  "extraction.boarding": "Boarding · {pct}%",
  "extraction.win": "You're aboard. Heron is taking you home.",
  "extraction.winHot": "You're aboard. The dead are still on the dock.",

  // survivor (GB-90, GP-69)
  "survivor.rescue": "{interact} · Bring them to safety",
  "survivor.board.ranger": "Someone lit a fire at the ranger camp.",
  "survivor.board.hikers": "Someone lit a fire at the hikers' camp.",
  "survivor.board.trapper": "Someone lit a fire at the trapper's camp.",

  // cinematic
  "cinematic.skip": "{jump} — skip",
  "cinematic.fell": "FELL ON DAY {day}",
  "cinematic.kills": {"one":"{count} KILL","other":"{count} KILLS"},
  "cinematic.noPlot": "No plot left for {name}",
  "cinematic.lake": "The lake keeps them now",

  // dawn
  "dawn.title": "Night {day} Complete",
  "dawn.kills": "Zombies killed",
  "dawn.skulls": "Skulls picked up",
  "dawn.best": "Best streak this night",
  "dawn.dareEarned": "Lights out earned {skulls} extra skull value.",
  "dawn.newStock": "New at the supply terminal: {weapons}.",
  "dawn.morning": "Proceed to Morning",
  "dawn.nextNight": "Next Night",
  "dawn.tipBank": "Bank your skulls at the HQ window, resupply, then sound the next alarm at the briefing panel.",
  "dawn.tipResupply": "Restock at the supply terminal, then sound the next alarm at the briefing panel.",
  "wavePreview.atHQ": "Visit the HQ panel to sound the alarm.",
  "wavePreview.ground": "Treeline · ground rise",

  // coach
  "poi.cleared": "{name} · Cleared",
  "coach.poi": "Shamblers at {poi}: go and clear them.",
  "coach.poiHelp": "Press {map} to find it on your map, then collect the skulls they drop.",
  "coach.build": "Press {buildWheel} to build.",
  "coach.pair": "Press {akimbo} for two guns.",
  "coach.medpen": "Press {heal} to jab a MedPen.",
  "coach.caveWarning": "Something in that cave woke up. Don't shoot into the caves again.",
  "coach.pitWarning": "The water over the pit is moving. Turn back.",
  "coach.pickup": "Skulls collected.",
  "economy.equipmentPrices": "Equipment +{percent}% this night. Ammo, supplies, builds and chainsaw prices stay fixed.",
  "economy.dayOne": "Day 1: each Shambler is worth 1 skull value before bonuses. Bank skulls at the HQ window: 1 skull value = 1 Cash.",
  "coach.return": "Bring them to the HQ window to bank Cash.",
  "coach.bank": "Press {interact} to bank your skulls.",
  "coach.purchase": "Purchase ready.",
  "coach.loop": "Collect skulls. Bank Cash. Resupply.",

  // wavePreview
  "wavePreview.title": "Day {day} briefing",
  "intake.title": "SAMPLE INTAKE",
  "intake.unit": "PGB / BONE RESEARCH",
  "intake.exchange": "SKULLS → CASH",
  "intake.ready": "AWAITING SAMPLES",
  "intake.processing": "PROCESSING SAMPLES",
  "intake.paid": "PAYMENT CREDITED",
  "intake.value": "{value} SKULL VALUE",
  "intake.cash": "+{value} CASH",
  "intake.received": { one: "{count} SKULL RECEIVED", other: "{count} SKULLS RECEIVED" },
  "intake.banked": { one: "{count} SKULL BANKED", other: "{count} SKULLS BANKED" },
  "intake.instruction": "DEPOSIT AT THE WINDOW",
  "intake.specimen": "SPECIMEN / {number}",
  "alarm.title": "Alarm control",
  "alarm.station": "FOB Threshold / Perimeter defence",
  "alarm.report": "Threat report",
  "alarm.fieldwork": "Fieldwork",
  "alarm.relay": "Relay",
  "alarm.ready": "Ready to sound",
  "alarm.active": "Alarm sounding",
  "alarm.locked": "Control unavailable",
  "alarm.inProgress": "Wave in progress",
  "alarm.remote": "Return to the HQ panel",
  "alarm.consequence": "The alarm draws the dead to HQ. Finish your preparations first.",
  "alarm.fieldworkEmpty": "No field assignments posted today.",
  "alarm.relaySilent": "Relay silent. Repair the relay to reach Ridgeline.",
  "alarm.relayQuiet": "No new transmissions.",
  "alarm.modelTitle": "ALARM",
  "alarm.modelUnit": "PGB / THRESHOLD",
  "alarm.modelScreen": "PERIMETER",
  "alarm.modelButton": "SOUND ALARM",
  "wavePreview.alarm": "Sound alarm",
  "wavePreview.callBoat": "Call Heron",
  "wavePreview.relayDown": "Relay down — repair the radio mast to call Heron.",
  "bounty.title": "Day bounties",
  "bounty.wanderer": "A colossus is walking the {direction} trail",
  "bounty.wandererActive": "One colossus roaming",
  "bounty.trail.north": "north",
  "bounty.trail.south": "south",
  "bounty.trail.east": "east",
  "bounty.trail.west": "west",
  "bounty.guards": {"one":"{count} guard remaining","other":"{count} guards remaining"},
  "bounty.reward": "{value} skull value",
  "bounty.deadline": "Before the alarm",
  "bounty.collected": "Collected",
  "bounty.empty": "No open bounties posted.",
  "bounty.bank": "Rewards go into your skull bag. Bank them at the HQ window.",
  "bounty.mapLegend": "Bounty sites are now marked with blue targets on your minimap.",
  "bounty.done": "Bounty: {name} +{value} skull value",
  "scouting.title": "Tonight · Night {day}",
  "scouting.caves": "Caves: {names}",
  "scouting.noCaves": "No cave approach confirmed",
  "scouting.pushes": {"one":"{count} push","other":"{count} pushes"},
  "scouting.rest": "Rest night · lighter mix, still a fight",
  "scouting.warning.fog": "Fog Night",
  "scouting.warning.siege": "The siege · they'll go for your walls",
  "scouting.mapLegend": "Tonight’s caves are marked on the minimap. Edge arrows point to caves beyond its range.",
  "scouting.unconfirmed": "Tactics unconfirmed",
  "scouting.counters": "Counters in tonight’s attack",
  "counter.brute": "Plates stop bullets. Blow it up or burn it.",
  "counter.shambler": "Save your ammo: the knife does the job.",
  "counter.feral": "Too quick for grenades. Let it close and use the shotgun.",
  "counter.leaper": "Shoot it before it lands. Don't try to knife it.",
  "counter.spider": "Its shell turns bullets. Burn it off the wall.",
  "counter.drowned": "Too wet to burn. The shotgun tears it apart.",
  "counter.military": "Vests stop bullets. They move together: throw a grenade.",
  "counter.spitter": "Shoot it while it creeps in. Don't get close.",
  "counter.screamer": "Kill the screamer first, with a rifle. It stays out of shotgun range.",
  "counter.bomber": "Burn it or shoot it far away. Never let it reach you.",
  "counter.demon": "Fire does nothing. Pour rifle fire into it.",
  "counter.colossus": "Bullets barely scratch it. Mortar and launcher.",
  "counter.guardian": "It lives in the dark. Fire drives it back.",
  "counter.firstSeen": "New threat: {enemy}",
  "scouting.trick.clawUp": "Shamblers from cave and treeline · watch for ground risers",
  "scouting.trick.runners": "Runner packs · break them up before they close",
  "scouting.trick.lake": "Drowned and leapers · keep clear of the water",
  "scouting.trick.twoFronts": "Soldiers and brutes on two fronts · plates stop bullets; fire and blasts don't",
  "scouting.trick.nest": "Spiders, then a colossus · clear the wall climbers before the last push",
  "scouting.trick.guardian": "Marrow guardian and spitters · pick off the spitters before they line up",
  "scouting.trick.woods": "Treeline risers and bombers · shoot a bomber inside its pack for a chain",
  "scouting.trick.bomberPack": "Bomber pack and screamers · kill the screamers first; chain the bombers",
  "scouting.trick.runnersTwoCaves": "Runners from two caves · keep moving between packs",
  "scouting.trick.bruteNight": "Brute packs and a colossus · plates stop bullets; fire and blasts don't",
  "scouting.trick.surround": "Every cave and the first demons · hold an exit from the ring",
  "scouting.trick.guardianEmber": "Ember guardian and demons · keep the Marrow cave in sight",
  "scouting.trick.artillery": "Spitters behind soldiers · close on the spitters after the front line breaks",
  "scouting.trick.lakeSurge": "Lake surge and treeline risers · watch both water and ground",
  "scouting.trick.fogNight": "Lake surge in dense fog · keep a short route back to cover",
  "scouting.trick.nestColossus": "Spider packs, screamers, colossus · kill screamers first",
  "scouting.trick.demonNight": "Ember demon packs · save heavy fire for the pack fronts",
  "scouting.trick.surroundFast": "Fast attackers from every cave · keep an escape lane open",
  "scouting.trick.siege": "Brutes and soldiers will smash your walls · reinforce the weakest side",
  "scouting.trick.gauntlet": "Three caves and treeline · reload in the short breather before the surge",
  "scouting.trick.lastStand": "Colossus, caves, treeline and lake · save blasts for the colossus",
  "wavePreview.locked": "Field Intel reveals exact counts and approaches.",
  "wavePreview.largest": "Largest approach: {source} · {bearing}",
  "wavePreview.mainThreat": "Main threat: {enemy}",
  "wavePreview.multiple": "Multiple approaches",
  "wavePreview.empty": "No attack scheduled",
  "wavePreview.unavailable": "Briefing unavailable",
  "wavePreview.row": "{enemy}: {count}",
  "wavePreview.sourceTotal": "{source}: {count}",
  "wavePreview.total": "Total: {count}",
  "wavePreview.inProgress": "Wave under way",
  "wavePreview.upgrade": "Field Intel",
  "wavePreview.upgradeDescription": "See every enemy type, count and approach at the HQ panel.",
  "wavePreview.prompt": "{interact} — HQ briefing",
  "wavePreview.unknownSource": "Unconfirmed approach",
  "wavePreview.unknownBearing": "Bearing unconfirmed",
  "wavePreview.lake": "Lake",
  "wavePreview.perimeter": "Outer perimeter",
  "wavePreview.colossus": "Colossus detected",
  "wavePreview.guardianNight": "Guardian night",
  "wavePreview.guardianFromCave": "From {source}",
  "wavePreview.guardianUrgent": "A Guardian is coming from {source}.",
  "wavePreview.prep": "Preparation",
  "wavePreview.hudBasic": "Wave Day {day} · Prep · HQ briefing",
  "wavePreview.hudFull": "Wave Day {day} · Prep · Next: {count} · HQ briefing",
  "wavePreview.prepDay": "Prep — day {day}",

  // Guardian first-blood reward; announce only the confirmed economy result.
  "reward.guardianFirstBlood": "First Guardian defeated",
  "reward.guardianBlueprint": "Mortar blueprint unlocked",
  "reward.guardianSkulls": "+80 skull value — bank it at the HQ window",

  // objectives
  "objectives.track": "Track",
  "objectives.untrack": "Stop tracking",
  "objectives.interact": "{interact} — {action}",
  "objectives.repairing": "Restoring signal…",
  "objectives.interrupted": "Repair interrupted",
  "objectives.claim": "Take supplies",
  "objectives.choosePack": "Choose supplies",
  "objectives.holdRepair": "Hold {interact} for 6 seconds to restore the radio",
  "objectives.mapLegend": "Gold markers: supplies · select one to track",
  "objectives.packChoice": "{calibre} · {pack}",
  "objectives.full": "Inventory full — supplies remain",
  "objectives.claimed": "Supplies collected",
  "objectives.unavailable": "Site unavailable",
  "objectives.distance": "{distance} m",
  "objectives.reward": "Reward: {reward}",
  "objectives.remaining": "Supplies remaining: {reward}",
  "objectives.progress": "{objective} · {distance} m",
  "objectives.radioRepair": "Restore the radio mast",
  "objectives.medicalConvoy": "Recover medical supplies",
  "objectives.rangerCache": "Search the ranger cache",
  "objectives.hikersCache": "Recover the hikers' first-aid kit",
  "objectives.trapperCache": "Recover the trapper's supplies",
  "objectives.fuelDepot": "Recover the depot fuel",
  "objectives.wreckSalvage": "Salvage the utility truck",

  // dev
  "dev.consoleLabel": "Command",
  "dev.bigtex": "BIGTEX SHOOTER",
  "dev.unlocked": "Everything unlocked · Unlimited Cash",
  "dev.cashOff": "CASH CHEAT OFF",
  "dev.godmode": "GODMODE",
  "dev.invincible": "Invincible",
  "dev.godmodeOff": "GODMODE OFF",
  "dev.nodead": "NODEAD",
  "dev.noWaves": "Zombies and waves disabled",
  "dev.godead": "GODEAD",
  "dev.nodeadOff": "NODEAD OFF",
  "dev.wavesBack": "Zombies and waves are back",
  "dev.night": "NIGHT OPS",
  "dev.nightHelp": "Night has fallen",
  "dev.shower": "SHOWER",
  "dev.showerHelp": "Storm rolling in",
  "dev.unknown": "UNKNOWN COMMAND",
  "dev.benchmark": "BENCHMARK",
  "dev.benchmarkHelp": "Recording 25 seconds — stand and watch",
  "dev.benchmarkResult": "avg {average} fps · 5% low {low5} · 1% low {low1} · worst {worst}ms · {draws} draws · {triangles}k tris · {pieces} pieces · {alive} alive",
  "dev.swarm": "SWARM",
  "dev.swarmHelp": "{count} zombies closing in from 50m",
  "dev.basebuild": "BASEBUILD",
  "dev.basebuildHelp": "{count} pieces put up",
  "dev.reset": "RESET",
  "dev.resetHelp": "Back at insertion",
  "dev.badge.music": "MUSIC",
  "dev.badge.bugs": "BUGS",
  "dev.badge.wild": "WILD",
  "dev.badge.night": "NIGHT",
  "dev.badge.horde": "HORDE",
  "dev.badge.gore": "GORE",
  "dev.badge.ball": "BALL",
  "dev.badge.poi": "POI",
  "dev.badge.solid": "SOLID",

  // performance
  "performance.gpu": "gpu   {gpu}",
  "performance.cpu": "cpu   {cpu}",
  "performance.threads": "{count} threads",
  "performance.memory": "{memory}GB",
  "performance.resolution": "res   {width}x{height} @{ratio}x",
  "performance.renderer": "rend  {backend}",
  "performance.fps": "fps   {fps}",
  "performance.worst": "worst {ms}ms",
  "performance.hitches": "hitch {count}",
  "performance.draws": "draws {count}",
  "performance.triangles": "tris  {count}k",
  "performance.zombies": "zombs {count}",
  "performance.webgl": "WebGL2 fallback",
  "performance.unknown": "unknown",

  // tips
  "tips.movement.title": "Movement & looking",
  "tips.movement.move": "{move} / arrows — move: {forward} is up the screen, whichever way you're aiming · {run} — run",
  "tips.movement.jump": "{jump} — jump · {dodge} — dodge roll (can't be hurt mid-roll)",
  "tips.movement.crouch": "{crouch} — crouch: slower, but tighter groups and a lower silhouette",
  "tips.movement.aim": "Mouse — aim anywhere around you; the Gravewalker turns to face the reticle while the camera holds still, so shots land where it sits",
  "tips.movement.zoom": "Scroll wheel — zoom the camera in / out (scoped, it dials the magnification)",
  "tips.movement.camera": "Hold the middle mouse button and drag — rotate the camera",
  "tips.movement.tilt": "The tilt looks after itself: the view lifts to look up a hill ahead, drops into a dip, and rises over ground behind you instead of crowding the Gravewalker",
  "tips.movement.followCursor": "The camera slides toward the cursor once you point past the middle of the screen, so you see more of what you're aiming at",
  "tips.movement.cameraSettings": "{pause} > Settings > Camera turns both off (with auto tilt off, middle-drag up / down tilts by hand again). Look sensitivity is there too",
  "tips.combat.title": "Combat",
  "tips.combat.fire": "{fire} — fire / hold for the chainsaw and flamethrower · {reload} — reload",
  "tips.combat.scope": "{aim} — zoom. On the sniper it raises a real scope on whatever the reticle is on; the mouse then moves the scope directly (push to the screen edge to swing further). Wheel or middle click — 2X / 4X / 6X",
  "tips.combat.grenade": "{grenade} — grenade · {melee} — knife (or the machete, once bought)",
  "tips.combat.medpen": "{heal} — jab a MedPen (heals 60%). Health only regenerates back to 40% on its own",
  "tips.combat.weapons": "Hold {weaponWheel} — weapon wheel: time slows, point at a gun, let go to draw it · tap {weaponWheel} to step to the next one",
  "tips.interaction.title": "Action key ({interact})",
  "tips.interaction.kiosk": "{interact} at the supply terminal (the supply hatch in the east wall of the HQ, yellow square on the map) — weapons, ammo, gear, upgrades, blueprints. Open any time; time stops while you shop. {interact} or {pause} closes it",
  "tips.interaction.bank": "{interact} at the HQ sample window (front of the HQ) — turn in collected skulls for Cash. Kill → pick up glowing skulls → turn in → spend at the supply terminal",
  "tips.interaction.alarm": "{interact} at the HQ start panel (front wall) — sound the alarm to start the next wave. Prep lasts until you call it",
  "tips.interaction.mortar": "{interact} at a mortar — man it: {fire} lobs a shell at the reticle (dotted arc), {interact} leaves it, {carry} shoulders it to carry it (no weapons while carrying; {fire} or {interact} sets it down)",
  "tips.building.title": "Building",
  "tips.building.wheel": "Hold {buildWheel} — build wheel (paged): Structure · Defenses · Turrets. Point at a build, let go to pick it · tap {buildWheel} to enter / leave build mode · {fire} place",
  "tips.building.blueprints": "Blueprints unlock builds in the {buildWheel} menu (supply terminal → Blueprints). Barricade, shovel, and Upgrade start unlocked; placing most pieces still costs Cash. Fortify blueprints upgrade walls, doors, turrets, and more",
  "tips.building.repair": "{rotate} — rotate the build, or choose the part to upgrade · {repair} — repair · {scrap} — scrap. In build mode these target your preview; hold {scrap} to preview a scrap box",
  "tips.building.trees": "Fell a tree onto approaching zombies to crush them. Stand clear as it falls.",
  "tips.building.drums": "Fuel drums: place one, shoot it when the horde is beside it, stand well back — they chain",
  "tips.waves.title": "Waves & enemies",
  "tips.waves.prep": "Prep — no countdown: start the wave at the HQ panel ({interact}). {confirm} only reminds you",
  "tips.waves.caves": "Waves pour out of the six cave mouths at the map rim — the red arcs on the map point at the mouths in use. You can't build within 25m of a mouth, and do NOT walk into one: something lives in there, and it does not lose",
  "tips.waves.streak": "Chain kills fast for a streak: 5 / 10 / 20 / 30 raise skull value AND grant powers while it holds — light step, steady hands, free rounds, thick skin. From 5, your own kills also heal 1 HP (2 from 20), up to 70% health. Lose the streak, lose the powers",
  "tips.waves.minimap": "Minimap: the 50 m around you, turned so up is always the way the camera faces (W). Zombies are the flashing red dots; red arcs on the rim are where the wave comes from",
  "tips.waves.map": "{map} — full map of the whole area, north-up",
  "tips.waves.bombers": "Bombers (glowing gut) sprint and detonate — shoot them before they reach your line, ideally next to other zombies",
  "tips.waves.leapers": "Leapers run on all fours and jump 5–14m onto you — sidestep the landing. Spiders — crawling zombies with six limbs — hang back and web you (slowed): kill them first",
  "tips.waves.demons": "Demons (red, horned, from day 6 — more on Ember Night) stop and roar before they charge in a straight line: sidestep or roll when you hear it. Fire barely hurts them; bullets do",
  "tips.waves.spitters": "Spitters (bloated, olive) don't spit — they walk in and then crawl the last 15m. Easy targets, but they keep coming",
  "tips.waves.blade": "Most of a wave is plain shamblers, and there are a lot of them. Your blade costs nothing: {melee} one-shots shamblers, ferals, leapers and spitters through a near half-circle sweep",
  "tips.waves.drowned": "The drowned only ever come up out of the Underwater Pit in the lake bed and are fast in the water — don't fight near the banks, and never swim over the pit itself: the thing that owns it takes swimmers whole",
  "tips.waves.flamer": "Flamethrower: the stream sticks to what it hits and fizzles in water; burning zombies light whatever they touch, and the ground keeps burning — including under you",
  "tips.economy.title": "Cash & skulls",
  "tips.economy.skulls": "Risen skulls carry a rune mark. Collect these samples — the HUD Skulls line shows how many you carry and what they are worth.",
  "tips.economy.bank": "Bank skull samples at the HQ sample window ({interact}). The PGB pays Cash — requisition credit for the supply terminal and your builds.",
  "tips.economy.supplies": "Starting Cash is a small seed for the first prep. Supply drops can dump ammo and MedPens; rare Cash stacks still go straight to the bank",
  "tips.misc.title": "Misc",
  "tips.misc.pause": "{pause} — pause / resume · {mute} — mute · {fullscreen} — fullscreen",
  "tips.misc.gear": "{nightVision} — night vision (buy after the helmet) · {laser} — laser sight (supply terminal) · {flashlight} — flashlight (on every gun from the start)",
  "tips.misc.settings": "Settings: volume, look sensitivity, graphics quality, camera, fullscreen — from the title screen or {pause}",
  "tips.testing.title": "Testing",
  "tips.testing.commands": "~ opens the dev console: \"bigtex shooter\" for unlimited Cash, \"broke\" to turn it off",
  "tips.testing.switches": "URL switches: ?debug=1 perf overlay · ?renderer=webgl WebGL2 fallback · ?sky=flat plain sky",

  // ammo
  "ammo.quantity.rounds": {"one":"{count} round","other":"{count} rounds"},
  "ammo.quantity.shells": {"one":"{count} shell","other":"{count} shells"},
  "ammo.quantity.grenades": {"one":"{count} grenade","other":"{count} grenades"},
  "ammo.quantity.fuel": "{count} fuel",

  // build
  "build.message.scrapAttached": "{scrap} scraps: {name} + {attached} on it — +{refund} Cash",
  "build.message.upgradeTarget": "{name} — {cost} Cash",
  "build.message.upgradePart": "{message} · {rotate}: {part}",
  "build.part.wall": "wall",
  "build.part.door": "door",
  "build.part.window": "window",

  // world
  "world.sign.keepout": "KEEP OUT",
  "world.sign.hazard": "DANGER",

  // a11y
  "a11y.cash": "Cash available: {amount}",
  "a11y.skulls": {"one":"Carrying {count} skull, skull value {value}","other":"Carrying {count} skulls, skull value {value}"},
  "a11y.health": "Health: {hp} of {max}",
  "a11y.armor": "Armor: {armor} of {max}",
  "a11y.weaponWheel": "Weapon wheel",
  "a11y.buildWheel": "Build wheel",
  "a11y.map": "Map",
  "a11y.minimap": "Minimap",
  "a11y.loading": "Loading progress",
  "a11y.coach": "Field guidance",
  "a11y.prep": "Preparation checklist",
  "a11y.settings": "Settings",
  "a11y.wavePreview": "Wave briefing",

  // fieldIntel
  "fieldIntel.name": "Field Intel",
  "fieldIntel.description": "See every enemy type, count and approach at the HQ panel.",
};

// Freeze plural records too: one area cannot accidentally change another's copy.
for (const value of Object.values(messages)) {
  if (typeof value === 'object') Object.freeze(value);
}
export const STRINGS = Object.freeze(messages);

/** True for complete catalogue keys; inherited object properties are never keys. */
export function hasText(key) {
  return typeof key === 'string' && Object.hasOwn(STRINGS, key);
}

/**
 * Format a keyed message. Plural records require an own, nonnegative integer count.
 * Supported values: strings, finite numbers and booleans. Null/missing/object
 * values are caller mistakes, not the literal words 'undefined' or '[object Object]'.
 * Unknown extra parameters are harmless; this lets a view pass its shared state.
 */
export function text(key, params = {}) {
  if (!hasText(key)) throw new RangeError('Unknown text key: ' + String(key));
  if (params === null || typeof params !== 'object' || Array.isArray(params)) {
    throw new TypeError('Text parameters must be an object: ' + key);
  }
  const entry = STRINGS[key];
  let template = entry;
  if (typeof entry === 'object') {
    if (!Object.hasOwn(params, 'count') || !Number.isSafeInteger(params.count) || params.count < 0) {
      throw new TypeError('Text requires a nonnegative integer count: ' + key);
    }
    template = params.count === 1 ? entry.one : entry.other;
  }
  return template.replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g, (placeholder, name) => {
    const supplied = Object.hasOwn(params, name);
    const fallback = Object.hasOwn(DEFAULT_INPUT_LABELS, name);
    if (!supplied && !fallback) throw new TypeError('Missing text parameter ' + name + ': ' + key);
    const value = supplied ? params[name] : DEFAULT_INPUT_LABELS[name];
    if (!['string', 'number', 'boolean'].includes(typeof value) ||
        (typeof value === 'number' && !Number.isFinite(value))) {
      throw new TypeError('Invalid text parameter ' + name + ': ' + key);
    }
    return String(value);
  });
}
