/**
 * Dead-Wave player copy — GP-1, 2026-09-23. ChatGPT owns this catalogue.
 * Native ES module; no imports, DOM/storage/audio access, timers or Three.js.
 * Deliberately NOT wired into index.html. Owners migrate their own callers.
 *
 * Usage: text('hq.deposit', { count: 2, interact: 'E' }).
 * Returns PLAIN TEXT. Use textContent/canvas text; never insert it as HTML.
 * Parameters are substituted once, so a callsign containing {name} stays literal.
 * Missing keys/parameters and invalid counts throw; test callers before wiring.
 * Input labels default to today's controls, but callers can override by action.
 * Supply numeric formatting (clock/precision) at the call site, never markup.
 *
 * Keys follow semantic namespaces, not DOM IDs or source line numbers. Keep
 * existing keys until all owners migrate. Tier numbers are stable game tiers.
 * legacy.* is migration-only copy: retire Skip prep in GP-2; do not use the
 * legacy menu description in the simplified menu. Other GP-2/3/4/5 and objective
 * entries are copy only, not implementations or promises those features exist.
 * World cave names preserve the current cardinal names; Claude owns later IDs.
 *
 * Inventory: shell/accessibility, HUD/maps, settings/tips, shop and catalogues,
 * builds/fortification/errors, combat/waves, interaction, deaths, debug UI;
 * plus the approved UI spec. Internal IDs, shader source, styles, logs and SVG
 * paths are deliberately not player copy. Snapshot SHA-256:
 * 96f0d03f2370c6df191b6346fcdcc06162732cbca11b162719681404ec3da7f3
 */

export const DEFAULT_INPUT_LABELS = Object.freeze({
  "fire": "LMB",
  "aim": "RMB",
  "move": "WASD",
  "forward": "W",
  "pause": "Esc",
  "map": "Tab",
  "run": "Shift",
  "jump": "Space",
  "fullscreen": "F11",
  "confirm": "Enter",
  "reload": "R",
  "rotate": "R",
  "melee": "F",
  "grenade": "G",
  "heal": "H",
  "weaponWheel": "Q",
  "interact": "E",
  "buildWheel": "B",
  "repair": "T",
  "carry": "T",
  "scrap": "X",
  "nightVision": "N",
  "akimbo": "Y",
  "laser": "Z",
  "flashlight": "L",
  "mute": "M",
  "dodge": "V",
  "crouch": "C"
});

const messages = {

  // common
  "common.on": "on",
  "common.off": "off",
  "common.down": "down",
  "common.enabled": "ON",
  "common.unknown": "—",
  "common.infinity": "∞",
  "common.ellipsis": "…",
  "common.back": "Back",
  "common.close": "Close",
  "common.ready": "Ready",
  "common.new": "NEW",
  "common.and": "{first} and {second}",
  "common.or": "{first} or {second}",
  "common.list": "{first} · {second}",
  "common.fraction": "{value} / {max}",
  "common.percent": "{value}%",
  "common.seconds": "{value}s",
  "common.metres": "{value} m",
  "common.multiplier": "{value}×",
  "common.price": "{amount} Cash",
  "common.priceCompact": "${amount}",
  "common.empty": "",
  "common.unavailable": "Unavailable",

  // menu
  "menu.title": "Dead Wave",
  "menu.titleFirst": "Dead",
  "menu.titleSecond": "Wave",
  "menu.studio": "CARACAL INTERACTIVE PRESENTS",
  "menu.play": "Play",
  "menu.settings": "Settings",
  "menu.quit": "Quit",
  "menu.callsign": "Callsign",
  "menu.namePlaceholder": "Enter your name",
  "menu.nameRequired": "Enter your name to play.",
  "menu.signal": "Signal established",
  "menu.closeWindow": "You can close this window.",

  // opening
  "opening.label": "Dead Wave opening",
  "opening.videoLabel": "Caracal studio intro",
  "opening.play": "Play intro with sound",
  "opening.connecting": "Connecting",
  "opening.reload": "Reload",
  "opening.soundOn": "Sound on",
  "opening.soundOff": "Sound off",
  "opening.skip": "Skip · {pause}",

  // loading
  "loading.terrain": "Preparing terrain…",
  "loading.world": "Preparing the world…",
  "loading.zombies": "Preparing enemies…",
  "loading.shaders": "Preparing graphics…",
  "loading.ready": "Ready",
  "loading.waiting": "Still working: {stage}",
  "loading.failed": "Couldn't finish loading.",
  "loading.retry": "Try again",
  "loading.unknown": "Preparing game…",
  "loading.units": "{completed} / {total} {unit}",
  "loading.error": "Unable to load",
  "loading.complete": "Complete",
  "loading.pending": "Waiting",
  "loading.active": "In progress",
  "loading.substage.terrain": "Terrain",
  "loading.substage.rocks": "Rocks",
  "loading.substage.trees": "Trees",
  "loading.substage.actors": "Marine, weapons and enemies",
  "loading.substage.foliage": "Ground cover",
  "loading.substage.pois": "Landmarks and map",
  "loading.substage.setup": "Scene setup",
  "loading.substage.compile": "Graphics preparation",
  "loading.substage.loop": "Renderer startup",
  "loading.substage.warmup": "First-frame preparation",
  "loading.substage.bake": "Reading the world",
  "loading.substage.generate": "Generating the world",
  "loading.stage.terrain": "Terrain",
  "loading.stage.world": "World",
  "loading.stage.zombies": "Enemies",
  "loading.stage.shaders": "Graphics",
  "loading.stage.ready": "Ready",
  "loading.stage.load": "Game loading",

  // legacy
  "legacy.loading.world": "Loading world",
  "legacy.loading.equipment": "Preparing equipment",
  "legacy.loading.scene": "Preparing scene",
  "legacy.loading.finishing": "Finishing up",
  "legacy.loading.still": "Still loading",
  "legacy.menu.tagline": "Survive the days. Bank skulls. Fortify the cabin.",
  "legacy.settings.skipPrep": "Skip prep time: {state}",

  // error
  "error.rendererTitle": "Dead Wave can’t start",
  "error.rendererUnsupported": "This machine reported neither WebGPU nor WebGL2.",
  "error.rendererHelp": "Update your browser or enable hardware acceleration, then reload.",
  "error.unknown": "Unknown error",
  "error.briefing": "Briefing unavailable",
  "error.generic": "Something went wrong. Try again.",

  // settings
  "settings.title": "Settings",
  "settings.music": "Music",
  "settings.sfx": "SFX",
  "settings.look": "Look",
  "settings.graphics": "Graphics",
  "settings.low": "Low",
  "settings.medium": "Medium",
  "settings.high": "High",
  "settings.max": "Max",
  "settings.camera": "Camera",
  "settings.followCursor": "Follow cursor: {state}",
  "settings.autoTilt": "Auto tilt",
  "settings.tiltOff": "Off",
  "settings.tiltGentle": "Gentle",
  "settings.tiltStrong": "Strong",
  "settings.screen": "Screen",
  "settings.fullscreen": "Fullscreen: {state}",
  "settings.fullscreenUnavailable": "Fullscreen unavailable",
  "settings.overlay": "Overlay",
  "settings.performance": "FPS & hardware: {state}",
  "settings.prep": "Prep",
  "settings.prepHelp": "Start the next wave at the HQ panel.",
  "settings.sensitivity": "{value}x",

  // pause
  "pause.title": "Paused",
  "pause.description": "Game frozen. Resume, change settings, check the tips, or quit back to the main menu.",
  "pause.resume": "Resume",
  "pause.tips": "Tips",
  "pause.quit": "Quit to menu",

  // hud
  "hud.cash": "Cash",
  "hud.skulls": "Skulls",
  "hud.skullValue": "Skull value: {value}",
  "hud.skullBag": "{count} ({value} skull value)",
  "hud.health": "Health",
  "hud.armor": "Armor",
  "hud.killStreak": "Kill streak",
  "hud.land": "Land r{radius}",
  "hud.landOpen": "{radius} · Land open",
  "hud.time": "{period} · {time}",
  "hud.day": "Day",
  "hud.night": "Night",
  "hud.rain": "Rain",
  "hud.grace": "Grace",
  "hud.bloodMoon": "Ember Night",
  "hud.tactical": "NVG {nvg} · Laser {laser} · Light {light}",
  "hud.scopeZoom": "{zoom}X",
  "hud.headshot": "HEADSHOT",
  "hud.critical": "CRIT",
  "hud.house": "House {hp} / {max}",
  "hud.ammo": "{loaded} / {magazine} · {reserve} spare",
  "hud.grenades": "{grenade}×{count}",
  "hud.medpens": "{heal}×{count}",
  "hud.reloading": "Reloading",
  "hud.reload": "Reload · {reload}",
  "hud.noFuel": "No fuel",
  "hud.noAmmo": "No ammo · kiosk",
  "hud.sawFuel": "Gas {fuel} / {max}",
  "hud.sawRunning": "Gas {fuel} / {max} · Running",
  "hud.sawEmpty": "Gas {fuel} / {max} · EMPTY",
  "hud.streakPower": "x{multiplier} skull value · {power}",
  "hud.wave.initial": "Day — · Prep",
  "hud.wave.menu": "Wave Day — · Press Play",
  "hud.wave.disabled": "Wave Day {day} · No waves (nodead)",
  "hud.wave.prep": "Wave Day {day} · Prep · Next: {total} · start at the HQ",
  "hud.wave.active": "Wave Day {day} · Zombies left: {remaining}",
  "hud.wave.idle": "Wave Day {day}",
  "hud.wave.grace": "{line} · Z-Grace",

  // map
  "map.close": "{map} close",
  "map.zombies": "zombies",
  "map.kiosk": "kiosk",
  "map.hq": "HQ",
  "map.builds": "builds",
  "map.reach": "dashed ring: minimap reach ({distance} m)",
  "map.ranger": "RANGER CAMP",
  "map.hikers": "HIKERS CAMP",
  "map.trapper": "TRAPPER CAMP",
  "map.campsite": "CAMPSITE",
  "map.cabin": "CABIN",
  "map.tower": "WATCHTOWER",
  "map.graveyard": "GRAVEYARD",
  "map.mast": "RADIO MAST",
  "map.dock": "DOCK",
  "map.shed": "HUT",
  "map.bridge": "BRIDGE",
  "map.pit": "UNDERWATER PIT",

  // compass
  "compass.n": "N",
  "compass.ne": "NE",
  "compass.e": "E",
  "compass.se": "SE",
  "compass.s": "S",
  "compass.sw": "SW",
  "compass.w": "W",
  "compass.nw": "NW",

  // world
  "world.hq": "HQ",
  "world.hqWindow": "HQ window",
  "world.dock": "Dock",
  "world.mast": "Radio mast",
  "world.tower": "Watchtower",
  "world.graveyard": "Graveyard",
  "world.pit": "Underwater Pit",
  "world.campsite": "Campsite",
  "world.ranger": "Ranger Camp",
  "world.hikers": "Hikers Camp",
  "world.trapper": "Trapper Camp",
  "world.cabin": "Cabin",
  "world.shed": "Hut",
  "world.wreck": "Truck wreck",
  "world.bridge": "Bridge",
  "world.cave.north": "North Cave",
  "world.cave.northeast": "Northeast Cave",
  "world.cave.east": "East Cave",
  "world.cave.southeast": "Southeast Cave",
  "world.cave.south": "South Cave",
  "world.cave.southwest": "Southwest Cave",
  "world.cave.west": "West Cave",
  "world.cave.northwest": "Northwest Cave",
  "world.cave.outer": "Outer Rim Cave",

  // hq
  "hq.deposit": {"one":"{interact} — Bank {count} skull","other":"{interact} — Bank {count} skulls"},
  "hq.depositValue": {"one":"{interact} — Bank {count} skull ({value} skull value)","other":"{interact} — Bank {count} skulls ({value} skull value)"},
  "hq.processing": "Processing skulls…",
  "hq.banked": "Banked {amount} Cash",
  "hq.processed": {"one":"{count} skull processed — spend the Cash at the kiosk","other":"{count} skulls processed — spend the Cash at the kiosk"},
  "hq.empty": "Bring skulls to the HQ window.",
  "hq.busyTitle": "HQ BUSY",
  "hq.busy": "Wait for the ding",
  "hq.emptyTitle": "NO SKULLS",
  "hq.alarm": "ALARM",
  "hq.alarmSounding": "Alarm sounding…",
  "hq.start": "{interact} — Sound the alarm: start the wave",
  "hq.inProgress": "Wave under way",
  "hq.waveTitle": "WAVE UNDER WAY",
  "hq.betweenWaves": "The panel works between waves",
  "hq.disabledTitle": "NODEAD IS ON",
  "hq.disabled": "Waves are switched off",
  "hq.heard": "Day {day} — they heard that",
  "hq.startReminderTitle": "START AT THE HQ",
  "hq.startReminder": "Sound the alarm on the panel by the HQ’s front wall",

  // interaction
  "interaction.kiosk": "{interact} — Supply Kiosk",
  "interaction.kioskLocked": "Kiosk locked — opens during prep",
  "interaction.mortar": "{interact} — Man the mortar",
  "interaction.mortarLeave": "{interact} — Leave the mortar · {carry} — Shoulder it",
  "interaction.closeDoor": "{interact} — Close the door",
  "interaction.openDoor": "{interact} — Open the door",
  "interaction.lowerStairs": "{interact} — Lower the stairs",
  "interaction.raiseStairs": "{interact} — Raise the stairs",
  "interaction.grave": "Here lies {name} — fell on Day {day}",

  // shop
  "shop.title": "Supply Kiosk",
  "shop.balance": "Cash ${amount}",
  "shop.buy": "Buy — {price} Cash",
  "shop.owned": "Owned",
  "shop.ownedButton": "OWNED",
  "shop.full": "Full",
  "shop.fullButton": "FULL",
  "shop.locked": "LOCKED",
  "shop.maxed": "MAXED",
  "shop.shortfall": "Need {amount} more Cash",
  "shop.noCash": "NO CASH",
  "shop.close": "Back to the fight ({interact} / {pause})",
  "shop.blueprint": "{name} blueprint",
  "shop.blueprintCost": "Places for {cost} Cash.",
  "shop.armorBonus": "+{amount} armor",
  "shop.carried": "{count} / {capacity} carried",
  "shop.rank": "rank {rank}",
  "shop.findTitle": "FIND THE KIOSK",
  "shop.find": "The supply hatch in the east wall of the cabin (yellow square on the map)",
  "shop.lockedTitle": "KIOSK LOCKED",
  "shop.lockedReason": "It only trades during prep — clear the wave first",
  "shop.blueprintsHelp": "Unlock a build here. Each placed piece costs Cash.",
  "shop.tabs.weapons": "Weapons",
  "shop.tabs.ammo": "Ammo",
  "shop.tabs.gear": "Gear",
  "shop.tabs.upgrades": "Upgrades",
  "shop.tabs.perks": "Perks",
  "shop.tabs.build": "Blueprints",
  "shop.tabs.builds": "Builds",
  "shop.tabs.fortify": "Fortify",
  "shop.hint.weapons": "One-time unlocks. Bought guns join the {weaponWheel} rotation and come with one loaded magazine.",
  "shop.hint.ammo": "The pistol uses .45; the Uzi uses 9mm. Guns of the same calibre share a reserve. {reload} reloads from it. Buy individual packs below or fill your reserves with Restock all.",
  "shop.hint.gear": "Tactical kit. Nothing here is issued; the nights are dark until you pay for eyes.",
  "shop.hint.upgrades": "Per-weapon improvements for guns you own. Extended mags are +50% (the revolver and launcher can't take one).",
  "shop.hint.perks": "Permanent for this run. Costs climb per rank so the last rank of anything is a real decision.",
  "shop.hint.build": "Blueprints put a build type into the {buildWheel} menu. Placing each piece still costs Cash on the spot.",
  "shop.hint.fortify": "Upgrade blueprints, tier by tier. Then take the Upgrade tool ({buildWheel} menu, Structure) to anything you have built and click it: each piece is upgraded one at a time, for the price shown.",
  "shop.ammo.restock": "Restock all",
  "shop.ammo.restockWeapon": "Restock",
  "shop.ammo.restockPrice": "Restock ${price}",
  "shop.ammo.restockFull": "Restock · Full",
  "shop.ammo.restockGunHelp": "Fill the {calibre} reserve to {capacity}. Whole-pack prices; {reload} reloads the gun.",
  "shop.ammo.restockFuelHelp": "Fill the chainsaw tank to {capacity}s at whole-pack prices.",
  "shop.ammo.short": "{count} short",
  "shop.ammo.allFull": "all full",
  "shop.ammo.restockHelp": "Fill all owned ammo reserves and chainsaw fuel at whole-pack prices. Shared calibres count once. {reload} reloads your gun.",
  "shop.ammo.fullHelp": "Every reserve is at its cap.",
  "shop.ammo.feedsMortar": "Feeds the mortar.",
  "shop.ammo.feeds": "Feeds {weapons}.",
  "shop.ammo.reserve": "{reserve} / {capacity} spare",
  "shop.ammo.pack": "+{quantity} {unit} to the reserve.",
  "shop.ammo.reserveFull": "Reserve is full.",
  "shop.ammo.packFeeds": "+{quantity} {unit} to the reserve. Feeds {weapons}.",
  "shop.ammo.packFeedsFull": "+{quantity} {unit} to the reserve. Feeds {weapons}. Reserve is full.",
  "shop.ammo.chainsaw": "Chainsaw gas",
  "shop.ammo.fuel": "{fuel}s / {capacity}s",
  "shop.ammo.fuelHelp": "+{seconds} seconds of cutting. Tops off at the tank cap.",
  "shop.ammo.nothing": "Nothing to feed",
  "shop.ammo.buyFirst": "Buy a gun first.",
  "shop.upgrade.machete": "Machete",
  "shop.upgrade.replacesKnife": "replaces the knife",
  "shop.upgrade.macheteHelp": "A proper blade for {melee}: {reach}m reach, {damage} damage and a wider arc (knife: {knifeReach}m, {knifeDamage}). Swings a touch slower.",
  "shop.upgrade.tank": "Bigger gas tank",
  "shop.upgrade.tankHelp": "+50% chainsaw fuel capacity ({seconds}s).",
  "shop.upgrade.pair": "{weapon} pair",
  "shop.upgrade.akimbo": "akimbo",
  "shop.upgrade.pairHelp": "A second {weapon} for the off hand. {akimbo} switches between one and two: twice the rate of fire and twice the loaded rounds, for a wider group, a slower reload, and no hand free for a grenade or the blade.",
  "shop.upgrade.biggerTank": "{weapon} bigger tank",
  "shop.upgrade.extendedMag": "{weapon} extended mag",
  "shop.upgrade.magHelp": "Magazine {before} → {after}, and a bigger reserve to match.",
  "shop.upgrade.fuelHelp": "Tank {before} → {after}, and a bigger reserve to match.",
  "shop.upgrade.nothing": "Nothing to upgrade yet",
  "shop.upgrade.buyFirst": "Buy a gun that takes an extended mag (or the chainsaw).",
  "shop.upgrade.fieldIntel": "Field Intel",
  "shop.upgrade.fieldIntelHelp": "See every enemy type, count and approach at the HQ panel.",
  "shop.fortify.toughness": "{hp} toughness (from {base}).",
  "shop.fortify.door": "+{hp} toughness on the wall it hangs in.",
  "shop.fortify.turret": "Damage ×{damage}, reach ×{range}, fire rate ×{rate}, toughness ×{hp}.",
  "shop.fortify.pieceCost": "Upgrading each piece: {cost} Cash.",
  "shop.fortify.requires": "Needs the {blueprint} blueprint first.",
  "shop.fortify.description": "{description} {stats} Upgrading each piece: {cost} Cash.",
  "shop.fortify.lockedDescription": "{description} {stats} Upgrading each piece: {cost} Cash. Needs the {blueprint} blueprint first.",
  "shop.gear.medpen": "MedPen",
  "shop.gear.medpenHelp": "Auto-injector. {heal} to jab one: heals 60% of max health. Natural regen only ever climbs back to 40%.",
  "shop.gear.repairArmor": "Repair armor",
  "shop.gear.repairArmorHelp": "Patch the plates back up to full. Armor also comes back to full at the start of each day.",
  "shop.gear.armorFull": "Everything is in one piece.",

  // weapon
  "weapon.minigun.name": "Minigun",
  "weapon.m4.name": "M4",
  "weapon.ak.name": "AK-47",
  "weapon.aa12.name": "AA-12",
  "weapon.pistol.name": "Pistol",
  "weapon.uzi.name": "Uzi",
  "weapon.shotgun.name": "Shotgun",
  "weapon.revolver.name": "Revolver",
  "weapon.sniper.name": "Sniper",
  "weapon.launcher.name": "Launcher",
  "weapon.flamer.name": "Flamethrower",
  "weapon.chainsaw.name": "Chainsaw",
  "weapon.pistol.description": "Sidearm. Reliable, slow.",
  "weapon.uzi.description": "Spray-and-pray SMG. Short range, fast.",
  "weapon.shotgun.description": "Seven-pellet pump. Devastating up close.",
  "weapon.m4.description": "Full-auto rifle. The workhorse.",
  "weapon.revolver.description": "Six heavy rounds. One-taps most things.",
  "weapon.sniper.description": "True scope, 2X/4X/6X. Headshots from across the map.",
  "weapon.ak.description": "Harder-hitting full-auto rifle. Slower and looser than the M4, but every round counts for more.",
  "weapon.aa12.description": "Full-auto shotgun off a 20-round drum. Five pellets a shell and no pump to work — it hoses a corridor.",
  "weapon.launcher.description": "40mm contact-fused grenades. Six in the drum.",
  "weapon.minigun.description": "300-round spin-up. Melts hordes.",
  "weapon.chainsaw.description": "No ammo, just gas. Hold to cut.",
  "weapon.flamer.description": "Hold to hose a stream of burning fuel, about 7m. It sticks to what it hits, sets the ground alight — including under you — and fizzles out in water. Burning zombies spread it to whatever they touch.",

  // blade
  "blade.knife.name": "Knife",
  "blade.machete.name": "Machete",

  // calibre
  "calibre.9mm": "9mm",
  "calibre.45": ".45",
  "calibre.556": "5.56mm",
  "calibre.762": "7.62mm",
  "calibre.44": ".44",
  "calibre.338": ".338",
  "calibre.12ga": "12ga",
  "calibre.40mm": "40mm",
  "calibre.belt762": "7.62 belt",
  "calibre.fuel": "Fuel",
  "calibre.60mm": "60mm",

  // ammo
  "ammo.unit.fuel": "fuel",
  "ammo.unit.shells": "shells",
  "ammo.unit.grenades": "grenades",
  "ammo.unit.rounds": "rounds",

  // gear
  "gear.helmet.name": "Combat helmet",
  "gear.helmet.description": "Ballistic helmet: +25 armor. Its rails are where the night-vision mount goes.",
  "gear.vest.name": "Plate carrier",
  "gear.vest.description": "Front and back plates with mag pouches: +50 armor.",
  "gear.pads.name": "Knee & elbow pads",
  "gear.pads.description": "+15 armor, and you are back on your feet from a dodge roll sooner.",
  "gear.nvg.name": "Night vision",
  "gear.nvg.description": "Flip-down NVGs ({nightVision}) on the helmet rails. The nights get very dark without them.",
  "gear.nvg.requires": "Needs the helmet",
  "gear.laser.name": "Laser sight",
  "gear.laser.description": "Aiming laser on every gun ({laser}). Tighter groups, easier tracking.",
  "gear.flashlight.name": "Gun flashlight",
  "gear.flashlight.description": "Weapon-mounted light ({flashlight}). A cone of visibility at night.",

  // perks
  "perks.vitality.name": "Vitality",
  "perks.vitality.description": "+20 max health per rank (heals to full)",
  "perks.power.name": "Stopping power",
  "perks.power.description": "+12% damage from every weapon per rank",
  "perks.hands.name": "Quick hands",
  "perks.hands.description": "Reloads and pump/cylinder work 12% faster per rank",
  "perks.legs.name": "Fleet foot",
  "perks.legs.description": "+5% walk and run speed per rank",
  "perks.scavenger.name": "Scavenger",
  "perks.scavenger.description": "+12% skull value from kills per rank",
  "perks.grenadier.name": "Grenadier",
  "perks.grenadier.description": "+1 grenade capacity and +8% blast radius per rank, and a fresh grenade each new day",

  // weapon
  "weapon.message.notOwned": "{name} NOT OWNED",
  "weapon.message.buyGear": "Buy it at the kiosk (Gear tab)",
  "weapon.message.noSecond": "NO SECOND GUN",
  "weapon.message.twoHanded": "{weapon} is a two-handed weapon",
  "weapon.message.akimboLocked": "AKIMBO NOT BOUGHT",
  "weapon.message.pairCost": "{weapon} pair costs {price} Cash (kiosk, Upgrades)",
  "weapon.message.akimbo": "AKIMBO",
  "weapon.message.single": "SINGLE",
  "weapon.message.twoGuns": "Two guns up — no grenades, no blade",
  "weapon.message.oneGun": "Back to one gun",
  "weapon.message.acquired": "{weapon} ACQUIRED",
  "weapon.message.draw": "{weaponWheel} to bring it up",
  "weapon.message.pair": "{weapon} PAIR",
  "weapon.message.switchPair": "{akimbo} switches between one gun and two",
  "weapon.message.outOfAmmo": "OUT OF AMMO",
  "weapon.message.restock": "Restock at the kiosk (Ammo tab)",
  "weapon.message.handsFull": "BOTH HANDS FULL",
  "weapon.message.freeHand": "{akimbo} goes back to one gun",
  "weapon.message.notBought": "{weapon} — NOT BOUGHT",
  "weapon.message.buy": "Buy it at the kiosk ({price} Cash)",

  // build
  "build.upgrade.name": "Upgrade",
  "build.gate.name": "Gate",
  "build.pillar.name": "Structural pillar",
  "build.shovel.name": "Shovel",
  "build.window.name": "Window",
  "build.door.name": "Door",
  "build.platform.name": "Platform",
  "build.floor.name": "Floor",
  "build.stairs.name": "Stairs",
  "build.wire.name": "Barbed wire",
  "build.railing.name": "Railing",
  "build.barricade.name": "Barricade",
  "build.wall.name": "Wall",
  "build.spikes.name": "Spike trap",
  "build.sandbag.name": "Sandbag wall",
  "build.barrel.name": "Fuel drum",
  "build.mine.name": "Land mine",
  "build.lure.name": "Decoy beacon",
  "build.light.name": "Light turret",
  "build.flame.name": "Flame turret",
  "build.heavy.name": "Heavy turret",
  "build.mortar.name": "Mortar",
  "build.upgrade.description": "Point at something you built and click to take it up a tier: walls to stone and steel, doors to iron, turrets to Mk II and III, floors, gates, bars for windows. Each tier's blueprint is bought in the kiosk's Fortify tab; {rotate} picks which part of a wall (its door or window, or the wall itself).",
  "build.gate.description": "Cuts a gate into a run of barbed wire, a barricade or a railing — point at it. {interact} opens and shuts it like a door. Shut, it holds like the run it replaced; upgrade it to iron and steel.",
  "build.pillar.description": "Steel post for the corner where four squares meet. On its own it holds up a floor or platform in each of those four squares; with a wall within three squares, in twelve. Its cap takes a turret.",
  "build.shovel.description": "Levels the cell you point at, and fills in any rabbit burrow in it, blending it into the ground around it. Rough or sloping ground refuses a build; this is how you fix it. Works on a cell that already has something standing in it.",
  "build.window.description": "Cuts a firing window in a wall. Ground-level windows let smaller zombies climb inside: fit steel mesh in Fortify to stop them. Weakens the wall.",
  "build.door.description": "Hangs a pair of doors in a wall — point at the wall. {interact} opens and shuts them: shut, they are as solid as the wall; open, anything can walk through — so close them behind you. Weakens the wall more than a window does.",
  "build.platform.description": "Steel deck on the walls of its square — or bolted onto a wooden floor as a gun mount (one per floor). Its raised middle lifts a turret over the rail line, and all four edges can take a railing.",
  "build.floor.description": "Wooden boards on the walls of its square, or bridging out from the wall of the square next door: a floor for the storey above and a roof for the one below. A platform can go on a floor; a floor never goes on a platform.",
  "build.stairs.description": "Takes the whole cell and ramps up a storey. Anything that walks can use them — including the horde, so mind where you put them.",
  "build.wire.description": "Half height, so you shoot straight over it. Runs along a square’s edge like a wall: on the ground, a deck’s rim, or strung along the top of a wall, sandbags or a barricade (point at it). Cuts anything that comes through it, and comes apart quickly.",
  "build.railing.description": "Low rail for a deck edge: {rotate} picks the edge, and a deck can be railed on all four with a turret in the middle. Your rounds go between the bars.",
  "build.barricade.description": "Cheap steel beams along a square’s edge. Slows and soaks. Goes on the ground, a deck, or along the top of a wall.",
  "build.wall.description": "Solid log wall along the edge of a square — {rotate} picks the edge, two in one square make a corner. Real stopping power.",
  "build.sandbag.description": "Low, tough cover along a square’s edge, or heaped along the top of a wall. Cheap to line a lane with.",
  "build.spikes.description": "Buried spike bed. Springs once when something steps into its square: spikes through everything standing on it, then it is spent and the square is free again.",
  "build.barrel.description": "Fuel drum. Shoot it when the pack is beside it; chains into its neighbours.",
  "build.mine.description": "Buried charge. Goes off under the first thing that steps on it.",
  "build.lure.description": "Flashing, screaming beacon. The horde chases it instead of you for 20s, then it burns out.",
  "build.light.description": "Auto-turret. Cheap, chattery, fine vs. shamblers.",
  "build.flame.description": "Short-range fire cone. Crowds hate it.",
  "build.heavy.description": "Slow, hard-hitting sentry gun.",
  "build.mortar.description": "Crew-served tube. {interact} to mount, {fire} lobs a shell at the reticle (arc shown), {carry} to shoulder it and carry it elsewhere. Shells sold under Ammo.",

  // fortify
  "fortify.wall.category": "Walls",
  "fortify.wall.tier0.name": "Wood wall",
  "fortify.wall.tier1.name": "Reinforced wood wall",
  "fortify.wall.tier2.name": "Stone wall",
  "fortify.wall.tier3.name": "Reinforced stone wall",
  "fortify.wall.tier4.name": "Steel wall",
  "fortify.door.category": "Doors",
  "fortify.door.tier0.name": "Wood door",
  "fortify.door.tier1.name": "Reinforced wood door",
  "fortify.door.tier2.name": "Iron door",
  "fortify.door.tier3.name": "Reinforced iron door",
  "fortify.door.tier4.name": "Steel door",
  "fortify.floor.category": "Floors",
  "fortify.floor.tier0.name": "Wood floor",
  "fortify.floor.tier1.name": "Stone floor",
  "fortify.floor.tier2.name": "Steel floor",
  "fortify.light.category": "Light turrets",
  "fortify.light.tier0.name": "Light turret",
  "fortify.light.tier1.name": "Light turret Mk II",
  "fortify.light.tier2.name": "Light turret Mk III",
  "fortify.flame.category": "Flame turrets",
  "fortify.flame.tier0.name": "Flame turret",
  "fortify.flame.tier1.name": "Flame turret Mk II",
  "fortify.flame.tier2.name": "Flame turret Mk III",
  "fortify.heavy.category": "Heavy turrets",
  "fortify.heavy.tier0.name": "Heavy turret",
  "fortify.heavy.tier1.name": "Heavy turret Mk II",
  "fortify.heavy.tier2.name": "Heavy turret Mk III",
  "fortify.gate.category": "Gates",
  "fortify.gate.tier0.name": "Wooden gate",
  "fortify.gate.tier1.name": "Iron gate",
  "fortify.gate.tier2.name": "Steel gate",
  "fortify.bars.category": "Window mesh",
  "fortify.bars.tier0.name": "Window",
  "fortify.bars.tier1.name": "Steel mesh window",
  "fortify.barricade.category": "Barricades",
  "fortify.barricade.tier0.name": "Barricade",
  "fortify.barricade.tier1.name": "Braced barricade",
  "fortify.barricade.tier2.name": "Czech hedgehog",
  "fortify.sandbag.category": "Sandbag walls",
  "fortify.sandbag.tier0.name": "Sandbag wall",
  "fortify.sandbag.tier1.name": "Double-stacked sandbags",
  "fortify.sandbag.tier2.name": "Gabion wall",
  "fortify.wire.category": "Barbed wire",
  "fortify.wire.tier0.name": "Barbed wire",
  "fortify.wire.tier1.name": "Concertina wire",
  "fortify.wire.tier2.name": "Razor wire",
  "fortify.railing.category": "Railings",
  "fortify.railing.tier0.name": "Railing",
  "fortify.railing.tier1.name": "Mesh railing",
  "fortify.railing.tier2.name": "Armoured parapet",
  "fortify.platform.category": "Platforms",
  "fortify.platform.tier0.name": "Platform",
  "fortify.platform.tier1.name": "Plated platform",
  "fortify.platform.tier2.name": "Gun emplacement",
  "fortify.pillar.category": "Pillars",
  "fortify.pillar.tier0.name": "Structural pillar",
  "fortify.pillar.tier1.name": "Concrete pillar",
  "fortify.pillar.tier2.name": "Steel column",
  "fortify.stairs.category": "Stairs",
  "fortify.stairs.tier0.name": "Stairs",
  "fortify.stairs.tier1.name": "Steel stairs",
  "fortify.stairs.tier2.name": "Retractable stairs",
  "fortify.mortar.category": "Mortars",
  "fortify.mortar.tier0.name": "Mortar",
  "fortify.mortar.tier1.name": "Mortar Mk II",
  "fortify.mortar.tier2.name": "Mortar Mk III",
  "fortify.spikes.category": "Spike traps",
  "fortify.spikes.tier0.name": "Spike trap",
  "fortify.spikes.tier1.name": "Resetting spikes",
  "fortify.spikes.tier2.name": "Steel spike bed",
  "fortify.mine.category": "Land mines",
  "fortify.mine.tier0.name": "Land mine",
  "fortify.mine.tier1.name": "Frag mine",
  "fortify.mine.tier2.name": "Bounding mine",
  "fortify.lure.category": "Decoy beacons",
  "fortify.lure.tier0.name": "Decoy beacon",
  "fortify.lure.tier1.name": "Siren beacon",
  "fortify.lure.tier2.name": "Shock beacon",
  "fortify.barrel.category": "Fuel drums",
  "fortify.barrel.tier0.name": "Fuel drum",
  "fortify.barrel.tier1.name": "Napalm drum",
  "fortify.wall.tier1.description": "Steel straps both faces and an X-brace: tougher, same timber.",
  "fortify.wall.tier2.description": "Dressed stone courses. A real wall.",
  "fortify.wall.tier3.description": "Stone girdled with iron bands and plated corners.",
  "fortify.wall.tier4.description": "Ribbed, riveted steel plate on I-beam posts. The last word.",
  "fortify.door.tier1.description": "Iron-edged, strapped and studded.",
  "fortify.door.tier2.description": "A ribbed iron plate door.",
  "fortify.door.tier3.description": "Iron, cross-braced and bolted.",
  "fortify.door.tier4.description": "A steel vault door with a wheel lock.",
  "fortify.floor.tier1.description": "Stone flags on a mortar bed.",
  "fortify.floor.tier2.description": "Riveted steel tread plate.",
  "fortify.light.tier1.description": "Twin barrels and side armour.",
  "fortify.light.tier2.description": "Triple barrels, a gun shield and a sensor eye.",
  "fortify.flame.tier1.description": "A second tank and a heat shield.",
  "fortify.flame.tier2.description": "Three tanks, a flared nozzle, blue-hot.",
  "fortify.heavy.tier1.description": "Twin cannon and armour skirts.",
  "fortify.heavy.tier2.description": "An armoured hood and a radar dish.",
  "fortify.gate.tier1.description": "Wrought iron bars with spear tips.",
  "fortify.gate.tier2.description": "A steel gate: solid below, grilled above.",
  "fortify.bars.tier1.description": "Steel mesh across the window: fire out while stopping zombie climbs and claws.",
  "fortify.barricade.tier1.description": "A welded plate and a second brace.",
  "fortify.barricade.tier2.description": "Crossed steel beams. Anything that swings at it is knocked back a step.",
  "fortify.sandbag.tier1.description": "A fifth course and a plank on top. Armours what it stands on by 40.",
  "fortify.sandbag.tier2.description": "Wire baskets packed with rock. Armours what it stands on by 60.",
  "fortify.wire.tier1.description": "A coiled spiral: 12 damage to whatever tears at it.",
  "fortify.wire.tier2.description": "Razor tape on steel pickets: 18 damage, and it leaves them slowed.",
  "fortify.railing.tier1.description": "Welded mesh panels.",
  "fortify.railing.tier2.description": "Steel plate to the waist with a firing ledge. Acid and spit no longer reach you through it.",
  "fortify.platform.tier1.description": "A steel skirt round the rim.",
  "fortify.platform.tier2.description": "Sandbagged rim and an ammo locker: the gun on it fires 10% faster.",
  "fortify.pillar.tier1.description": "Poured concrete: braced by a wall within four squares.",
  "fortify.pillar.tier2.description": "A steel column: braced within five squares.",
  "fortify.stairs.tier1.description": "Checker-plate treads on steel stringers.",
  "fortify.stairs.tier2.description": "Steel, and it folds: press {interact} to pull the flight up behind you.",
  "fortify.mortar.tier1.description": "Sandbagged base and a second crate: 25% more blast, reloads 20% faster.",
  "fortify.mortar.tier2.description": "A long tube on a turntable: 50% more blast, reloads 35% faster.",
  "fortify.spikes.tier1.description": "Springs three times, re-arming 20 seconds after each.",
  "fortify.spikes.tier2.description": "A steel bed that never wears out: re-arms in 10 seconds, 200 damage, and leaves them bleeding.",
  "fortify.mine.tier1.description": "Fragmentation casing: 110 damage over a wider blast.",
  "fortify.mine.tier2.description": "Bounding charge: it jumps waist-high first. 150 damage.",
  "fortify.lure.tier1.description": "A siren: calls for 35 seconds, and from half again as far.",
  "fortify.lure.tier2.description": "A shock beacon: 45 seconds, and it zaps anything within 2 m.",
  "fortify.barrel.tier1.description": "Napalm: the blast leaves a burning pool that sets them alight.",

  // build
  "build.category.structure": "Structure",
  "build.category.defenses": "Defenses",
  "build.category.turrets": "Turrets",
  "build.reason.cannotBuild": "Cannot be built",
  "build.reason.runRequired": "Needs a run of wire, a barricade or a railing",
  "build.reason.wallRequired": "Needs a plain wall to cut into",
  "build.reason.pillarTaken": "There is already a pillar there",
  "build.reason.pillarTurretOnly": "A pillar only carries a turret",
  "build.reason.pillarTurretTaken": "That pillar already has a turret",
  "build.reason.nothingUnder": "Nothing under it",
  "build.reason.builtOver": "Built over",
  "build.reason.tooFar": "Too far",
  "build.reason.cellTaken": "Cell taken",
  "build.reason.edgeTaken": "That edge already has one",
  "build.reason.wallTaken": "That wall already has something on it",
  "build.reason.noRoom": "No room",
  "build.reason.openGround": "Needs open ground",
  "build.reason.support": "Needs a {supports} under it",
  "build.reason.occupied": "Something already standing there",
  "build.reason.belowWallTaken": "Something is on top of the wall below",
  "build.reason.standingOn": "Something is standing on the {name}",
  "build.reason.cannotStandOn": "Will not stand on {name}",
  "build.reason.unsupported": "Too far from anything to hold it up",
  "build.reason.stairsCell": "The stairs take the whole cell",
  "build.reason.cannotSitOn": "Will not sit on {name}",
  "build.reason.maxHeight": "Stacked as high as it goes",
  "build.reason.landmark": "{name} in the way — shoot it, knife it or dig it out",
  "build.reason.obstructed": "Something in the way",
  "build.reason.offMap": "Off the map",
  "build.reason.cave": "Too close to the cave",
  "build.reason.water": "In the water",
  "build.reason.nearWater": "Too close to the water",
  "build.reason.cabin": "That is the cabin",
  "build.reason.rough": "Ground too rough",
  "build.reason.player": "You are standing there",
  "build.reason.funds": "Not enough Cash",
  "build.reason.locked": "Blueprint required",
  "build.obstacle.fence": "a fence",
  "build.obstacle.campsite": "a camp",
  "build.obstacle.camp": "a camp",
  "build.obstacle.shed": "a shed",
  "build.obstacle.sign": "a sign",
  "build.obstacle.barrel": "a fuel drum",
  "build.obstacle.graveyard": "the graveyard",
  "build.obstacle.cabin": "a cabin",
  "build.message.noBlueprint": "{name} — NO BLUEPRINT",
  "build.message.buyBlueprint": "Buy the plans at the kiosk ({price} Cash)",
  "build.message.upgradeControls": "{fire} click one · drag for a box · {rotate} door / window / wall",
  "build.message.scrapControls": "{scrap} hold + release to scrap · {buildWheel} exit build mode",
  "build.message.placeControls": "{rotate} rotate ({bearing}) · {fire} place · {repair} repair · {scrap} hold + release to scrap · hold {scrap} + drag for a box · {buildWheel} exit build mode",
  "build.message.dragControls": "{rotate} rotate ({bearing}) · {fire} place · drag for a line · {repair} repair · {scrap} hold + release to scrap · hold {scrap} + drag for a box · {buildWheel} exit build mode",
  "build.message.price": "{name} — {cost} Cash",
  "build.message.nothing": "NOTHING THERE",
  "build.message.scrapPoint": "Point at the piece you want to scrap",
  "build.message.cannotBuild": "CAN'T BUILD THERE",
  "build.message.shovel": "SHOVEL",
  "build.message.shovelRemaining": "Keep at it — {hp} left",
  "build.message.rubble": "RUBBLE CLEARED",
  "build.message.burrow": "BURROW FILLED IN",
  "build.message.insufficient": "NOT ENOUGH CASH",
  "build.message.cost": "{name} costs {cost} Cash",
  "build.message.stairsUp": "STAIRS UP",
  "build.message.stairsDown": "STAIRS DOWN",
  "build.message.stairsSafe": "Nothing is climbing those",
  "build.message.cannotUpgrade": "CAN'T UPGRADE",
  "build.message.upgradePoint": "Point at something you built",
  "build.message.noUpgrades": "{name} has no upgrades",
  "build.message.maxUpgrade": "{name} — fully upgraded",
  "build.message.requiresUpgrade": "Buy the {name} blueprint at the kiosk",
  "build.message.upgraded": "UPGRADED",
  "build.message.nothingUpgraded": "NOTHING UPGRADED",
  "build.message.upgradeEmpty": "Nothing in the box to upgrade",
  "build.message.boxUpgradeEmpty": "Nothing in the box can be upgraded",
  "build.message.boxUpgrade": {"one":"Release to upgrade {count} of {total} piece — {cost} Cash","other":"Release to upgrade {count} of {total} pieces — {cost} Cash"},
  "build.message.boxScrap": {"one":"Release the mouse to scrap {count} piece — +{refund} Cash","other":"Release the mouse to scrap {count} pieces — +{refund} Cash"},
  "build.message.upgradeReceipt": {"one":"{count} piece — {cost} Cash","other":"{count} pieces — {cost} Cash"},
  "build.message.outOfCash": "OUT OF CASH",
  "build.message.partial": "Built {built} of {total} — {name} costs {cost} Cash",
  "build.message.built": "BUILT {built} OF {total}",
  "build.message.scrapBox": "Drag over the pieces you want to scrap",
  "build.message.scrapped": "SCRAPPED {count}",
  "build.message.refund": "+{amount} Cash",
  "build.message.scrapHint": "{scrap} scraps: {name} — +{refund} Cash",
  "build.message.scrapSupported": "{scrap} scraps: {name} +{count} on it — +{refund} Cash",
  "build.message.upgradeHint": "{name} — {cost} Cash · {rotate}: {part}",
  "build.message.that": "That",

  // mortar
  "mortar.manned": "MORTAR MANNED",
  "mortar.controls": "{fire} fire at the reticle · {interact} dismount · {carry} shoulder it · {shells} shells",
  "mortar.overhead": "BLOCKED OVERHEAD",
  "mortar.blocked": "The shell would hit your own {name} — move the tube into the open",
  "mortar.noShells": "NO MORTAR SHELLS",
  "mortar.buyShells": "Sold under Ammo at the kiosk",
  "mortar.carrying": "Carrying the mortar — {fire} / {interact} to set it down",
  "mortar.shouldered": "MORTAR SHOULDERED",
  "mortar.carryHelp": "No weapons while you carry it. {fire} or {interact} sets it down.",

  // wheel
  "wheel.gas": "{seconds}s gas",
  "wheel.ammo": "{loaded} + {reserve}",
  "wheel.tier": "price per tier",
  "wheel.plans": "plans {price} Cash",
  "wheel.weaponLocked": "Not bought · kiosk {price} Cash",
  "wheel.buildLocked": "No blueprint · kiosk {price} Cash",

  // death
  "death.shambler.name": "Shambler",
  "death.shambler.description": "Torn apart by a shambler.",
  "death.feral.name": "Feral",
  "death.feral.description": "Run down by a feral.",
  "death.leaper.name": "Leaper",
  "death.leaper.description": "Flattened under a leaper.",
  "death.spider.name": "Spider",
  "death.spider.description": "Wrapped and eaten by a spider.",
  "death.drowned.name": "Drowned",
  "death.drowned.description": "Pulled apart by the drowned.",
  "death.military.name": "Military",
  "death.military.description": "Outfought by a dead soldier.",
  "death.brute.name": "Brute",
  "death.brute.description": "Beaten down by a brute.",
  "death.spitter.name": "Spitter",
  "death.spitter.description": "Smothered by a spitter.",
  "death.screamer.name": "Screamer",
  "death.screamer.description": "Silenced by a screamer.",
  "death.bomber.name": "Bomber",
  "death.bomber.description": "Caught a bomber’s blast point-blank.",
  "death.demon.name": "Demon",
  "death.demon.description": "Gored on a demon’s horns.",
  "death.colossus.name": "Colossus",
  "death.colossus.description": "Crushed under the colossus.",
  "death.blast.name": "Explosion",
  "death.blast.description": "Blown apart by an explosion.",
  "death.fire.name": "Fire",
  "death.fire.description": "Burned to death.",
  "death.acid.name": "Acid",
  "death.acid.description": "Dissolved in spider acid.",
  "death.tree.name": "Falling tree",
  "death.tree.description": "Crushed by a falling tree.",
  "death.towerfall.name": "Tower collapse",
  "death.towerfall.description": "Rode the watchtower down.",
  "death.bird.name": "Birds",
  "death.bird.description": "Pecked to death by carrion birds.",
  "death.caveguard.name": "Cave Guardian",
  "death.caveguard.description": "Dragged into the dark.",
  "death.tentacles.name": "Underwater Pit",
  "death.tentacles.description": "Something in the Underwater Pit was hungry.",

  // enemy
  "enemy.shambler.name": "Shambler",
  "enemy.feral.name": "Feral",
  "enemy.leaper.name": "Leaper",
  "enemy.spider.name": "Spider",
  "enemy.drowned.name": "Drowned",
  "enemy.military.name": "Military",
  "enemy.brute.name": "Brute",
  "enemy.spitter.name": "Spitter",
  "enemy.screamer.name": "Screamer",
  "enemy.bomber.name": "Bomber",
  "enemy.demon.name": "Demon",
  "enemy.colossus.name": "Colossus",
  "enemy.guardian.name": "Guardian",
  "enemy.caveguard.name": "Cave Guardian",

  // streak
  "streak.rampage": "RAMPAGE",
  "streak.rampageHelp": "5 streak · x1.25 skull value · faster feet",
  "streak.massacre": "MASSACRE",
  "streak.massacreHelp": "10 streak · x1.5 skull value · quick reloads",
  "streak.unstoppable": "UNSTOPPABLE",
  "streak.unstoppableHelp": "20 streak · x2 skull value · rounds on the house",
  "streak.godlike": "GODLIKE",
  "streak.godlikeHelp": "30 streak · x2.5 skull value · a quarter of all damage shrugged off",
  "streak.lost": "STREAK LOST — {count}",
  "streak.thickSkin": "thick skin",
  "streak.freeRounds": "free rounds",
  "streak.quickHands": "quick hands",
  "streak.fastFeet": "fast feet",

  // wave
  "wave.cleared": "DAY {day} CLEARED",
  "wave.prep": "Use the prep — repair, build, resupply, turn in skulls",
  "wave.prepBest": "Use the prep — repair, build, resupply, turn in skulls · best streak {streak}",
  "wave.bloodMoon": "EMBER NIGHT",
  "wave.bloodMoonHelp": "Day {day} — the horde runs faster, kills worth x1.5 skull value",
  "wave.inbound": "DAY {day} — HORDE INBOUND",
  "wave.surround": "They're coming from every direction",
  "wave.from": "From {sources}",
  "wave.compassSource": "the {bearing}",
  "wave.boss": "{approach} — something enormous walks with them",
  "wave.colossusDown": "COLOSSUS DOWN",
  "wave.colossusReward": "{value} skull value — turn the skulls in at HQ",

  // prep
  "prep.ready": "Prep — ready when you are",
  "prep.start": "Start the wave at the HQ panel ({interact})",
  "prep.day": "Prep — day {day} · {count} coming",
  "prep.alarmSounding": "Alarm sounding",
  "prep.inbound": "INBOUND",
  "prep.readyStatus": "READY",
  "prep.summary": "Prep {done}/{total}",
  "prep.bank": "Bank your skulls",
  "prep.ammo": "Restock {calibre}",
  "prep.fortify": "Fortify the {bearing} approach",
  "prep.repair": "Repair the damaged {buildName}",
  "prep.alarm": "Start the wave at the HQ panel",
  "prep.unavailable": "No longer available",
  "prep.complete": "Complete",

  // supply
  "supply.inbound": "SUPPLY DROP INBOUND",
  "supply.direction": "Plane overhead — crate coming down {bearing} of you",
  "supply.title": "SUPPLY DROP",
  "supply.ammoRestocked": "Ammo restocked",
  "supply.ammoFull": "Ammo full",
  "supply.medpensFull": "MedPens full",
  "supply.medpens": {"one":"+{count} MedPen","other":"+{count} MedPens"},
  "supply.receipt": "{ammoStatus} · {medpenStatus}",
  "supply.noMedpens": "NO MEDPENS",
  "supply.medpenHelp": "Buy them at the kiosk, or find one in a supply drop",
  "supply.medpen": "MEDPEN",
  "supply.medpenPickedUp": "+1 MedPen ({count}/{capacity}) · {heal} to use",
  "supply.medpenUsed": "Pockets full — used on the spot, +{percent}% health",

  // world
  "world.message.towerFall": "THE TOWER COLLAPSED!",
  "world.message.towerFallHelp": "You should have climbed down sooner…",
  "world.message.towerCollapsed": "The watchtower has collapsed",
  "world.message.nest": "NEST DESTROYED",
  "world.message.nestHelp": "A bird is furious",
  "world.message.timber": "TIMBER",
  "world.message.timberHelp": "Watch where they fall",
  "world.message.webbed": "WEBBED",
  "world.message.webbedHelp": "Slowed — shake it off",

  // gameOver
  "gameOver.win": "You did it!",
  "gameOver.title": "Game over",
  "gameOver.winHelp": "Nice work.",
  "gameOver.retry": "Try again?",
  "gameOver.again": "Play again",
  "gameOver.overrun": "You were overrun…",
  "gameOver.houseLost": "The house was destroyed!",
  "gameOver.day": "Day",
  "gameOver.kills": "Kills",
  "gameOver.headshots": "Headshots",
  "gameOver.bestStreak": "Best streak",
  "gameOver.deathLog": "Ways to die · {seen} / {total} found",
  "gameOver.deathLogNew": "Ways to die · {seen} / {total} found · NEW",
  "gameOver.unknownDeath": "???",
  "gameOver.cave": "Dragged into {place}.",
  "gameOver.rest": "Rest easy, {name}",
  "gameOver.unknownMarine": "Unknown Marine",

  // cinematic
  "cinematic.skip": "{jump} — skip",
  "cinematic.fell": "FELL ON DAY {day}",
  "cinematic.kills": {"one":"{count} KILL","other":"{count} KILLS"},
  "cinematic.noPlot": "No plot left for {name}",
  "cinematic.lake": "The lake keeps them now",

  // coach
  "coach.pickup": "Skulls collected.",
  "coach.return": "Bring them to the HQ window to bank Cash.",
  "coach.bank": "Press {interact} to bank your skulls.",
  "coach.purchase": "Purchase ready.",
  "coach.loop": "Collect skulls. Bank Cash. Resupply.",

  // wavePreview
  "wavePreview.title": "Day {day} briefing",
  "wavePreview.alarm": "Sound alarm",
  "wavePreview.locked": "Field Intel reveals the full roster and counts.",
  "wavePreview.largest": "Largest approach: {source} · {bearing}",
  "wavePreview.mainThreat": "Main threat: {enemy}",
  "wavePreview.multiple": "Multiple approaches",
  "wavePreview.empty": "No attack scheduled",
  "wavePreview.unavailable": "Briefing unavailable",
  "wavePreview.row": "{enemy}: {count}",
  "wavePreview.sourceTotal": "{source}: {count}",
  "wavePreview.total": "Total: {count}",
  "wavePreview.inProgress": "Wave under way",
  "wavePreview.upgrade": "Field Intel",
  "wavePreview.upgradeDescription": "See every enemy type, count and approach at the HQ panel.",
  "wavePreview.prompt": "{interact} — HQ briefing",
  "wavePreview.unknownSource": "Unconfirmed approach",
  "wavePreview.unknownBearing": "Bearing unconfirmed",
  "wavePreview.lake": "Lake",
  "wavePreview.perimeter": "Outer perimeter",
  "wavePreview.colossus": "Colossus detected",
  "wavePreview.guardianNight": "Guardian night",
  "wavePreview.guardianFromCave": "From {source}",
  "wavePreview.guardianUrgent": "A Guardian is coming from {source}.",
  "wavePreview.prep": "Preparation",
  "wavePreview.hudBasic": "Wave Day {day} · Prep · HQ briefing",
  "wavePreview.hudFull": "Wave Day {day} · Prep · Next: {count} · HQ briefing",
  "wavePreview.prepDay": "Prep — day {day}",

  // Guardian first-blood reward; announce only the confirmed economy result.
  "reward.guardianFirstBlood": "First Guardian defeated",
  "reward.guardianBlueprint": "Mortar blueprint unlocked",
  "reward.guardianSkulls": "+80 skull value — bank it at the HQ window",

  // objectives
  "objectives.track": "Track",
  "objectives.untrack": "Stop tracking",
  "objectives.interact": "{interact} — {action}",
  "objectives.repairing": "Restoring signal…",
  "objectives.interrupted": "Repair interrupted",
  "objectives.claim": "Take supplies",
  "objectives.choosePack": "Choose supplies",
  "objectives.holdRepair": "Hold {interact} for 6 seconds to restore the radio",
  "objectives.mapLegend": "Gold markers: supplies · select one to track",
  "objectives.packChoice": "{calibre} · {pack}",
  "objectives.full": "Inventory full — supplies remain",
  "objectives.claimed": "Supplies collected",
  "objectives.unavailable": "Site unavailable",
  "objectives.distance": "{distance} m",
  "objectives.reward": "Reward: {reward}",
  "objectives.remaining": "Supplies remaining: {reward}",
  "objectives.progress": "{objective} · {distance} m",
  "objectives.radioRepair": "Restore the radio mast",
  "objectives.medicalConvoy": "Recover medical supplies",
  "objectives.rangerCache": "Search the ranger cache",
  "objectives.hikersCache": "Recover the hikers' first-aid kit",
  "objectives.trapperCache": "Recover the trapper's supplies",
  "objectives.fuelDepot": "Recover the depot fuel",
  "objectives.wreckSalvage": "Salvage the utility truck",

  // dev
  "dev.consoleLabel": "Command",
  "dev.bigtex": "BIGTEX SHOOTER",
  "dev.unlocked": "Everything unlocked · Unlimited Cash",
  "dev.cashOff": "CASH CHEAT OFF",
  "dev.godmode": "GODMODE",
  "dev.invincible": "Invincible",
  "dev.godmodeOff": "GODMODE OFF",
  "dev.nodead": "NODEAD",
  "dev.noWaves": "Zombies and waves disabled",
  "dev.godead": "GODEAD",
  "dev.nodeadOff": "NODEAD OFF",
  "dev.wavesBack": "Zombies and waves are back",
  "dev.night": "NIGHT OPS",
  "dev.nightHelp": "Night has fallen",
  "dev.shower": "SHOWER",
  "dev.showerHelp": "Storm rolling in",
  "dev.unknown": "UNKNOWN COMMAND",
  "dev.benchmark": "BENCHMARK",
  "dev.benchmarkHelp": "Recording 25 seconds — stand and watch",
  "dev.benchmarkResult": "avg {average} fps · 5% low {low5} · 1% low {low1} · worst {worst}ms · {draws} draws · {triangles}k tris · {pieces} pieces · {alive} alive",
  "dev.swarm": "SWARM",
  "dev.swarmHelp": "{count} zombies closing in from 50m",
  "dev.basebuild": "BASEBUILD",
  "dev.basebuildHelp": "{count} pieces put up",
  "dev.reset": "RESET",
  "dev.resetHelp": "Back at insertion",
  "dev.badge.music": "MUSIC",
  "dev.badge.bugs": "BUGS",
  "dev.badge.wild": "WILD",
  "dev.badge.night": "NIGHT",
  "dev.badge.horde": "HORDE",
  "dev.badge.gore": "GORE",
  "dev.badge.ball": "BALL",
  "dev.badge.poi": "POI",
  "dev.badge.solid": "SOLID",

  // performance
  "performance.gpu": "gpu   {gpu}",
  "performance.cpu": "cpu   {cpu}",
  "performance.threads": "{count} threads",
  "performance.memory": "{memory}GB",
  "performance.resolution": "res   {width}x{height} @{ratio}x",
  "performance.renderer": "rend  {backend}",
  "performance.fps": "fps   {fps}",
  "performance.worst": "worst {ms}ms",
  "performance.hitches": "hitch {count}",
  "performance.draws": "draws {count}",
  "performance.triangles": "tris  {count}k",
  "performance.zombies": "zombs {count}",
  "performance.webgl": "WebGL2 fallback",
  "performance.unknown": "unknown",

  // tips
  "tips.movement.title": "Movement & looking",
  "tips.movement.move": "{move} / arrows — move: {forward} is up the screen, whichever way you're aiming · {run} — run",
  "tips.movement.jump": "{jump} — jump · {dodge} — dodge roll (can't be hurt mid-roll)",
  "tips.movement.crouch": "{crouch} — crouch: slower, but tighter groups and a lower silhouette",
  "tips.movement.aim": "Mouse — aim anywhere around you; the marine turns to face the reticle while the camera holds still, so shots land where it sits",
  "tips.movement.zoom": "Scroll wheel — zoom the camera in / out (scoped, it dials the magnification)",
  "tips.movement.camera": "Hold the middle mouse button and drag — rotate the camera",
  "tips.movement.tilt": "The tilt looks after itself: the view lifts to look up a hill ahead, drops into a dip, and rises over ground behind you instead of crowding the marine",
  "tips.movement.followCursor": "The camera slides toward the cursor once you point past the middle of the screen, so you see more of what you're aiming at",
  "tips.movement.cameraSettings": "{pause} > Settings > Camera turns both off (with auto tilt off, middle-drag up / down tilts by hand again). Look sensitivity is there too",
  "tips.combat.title": "Combat",
  "tips.combat.fire": "{fire} — fire / hold for the chainsaw and flamethrower · {reload} — reload",
  "tips.combat.scope": "{aim} — zoom. On the sniper it raises a real scope on whatever the reticle is on; the mouse then moves the scope directly (push to the screen edge to swing further). Wheel or middle click — 2X / 4X / 6X",
  "tips.combat.grenade": "{grenade} — grenade · {melee} — knife (or the machete, once bought)",
  "tips.combat.medpen": "{heal} — jab a MedPen (heals 60%). Health only regenerates back to 40% on its own",
  "tips.combat.weapons": "Hold {weaponWheel} — weapon wheel: time slows, point at a gun, let go to draw it · tap {weaponWheel} to step to the next one",
  "tips.interaction.title": "Action key ({interact})",
  "tips.interaction.kiosk": "{interact} at the kiosk (the supply hatch in the east wall of the cabin, yellow square on the map) — weapons, ammo, gear, upgrades, perks, blueprints. Open any time; time stops while you shop. {interact} or {pause} closes it",
  "tips.interaction.bank": "{interact} at the HQ skull window (front of the cabin) — turn in collected skulls for Cash. Kill → pick up glowing skulls → turn in → spend at the kiosk",
  "tips.interaction.alarm": "{interact} at the HQ start panel (front wall) — sound the alarm to start the next wave. Prep lasts until you call it",
  "tips.interaction.mortar": "{interact} at a mortar — man it: {fire} lobs a shell at the reticle (dotted arc), {interact} leaves it, {carry} shoulders it to carry it (no weapons while carrying; {fire} or {interact} sets it down)",
  "tips.building.title": "Building",
  "tips.building.wheel": "Hold {buildWheel} — build wheel (paged): Structure · Defenses · Turrets. Point at a build, let go to pick it · tap {buildWheel} to enter / leave build mode · {fire} place",
  "tips.building.blueprints": "Blueprints unlock builds in the {buildWheel} menu (kiosk → Blueprints). Barricade, shovel, and Upgrade start unlocked; placing most pieces still costs Cash. Fortify blueprints upgrade walls, doors, turrets, and more",
  "tips.building.repair": "{repair} — repair the nearest build · {scrap} — sell / scrap it (hold {scrap} in build mode to preview a scrap box)",
  "tips.building.drums": "Fuel drums: place one, shoot it when the horde is beside it, stand well back — they chain",
  "tips.waves.title": "Waves & enemies",
  "tips.waves.prep": "Prep — no countdown: start the wave at the HQ panel ({interact}). {confirm} only reminds you",
  "tips.waves.caves": "Waves pour out of the six cave mouths at the map rim — the red arcs on the map point at the mouths in use. You can't build within 25m of a mouth, and do NOT walk into one: something lives in there, and it does not lose",
  "tips.waves.streak": "Chain kills fast for a streak: 5 / 10 / 20 / 30 raise skull value AND grant powers while it holds — faster feet, quick reloads, free rounds, thick skin. Lose the streak, lose the powers",
  "tips.waves.minimap": "Minimap: the 50 m around you, turned so up is always the way the camera faces (W). Zombies are the flashing red dots; red arcs on the rim are where the wave comes from",
  "tips.waves.map": "{map} — full map of the whole area, north-up",
  "tips.waves.bombers": "Bombers (glowing gut) sprint and detonate — shoot them before they reach your line, ideally next to other zombies",
  "tips.waves.leapers": "Leapers run on all fours and jump 5–14m onto you — sidestep the landing. Spiders — crawling zombies with six limbs — hang back and web you (slowed): kill them first",
  "tips.waves.demons": "Demons (red, horned, from day 6 — more on Ember Night) stop and roar before they charge in a straight line: sidestep or roll when you hear it. Fire barely hurts them; bullets do",
  "tips.waves.spitters": "Spitters (bloated, olive) don't spit — they walk in and then crawl the last 15m. Easy targets, but they keep coming",
  "tips.waves.blade": "Most of a wave is plain shamblers, and there are a lot of them. Your blade costs nothing: {melee} one-shots shamblers, ferals, leapers and spitters through a near half-circle sweep",
  "tips.waves.drowned": "The drowned only ever come up out of the Underwater Pit in the lake bed and are fast in the water — don't fight near the banks, and never swim over the pit itself: the thing that owns it takes swimmers whole",
  "tips.waves.flamer": "Flamethrower: the stream sticks to what it hits and fizzles in water; burning zombies light whatever they touch, and the ground keeps burning — including under you",
  "tips.economy.title": "Cash & skulls",
  "tips.economy.skulls": "Kills drop skulls (pooled for small payouts). Pick them up — the HUD Skulls line shows how many you carry and what they are worth",
  "tips.economy.bank": "Turn skulls in at the HQ window ({interact}) to convert them to Cash. The Supply Kiosk and builds spend Cash only",
  "tips.economy.supplies": "Starting Cash is a small seed for the first prep. Supply drops can dump ammo and MedPens; rare Cash stacks still go straight to the bank",
  "tips.misc.title": "Misc",
  "tips.misc.pause": "{pause} — pause / resume · {mute} — mute · {fullscreen} — fullscreen",
  "tips.misc.gear": "{nightVision} — night vision (needs the helmet) · {laser} — laser sight · {flashlight} — gun flashlight (all bought at the kiosk)",
  "tips.misc.settings": "Settings: volume, look sensitivity, graphics quality, camera, fullscreen — from the title screen or {pause}",
  "tips.testing.title": "Testing",
  "tips.testing.commands": "~ opens the dev console: \"bigtex shooter\" for unlimited Cash, \"broke\" to turn it off",
  "tips.testing.switches": "URL switches: ?debug=1 perf overlay · ?renderer=webgl WebGL2 fallback · ?sky=flat plain sky",

  // ammo
  "ammo.quantity.rounds": {"one":"{count} round","other":"{count} rounds"},
  "ammo.quantity.shells": {"one":"{count} shell","other":"{count} shells"},
  "ammo.quantity.grenades": {"one":"{count} grenade","other":"{count} grenades"},
  "ammo.quantity.fuel": "{count} fuel",

  // build
  "build.message.scrapAttached": "{scrap} scraps: {name} + {attached} on it — +{refund} Cash",
  "build.message.upgradeTarget": "{name} — {cost} Cash",
  "build.message.upgradePart": "{message} · {rotate}: {part}",
  "build.part.wall": "wall",
  "build.part.door": "door",
  "build.part.window": "window",

  // world
  "world.sign.keepout": "KEEP OUT",
  "world.sign.hazard": "DANGER",

  // a11y
  "a11y.cash": "Cash available: {amount}",
  "a11y.skulls": {"one":"Carrying {count} skull, skull value {value}","other":"Carrying {count} skulls, skull value {value}"},
  "a11y.health": "Health: {hp} of {max}",
  "a11y.armor": "Armor: {armor} of {max}",
  "a11y.weaponWheel": "Weapon wheel",
  "a11y.buildWheel": "Build wheel",
  "a11y.map": "Map",
  "a11y.minimap": "Minimap",
  "a11y.loading": "Loading progress",
  "a11y.coach": "Field guidance",
  "a11y.prep": "Preparation checklist",
  "a11y.settings": "Settings",
  "a11y.wavePreview": "Wave briefing",

  // fieldIntel
  "fieldIntel.name": "Field Intel",
  "fieldIntel.description": "See every enemy type, count and approach at the HQ panel.",
};

// Freeze plural records too: one area cannot accidentally change another's copy.
for (const value of Object.values(messages)) {
  if (typeof value === 'object') Object.freeze(value);
}
export const STRINGS = Object.freeze(messages);

/** True for complete catalogue keys; inherited object properties are never keys. */
export function hasText(key) {
  return typeof key === 'string' && Object.hasOwn(STRINGS, key);
}

/**
 * Format a keyed message. Plural records require an own, nonnegative integer count.
 * Supported values: strings, finite numbers and booleans. Null/missing/object
 * values are caller mistakes, not the literal words 'undefined' or '[object Object]'.
 * Unknown extra parameters are harmless; this lets a view pass its shared state.
 */
export function text(key, params = {}) {
  if (!hasText(key)) throw new RangeError('Unknown text key: ' + String(key));
  if (params === null || typeof params !== 'object' || Array.isArray(params)) {
    throw new TypeError('Text parameters must be an object: ' + key);
  }
  const entry = STRINGS[key];
  let template = entry;
  if (typeof entry === 'object') {
    if (!Object.hasOwn(params, 'count') || !Number.isSafeInteger(params.count) || params.count < 0) {
      throw new TypeError('Text requires a nonnegative integer count: ' + key);
    }
    template = params.count === 1 ? entry.one : entry.other;
  }
  return template.replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g, (placeholder, name) => {
    const supplied = Object.hasOwn(params, name);
    const fallback = Object.hasOwn(DEFAULT_INPUT_LABELS, name);
    if (!supplied && !fallback) throw new TypeError('Missing text parameter ' + name + ': ' + key);
    const value = supplied ? params[name] : DEFAULT_INPUT_LABELS[name];
    if (!['string', 'number', 'boolean'].includes(typeof value) ||
        (typeof value === 'number' && !Number.isFinite(value))) {
      throw new TypeError('Invalid text parameter ' + name + ': ' + key);
    }
    return String(value);
  });
}
