import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/survivor-fit',before=process.argv.includes('--before'),prefix=before?'before':'after',srv=await serve(process.cwd(),0);let browser;const timer=setTimeout(()=>process.exit(2),120000);
try{browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>{if(!errors.includes(e.message))console.error(e.message);errors.push(e.message);});
await p.route('**/index.html*',r=>{let s=fs.readFileSync('index.html','utf8');if(before)for(const{a,b,text}of JSON.parse(fs.readFileSync(out+'/source-before.json','utf8'))){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i);s=s.slice(0,i)+text+s.slice(j);}if(before)s=s.replace('buildMarineHead, buildMarineHair,','buildMarineHead,');return r.fulfill({contentType:'text/html',body:s});});
if(before)await p.route('**/ui/marine-face.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(out+'/face-before.js','utf8')}));
await p.goto(srv.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);await p.evaluate(()=>{document.getElementById('playerName').value='Survivor review';document.getElementById('modeTraining').click();});await p.waitForFunction(()=>TT.trainingDbg.state().active);
await p.evaluate(()=>{TT.getMarine().visible=false;window.FIG={};for(const id of['marine','brandt','okafor','pike']){const m=id==='marine'?TT.makeMarine():TT.makeSurvivorFigure(id);m.position.set(0,-200,-647);TT.scene.add(m);FIG[id]=m;m.visible=false;}const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');});
const shots=[['hair-side','marine',Math.PI/2,true,true],['hair-back','marine',Math.PI,true,true],['hair-quarter','marine',.65,true,true],['cap','pike',2.4,true,false],...['brandt','okafor','pike'].flatMap(w=>[[w+'-front',w,.35,false,false],[w+'-back',w,2.7,false,false],[w+'-side',w,Math.PI/2,false,false]])];
const states={};for(const[id,who,angle,head,noHat]of shots){states[id]=await p.evaluate(({who,angle,head,noHat})=>{for(const[k,m]of Object.entries(FIG))m.visible=k===who;const m=FIG[who],u=m.userData;m.rotation.y=angle;if(who==='marine')for(const[k,list]of Object.entries(u.gearParts))for(const a of list)a.visible=['vest','pads'].includes(k);if(noHat)for(const g of Object.values(u.dress.hats))g.visible=false;const cy=head?1.46:.94,dist=head?1.3:4.7;TT.setShotView({x:0,y:-200+cy+.08,z:-647+dist,tx:0,ty:-200+cy,tz:-647,fov:head?35:32});const rifle=m.getObjectByName('survivor-rifle');return{wardrobe:Object.keys(u.wardrobe).sort(),arms:[u.armLG,u.armRG,u.elbowLG,u.elbowRG].map(g=>g.rotation.toArray().slice(0,3)),rifle:rifle?{position:rifle.position.toArray(),rotation:rifle.rotation.toArray(),visible:rifle.visible}:null};},{who,angle,head,noHat});await p.waitForTimeout(180);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
if(!before){const old=JSON.parse(fs.readFileSync(out+'/before-checks.json','utf8'));for(const k of Object.keys(states))assert.deepEqual(states[k].wardrobe,old.states[k].wardrobe);for(const who of['brandt','okafor','pike'])assert.deepEqual(states[who+'-front'].arms,[[-.02,-.25,-.05],[-.02,.25,.05],[-.22,0,0],[-.22,0,0]]);const checks=await p.evaluate(async()=>{const T=await import('./vendor/three/three.webgpu.js'),result={};for(const who of['okafor','pike']){const m=FIG[who],r=m.getObjectByName('survivor-rifle');m.updateMatrixWorld(true);let lights=0;r.traverse(o=>{if(o.isLight)lights++;});const b=new T.Box3().setFromObject(r),inv=m.matrixWorld.clone().invert(),pts=[];for(const x of[b.min.x,b.max.x])for(const y of[b.min.y,b.max.y])for(const z of[b.min.z,b.max.z])pts.push(new T.Vector3(x,y,z).applyMatrix4(inv));result[who]={lights,axis:new T.Vector3(0,0,1).applyQuaternion(r.quaternion).toArray(),position:r.position.toArray()};}const hair=FIG.marine.getObjectByName('medium-fade');result.hair=!!hair;result.hairColours=[];for(const colour of ['black','blond','auburn']){TT.dressMarine(FIG.marine,{items:{},body:{hair:colour}});result.hairColours.push(hair.children.every(c=>c.material.color===FIG.marine.userData.dress.mats.hair.color));}return result;});for(const who of['okafor','pike']){assert.equal(checks[who].lights,0);assert(checks[who].axis[1]>.97);assert(checks[who].position[2]<-.2);}assert(checks.hair);assert(checks.hairColours.every(Boolean));fs.writeFileSync(out+'/fit-checks.json',JSON.stringify(checks,null,2));console.log('PASS survivor unarmed pose, muzzle-up rear slings, no cloned weapon lights, haircut and wardrobe parity');}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({states,errors},null,2));console.log('PASS '+prefix+' '+shots.length+' views, no page errors');
}finally{clearTimeout(timer);await browser?.close();srv.close();}
