import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/tower/sightline',before=process.argv.includes('--before'),prefix=before?'before':'after';
const server=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
if(before)await p.route('**/index.html?*',async r=>{const response=await r.fetch(),s=await response.text();await r.fulfill({response,body:s.replace(/      \/\/ GP-118 \(Jerry\): Brandt needs[\s\S]*?POI.tower = \{ x: -25, z: -125 \};\s*\n/,'').replace('opacity: 0, depthWrite: false, fog: false, blending:', 'opacity: 0, depthWrite: false, blending:')});});
await p.goto(server.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const data=await p.evaluate(()=>{const{THREE:T}=TT,t=TT.getTowerState().tower;window.SIGHT={t,T};TT.scene.updateMatrixWorld(true);const targets=TT.pitSignal.beams.map(m=>m.getWorldPosition(new T.Vector3()).add(new T.Vector3(0,m.geometry.parameters.height/2-.1,0)));const blockers=[TT.ground,...TT.trees.map(q=>q.group),...TT.rocks.filter(q=>q.alive).map(q=>q.mesh),...TT.landmarks.filter(q=>q!==t&&q.mesh).map(q=>q.mesh)];const rays=[];for(const off of[[0,0],[-.9,-.9],[-.9,.9],[.9,-.9],[.9,.9]]){const eye=new T.Vector3(t.x+off[0],t.deckY+1.65,t.z+off[1]);for(let k=0;k<8;k++){const d=targets[k].clone().sub(eye),len=d.length(),ray=new T.Raycaster(eye,d.normalize(),0,len-.05);const hits=ray.intersectObjects(blockers,true).filter(h=>h.object.visible&&h.object.material?.visible!==false);rays.push({off,stone:k,clear:hits.length===0,first:hits[0]?{name:hits[0].object.name,distance:hits[0].distance}:null});}}
const loc=v=>v&&({x:v.x,z:v.z,kind:v.kind}),poi=Object.fromEntries(Object.entries(TT.POI).filter(([k])=>!['lakeHole','fences'].includes(k)).map(([k,v])=>[k,Array.isArray(v)?v.map(loc):loc(v)]));const ladderGround=TT.sampleHeight(t.ladderX,t.ladderZ);return{tower:{x:t.x,z:t.z,gy:t.gy,deckY:t.deckY,ladderX:t.ladderX,ladderZ:t.ladderZ},ladderGround,ladderGroundDelta:Math.abs(ladderGround-t.gy),pathDistance:TT.rabbitDbg.distToPath(t.ladderX,t.ladderZ),rays,poi,trees:TT.trees.map(q=>({x:q.x,z:q.z})),pit:TT.LAKE_HOLE};});
fs.writeFileSync(out+'/'+prefix+'-visibility.json',JSON.stringify(data,null,2));console.log(JSON.stringify({phase:prefix,clearRays:data.rays.filter(r=>r.clear).length,totalRays:data.rays.length,ladderDelta:data.ladderGroundDelta,pathDistance:data.pathDistance}));
await p.evaluate(fs.readFileSync('tools/tests/lib.js','utf8'));await p.evaluate(()=>startMatch(TT,'Tower sightline'));
await p.evaluate(()=>{const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);});
for(const[id,kind]of[['outlook','eye'],['whole','whole'],['approach','approach']]){await p.evaluate(kind=>{const{t}=SIGHT,h=TT.LAKE_HOLE;const eye=kind==='eye'?{x:t.x+.5,y:t.deckY+1.65,z:t.z}:kind==='whole'?{x:t.x+11,y:t.gy+9,z:t.z-14}:{x:t.x+2,y:t.gy+2,z:t.z-8};const target=kind==='eye'?{tx:h.x,ty:-3.4,tz:h.z}:kind==='whole'?{tx:t.x-9,ty:t.gy+3,tz:t.z}:{tx:t.x,ty:t.gy+3,tz:t.z};TT.setShotView({...eye,...target,fov:kind==='eye'?58:48});},kind);await p.waitForTimeout(300);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:93});}
const pulse=await p.evaluate(()=>{TT.towerDeckDbg();TT.player.position.x+=.85;TT.player.position.z+=.85;TT.setWorldTime(.85);TT.setPitWord([0,2,4,6,7]);TT.setPitSilenced(false);delete TT.pitSignal.freeze;const results=[];for(let i=0;i<5;i++){TT.pitSignal.t=i*1.3+.3;TT.updatePitSignal(0,{night:true});results.push(TT.pitSignal.beams.map((m,k)=>m.visible?k:-1).filter(k=>k>=0));}TT.setOnTowerDeckDbg(false);TT.updatePitSignal(0,{night:true});const groundOff=TT.pitSignal.beams.every(m=>!m.visible);TT.setOnTowerDeckDbg(true);return{results,groundOff};});assert.deepEqual(pulse,{results:[[0],[2],[4],[6],[7]],groundOff:true});
for(const stone of[0,4,7]){await p.evaluate(stone=>{const{t}=SIGHT,h=TT.LAKE_HOLE;TT.pitSignal.freeze={stone,glow:1};TT.updatePitSignal(0,{night:true});TT.setShotView({x:t.x+.5,y:t.deckY+1.65,z:t.z,tx:h.x,ty:-3.4,tz:h.z,fov:58});},stone);await p.waitForTimeout(300);await p.screenshot({path:out+'/'+prefix+'-night-'+stone+'.jpg',type:'jpeg',quality:93});}
assert.deepEqual(errors,[]);if(!before){const prior=JSON.parse(fs.readFileSync(out+'/before-visibility.json'));const strip=o=>{const{tower,...rest}=o;return rest;};assert.deepEqual(JSON.parse(JSON.stringify(strip(data.poi))),strip(prior.poi));assert.deepEqual(data.pit,prior.pit);assert(data.rays.every(r=>r.clear),'Every stone must have a clear ray from five deck positions');assert(data.ladderGroundDelta<.6,'Ladder must remain reachable from ground');assert(data.pathDistance<.1,'Path must meet actual ladder');}
if(!before){await p.evaluate(()=>{delete TT.pitSignal.freeze;TT.setWorldTime(.4);TT.towerDeckDbg();TT.setOnTowerDeckDbg(false);const t=SIGHT.t;TT.player.position.set(t.ladderX,TT.sampleHeight(t.ladderX,t.ladderZ),t.ladderZ);});await p.waitForTimeout(250);await p.keyboard.down('w');try{await p.waitForFunction(()=>TT.getTowerState().onDeck,null,{timeout:8000});}finally{await p.keyboard.up('w');}console.log('PASS actual keyboard climb from new ladder foot onto deck');}
fs.writeFileSync(out+'/'+prefix+'-results.json',JSON.stringify({pageErrors:errors,pulse,clearRays:data.rays.filter(r=>r.clear).length},null,2));console.log('PASS '+prefix+': six actual renderer views; pulse sequence and off-deck gate; '+(before?'baseline recorded':'all 40 stone rays clear, ladder/path reachable, other POIs and Pit unchanged'));
}finally{clearTimeout(stop);await b?.close();server.close();}
