// GP-117: bounded production-renderer tower review.
import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/tower',before=process.argv.includes('--before'),prefix=before?'before':'after';fs.mkdirSync(out,{recursive:true});if(before&&!process.argv.includes('--replay-baseline')){fs.copyFileSync('assets/world/landmark-details.js',out+'/details-before.js');const s=fs.readFileSync('index.html','utf8');fs.writeFileSync(out+'/buildWatchtower-before.txt',s.slice(s.indexOf('    function buildWatchtower('),s.indexOf('    function buildGraveyard(')));}
const server=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));if(process.argv.includes('--replay-baseline')){await p.route('**/assets/world/landmark-details.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(out+'/details-before.js','utf8')}));await p.route('**/index.html?*',async r=>{const response=await r.fetch(),s=await response.text(),a=s.indexOf('    function buildWatchtower('),b=s.indexOf('    function buildGraveyard(');await r.fulfill({response,body:s.slice(0,a)+fs.readFileSync(out+'/buildWatchtower-before.txt','utf8')+s.slice(b)});});}await p.goto(server.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(async()=>{window.TR={T:await import('three'),t:TT.landmarks.find(l=>l.kind==='tower')};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);const t=TR.t;return{tower:{x:t.x,z:t.z,gy:t.gy,deckY:t.deckY,ladderX:t.ladderX,ladderZ:t.ladderZ,colliders:t.colliders.map(s=>({x:s.x,z:s.z,r:s.radius,y0:s.y0,y1:s.y1}))},history:TT.historyProps.group.children.map(o=>({n:o.name,p:o.position.toArray()}))};});console.log(JSON.stringify(state.tower));
if(!before)assert.deepEqual(state,JSON.parse(fs.readFileSync(out+'/before-checks.json')).state);
for(const[id,eye,target]of[['whole',[10,8,-12],[0,3.2,0]],['deck',[4.7,9,-5],[0,5.9,.2]],['gear',[-3,7.4,3],[-.8,5.9,.7]],['table',[3.6,7.5,2.6],[.9,6.1,.6]],['ladder',[2.7,5,-5.5],[0,4,-1.5]],['rail',[-.1,7.9,.1],[-1.43,6.42,0]]]){await p.evaluate(({eye,target})=>{const{t}=TR;TT.setShotView({x:t.x+eye[0],y:t.gy+eye[1],z:t.z+eye[2],tx:t.x+target[0],ty:t.gy+target[1],tz:t.z+target[2],fov:48});},{eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
await p.evaluate(()=>{const t=TR.t,dx=-138-t.x,dz=-104-t.z,n=Math.hypot(dx,dz);TT.setShotView({x:t.x-dx/n*.5,y:t.deckY+1.65,z:t.z-dz/n*.5,tx:-138,ty:-3.4,tz:-104,fov:58});});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-outlook.jpg',type:'jpeg',quality:92});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': seven tower views; no page errors; '+(before?'baseline saved':'tower/ladder/deck/solids/history identical'));
}finally{clearTimeout(stop);await b?.close();server.close();}
