import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/range-usability',before=process.argv.includes('--before'),prefix=before?'before':'after',srv=await serve(process.cwd(),0);let browser;
try{
browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>{if(!errors.includes(e.message))console.error(e.stack);errors.push(e.message);});p.on('console',m=>{if(m.type()==='error')console.error(m.text().slice(0,6000));});
if(process.argv.includes('--diagnose'))await p.route('**/vendor/three/three.webgpu.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('vendor/three/three.webgpu.js','utf8').replace('passEncoderGPU.setPipeline( pipelineGPU );', `if(!pipelineGPU || pipelineGPU.constructor.name!=='GPURenderPipeline') console.error(JSON.stringify({missingPipeline:true,pipelineType:pipelineGPU?.constructor?.name,name:object.name,parents:[object.parent?.name,object.parent?.parent?.name,object.parent?.parent?.parent?.name],material:material.type,materialName:material.name,geometry:object.geometry.type,position:object.position.toArray(),castShadow:object.castShadow})); passEncoderGPU.setPipeline( pipelineGPU );`)}));
await p.route('**/index.html*',r=>{let s=fs.readFileSync('index.html','utf8');if(before)for(const{a,b,text}of JSON.parse(fs.readFileSync(out+'/range-before.json','utf8'))){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i);s=s.slice(0,i)+text+s.slice(j);}if(before)s=s.replace('!training.active && (Math.hypot(p.pos.x, p.pos.z) > TERRAIN_RADIUS || p.pos.y > 20)','Math.hypot(p.pos.x, p.pos.z) > TERRAIN_RADIUS || p.pos.y > 20');if(process.argv.includes('--no-marks'))s=s.replace('createTrainingImpacts(THREE, training.tg)','({clear(){},add(){},count(){return 0}})');s=s.replace('effectLights, muzzleFlashLight, flashlight,','rangeProbe: { status:()=>({fireHeld,mouseFireHeld,currentWeapon,ammo:ammoByWeapon[currentWeapon],unarmed,aim:aimTarget.toArray(),muzzle:getMuzzleWorld().toArray(),projectiles:projectiles.map(p=>({pos:p.pos.toArray(),dir:p.dir.toArray(),life:p.life,age:p.age}))}), aim:()=>aimTarget.toArray(), scope:()=>({pitch:scopePitch,yaw:scopeYaw,amount:scopeAmt}), floor:raycastTerrain, step:()=>updateMouseAim(1/60), point:(x,y,z)=>{const v=new THREE.Vector3(x,y,z).project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};}, ready:()=>{fireCooldown=0;swapT=0;}, fire:()=>{updateMouseAim(1/60);const origin=getMuzzleWorld().clone(),dir=getAimDir().clone();spawnProjectile(false,origin,dir,24,2);for(let i=0;i<20;i++)updateProjectiles(.025);return {origin:origin.toArray(),dir:dir.toArray(),left:projectiles.length};}}, effectLights, muzzleFlashLight, flashlight,');return r.fulfill({contentType:'text/html',body:s});});
if(before)await p.route('**/world/training.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(out+'/training-before.js','utf8')}));
await p.goto(srv.origin+'/index.html?debug=1&raf=timer'+(process.argv.includes('--webgl')?'&renderer=webgl':''),{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});
await p.evaluate(()=>{DWOpening.dismissForTesting();document.getElementById('playerName').value='Range checks';document.getElementById('modeTraining').click();document.activeElement?.blur();});await p.waitForFunction(()=>TT.trainingDbg.state().active);
await p.waitForFunction(()=>!document.getElementById('trainingBlackout')?.classList.contains('on'));
if(!before&&!process.argv.includes('--no-marks')){
 await p.waitForTimeout(1400);
 const initial=await p.evaluate(()=>{const im=TT.trainingDbg.state().impacts;window.markPrograms=0;window.markProgramNames=[];window.markPipelines=[];const b=TT.renderer.backend,original=b.createProgram.bind(b);const originalPipeline=b.createRenderPipeline.bind(b);b.createRenderPipeline=(o,...a)=>{window.markPipelines.push({object:o.object.name,material:o.material.name});return originalPipeline(o,...a);};b.createProgram=(...a)=>{window.markPrograms++;window.markProgramNames.push({name:a[0].name,stage:a[0].stage});return original(...a);};return{count:im.count(),ranges:TT.trainingDbg.tg().group.getObjectsByProperty('name','training-impact-marks').map(m=>m.geometry.drawRange.count)};});
 assert.equal(initial.count,0);assert(initial.ranges.every(n=>n===0),'warm-up quads cleared');
 await p.evaluate(()=>{const tg=TT.trainingDbg.tg(),im=TT.trainingDbg.state().impacts;im.add({solid:{},point:{x:0,y:-198,z:-610.55},normal:{x:0,y:0,z:-1}});for(const t of tg.targets)im.add({solid:{target:t.id??tg.targets.indexOf(t)},point:{x:tg.origin.x+t.x,y:tg.floorY+1.22,z:tg.origin.z+t.z},normal:{x:0,y:0,z:-1}});});
 await p.waitForTimeout(400);
 const warm=await p.evaluate(()=>{const im=TT.trainingDbg.state().impacts,result={initialPrograms:window.markPrograms,names:window.markProgramNames,pipelines:window.markPipelines,marks:im.count()};im.clear();return result;});
 fs.writeFileSync(out+'/impact-warm-checks.json',JSON.stringify({initial,warm},null,2));assert.equal(warm.names.filter(n=>n.name==='training-impact-mark').length,0,'first impact batches must reuse warmed programs');assert(!warm.pipelines.some(p=>p.object==='training-impact-marks'),'first impact must reuse warmed pipelines');assert.equal(warm.marks,6);console.log('PASS first six impact batches: zero impact shader programs/pipelines compiled; warm-up marks cleared');
}
await p.evaluate(()=>{TT.player.position.set(0,-200,-641);TT.setWeapon(TT.WEAPON_ORDER.indexOf('m4'));TT.setShotView({x:0,y:-193,z:-651,tx:0,ty:-199,tz:-627,fov:52});});await p.waitForTimeout(500);
const shots=[];
for(let lane=0;lane<5;lane++){
  const pt=await p.evaluate(i=>{const t=TT.trainingDbg.tg().targets[i],o=TT.trainingDbg.tg().origin;TT.trainingDbg.tg().resetTargets();return TT.rangeProbe.point(o.x+t.x,o.y+1.22,o.z+t.z);},lane);
  await p.mouse.move(pt.x,pt.y);await p.waitForTimeout(100);
  const aim=await p.evaluate(()=>{TT.rangeProbe.step();return TT.rangeProbe.aim();});
  const old=await p.evaluate(()=>TT.trainingDbg.state().hits);
  const flight=await p.evaluate(()=>TT.rangeProbe.fire());await p.waitForTimeout(100);
  const hits=await p.evaluate(()=>TT.trainingDbg.state().hits);shots.push({lane:lane+1,aim,flight,hit:hits>old});
}
if(!before)assert(shots.every(s=>s.hit),'all target centres hit through production muzzle/aim/projectiles: '+JSON.stringify(shots));
// Marks around the range: misses on wall/floor/backstop and a hit on a moving target.
await p.evaluate(()=>{const tg=TT.trainingDbg.tg();tg.resetTargets();for(const [a,b]of [ [[1,-198.6,-615],[1,-198.6,-609]],[[1.3,-198.8,-615],[1.3,-198.8,-609]],[[1.05,-198.9,-615],[1.05,-198.9,-609]],[[6,-198,-644],[9,-198,-644]],[[2,-199,-644],[2,-201,-642]],[[.1,-198.8,-625],[.1,-198.8,-623]]])TT.trainingDbg.round({prev:{x:a[0],y:a[1],z:a[2]},pos:{x:b[0],y:b[1],z:b[2]},hit:false});tg.resetTargets();TT.setShotView({x:3,y:-197,z:-619,tx:.7,ty:-198.65,tz:-610,fov:46});});await p.waitForTimeout(1300);await p.screenshot({path:out+'/'+prefix+'-range-marks.jpg',type:'jpeg',quality:94});
await p.evaluate(()=>TT.setShotView({x:-1,y:-198.4,z:-627,tx:0,ty:-198.78,tz:-624,fov:38}));await p.waitForTimeout(100);await p.screenshot({path:out+'/'+prefix+'-target-marks.jpg',type:'jpeg',quality:94});
if(!before){
 const checks=await p.evaluate(()=>{const tg=TT.trainingDbg.tg(),imp=TT.trainingDbg.state().impacts;for(let i=0;i<180;i++)TT.trainingDbg.round({prev:{x:1,y:-198,z:-612},pos:{x:1,y:-198,z:-609}});return{count:imp.count(),batches:tg.group.getObjectsByProperty('name','training-impact-marks').length};});assert(checks.count<=208);assert.equal(checks.batches,6);
 // Use the live orbit/scope camera, not the screenshot camera, and hold the pointer still.
 await p.evaluate(()=>{TT.setShotView(null);TT.player.position.set(0,-200,-641);TT.setWeapon(TT.WEAPON_ORDER.indexOf('sniper'));TT.trainingDbg.tg().resetTargets();});await p.waitForTimeout(600);
 const pt=await p.evaluate(()=>TT.rangeProbe.point(0,-198.78,-624));await p.mouse.move(pt.x,pt.y);await p.waitForTimeout(120);await p.mouse.down({button:'right'});await p.waitForTimeout(600);
 const scopes=[];for(let i=0;i<8;i++){scopes.push(await p.evaluate(()=>({scope:TT.rangeProbe.scope(),aim:TT.rangeProbe.aim()})));await p.waitForTimeout(60);}await p.screenshot({path:out+'/after-sniper-scope.jpg',type:'jpeg',quality:94});const hitsBefore=await p.evaluate(()=>TT.trainingDbg.state().hits);await p.evaluate(()=>TT.rangeProbe.ready());await p.mouse.down({button:'left'});await p.waitForTimeout(150);await p.mouse.up({button:'left'});console.log('CLICK',await p.evaluate(()=>TT.rangeProbe.status()));await p.waitForFunction(n=>TT.trainingDbg.state().hits>n,hitsBefore,{timeout:5000});await p.mouse.up({button:'right'});
 assert(scopes.every(s=>s.scope.amount>.8&&Math.abs(s.scope.pitch)<.3),'sniper reaches stable target-height scope: '+JSON.stringify(scopes));
 assert(Math.max(...scopes.map(s=>s.scope.pitch))-Math.min(...scopes.map(s=>s.scope.pitch))<.01,'still pointer stable pitch');
 fs.writeFileSync(out+'/scope-checks.json',JSON.stringify(scopes,null,2));
}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-range-checks.json',JSON.stringify({shots,errors},null,2));console.log('PASS '+prefix+' range: '+shots.filter(s=>s.hit).length+'/5 targets from firing line'+(!before?', bounded persistent impacts and stable sniper scope':''));
}finally{await browser?.close();srv.close();}
