import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/training-sound',before=process.argv.includes('--before'),prefix=before?'before':'after',srv=await serve(process.cwd(),0);let browser;
try{
browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required']});const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>{if(!errors.includes(e.message))console.error(e.stack);errors.push(e.message);});p.on('console',m=>{if(m.type()==='error')console.error(m.text().slice(0,6000));});
if(process.argv.includes('--diagnose'))await p.route('**/vendor/three/three.webgpu.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('vendor/three/three.webgpu.js','utf8').replace('passEncoderGPU.setPipeline( pipelineGPU );', `if(!pipelineGPU || pipelineGPU.constructor.name!=='GPURenderPipeline') console.error(JSON.stringify({missingPipeline:true,pipelineType:pipelineGPU?.constructor?.name,name:object.name,parents:[object.parent?.name,object.parent?.parent?.name,object.parent?.parent?.parent?.name],material:material.type,materialName:material.name,geometry:object.geometry.type,position:object.position.toArray(),castShadow:object.castShadow})); passEncoderGPU.setPipeline( pipelineGPU );`)}));
await p.route('**/index.html*',r=>{let s=fs.readFileSync('index.html','utf8');if(before)for(const{a,b,text}of JSON.parse(fs.readFileSync(out+'/range-before.json','utf8'))){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i);s=s.slice(0,i)+text+s.slice(j);}if(before)s=s.replace('!training.active && (Math.hypot(p.pos.x, p.pos.z) > TERRAIN_RADIUS || p.pos.y > 20)','Math.hypot(p.pos.x, p.pos.z) > TERRAIN_RADIUS || p.pos.y > 20');if(process.argv.includes('--no-marks'))s=s.replace('createTrainingImpacts(THREE, training.tg)','({clear(){},add(){},count(){return 0}})');s=s.replace('effectLights, muzzleFlashLight, flashlight,','rangeProbe: { status:()=>({fireHeld,mouseFireHeld,currentWeapon,ammo:ammoByWeapon[currentWeapon],unarmed,aim:aimTarget.toArray(),muzzle:getMuzzleWorld().toArray(),projectiles:projectiles.map(p=>({pos:p.pos.toArray(),dir:p.dir.toArray(),life:p.life,age:p.age}))}), aim:()=>aimTarget.toArray(), scope:()=>({pitch:scopePitch,yaw:scopeYaw,amount:scopeAmt}), floor:raycastTerrain, step:()=>updateMouseAim(1/60), point:(x,y,z)=>{const v=new THREE.Vector3(x,y,z).project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};}, ready:()=>{fireCooldown=0;swapT=0;}, fire:()=>{updateMouseAim(1/60);const origin=getMuzzleWorld().clone(),dir=getAimDir().clone();spawnProjectile(false,origin,dir,24,2);for(let i=0;i<20;i++)updateProjectiles(.025);return {origin:origin.toArray(),dir:dir.toArray(),left:projectiles.length};}}, effectLights, muzzleFlashLight, flashlight,');return r.fulfill({contentType:'text/html',body:s});});
if(before)await p.route('**/world/training.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(out+'/training-before.js','utf8')}));
await p.goto(srv.origin+'/index.html?debug=1&raf=timer'+(process.argv.includes('--webgl')?'&renderer=webgl':''),{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});
await p.evaluate(()=>{DWOpening.dismissForTesting();document.getElementById('playerName').value='Range checks';document.getElementById('modeTraining').click();document.activeElement?.blur();});await p.waitForFunction(()=>TT.trainingDbg.state().active);
await p.waitForFunction(()=>!document.getElementById('trainingBlackout')?.classList.contains('on'));

await p.waitForTimeout(500);
const result=await p.evaluate(async()=>{
 const {AudioSys:A}=await import('./core/audio.js'),tg=TT.trainingDbg.tg(),im=TT.trainingDbg.state().impacts;
 const state=A.trainingState(),music=A.musicState(),mix=A.mixState();
 const proto=AudioContext.prototype,original=proto.createOscillator;let created=0;proto.createOscillator=function(...a){created++;return original.apply(this,a)};
 A.scream();A.bossRoar();A.zombieVoice('shambler','idle');A.thunder();A.distantGroan();A.waveStart();A.musicCue('clear');const blocked=created;
 A.trainingCue('target');const cueNodes=created-blocked;A.setMuted(true);A.trainingCue('spawn');const mutedNodes=created-blocked-cueNodes;A.setMuted(false);proto.createOscillator=original;
 im.clear();im.add({solid:{},point:{x:1,y:-198.6,z:-610.55},normal:{x:0,y:0,z:-1}});im.add({solid:{target:2},point:{x:0,y:-198.78,z:-624},normal:{x:0,y:0,z:-1}});
 const initial=im.count();im.update(16);const full=im.count();im.update(2);const fade=tg.group.getObjectsByProperty('name','training-impact-marks').find(m=>m.parent===tg.group).geometry.attributes.color.getW(0);im.update(2.1);const expired=im.count();
 im.add({solid:{},point:{x:1,y:-198.6,z:-610.55},normal:{x:0,y:0,z:-1}});const reused=im.count();
 return{state,musicPlaying:music.playing,worldTrack:music.front,amb:mix.amb,blocked,cueNodes,mutedNodes,initial,full,fade,expired,reused};
});
assert(result.state.enabled&&result.state.looping);assert.equal(result.state.loopSeconds,24);assert.equal(result.musicPlaying,false);assert.equal(result.worldTrack,null);assert.equal(result.amb,0);assert.equal(result.blocked,0);assert(result.cueNodes>0);assert.equal(result.mutedNodes,0);assert.equal(result.initial,2);assert.equal(result.full,2);assert(Math.abs(result.fade-.5)<.01);assert.equal(result.expired,0);assert.equal(result.reused,1);
await p.evaluate(()=>{TT.setShotView({x:3,y:-197,z:-619,tx:.7,ty:-198.65,tz:-610,fov:46});});await p.waitForTimeout(150);await p.screenshot({path:out+'/marks-fresh.jpg'});
await p.evaluate(()=>TT.trainingDbg.state().impacts.update(18));await p.screenshot({path:out+'/marks-fading.jpg'});
await p.evaluate(()=>TT.trainingDbg.state().impacts.update(3));await p.waitForTimeout(100);await p.screenshot({path:out+'/marks-expired.jpg'});
const wav=await p.evaluate(async()=>{const{createTrainingAudio}=await import('./ui/training-audio.js'),c=new OfflineAudioContext(1,24000*24,24000),a=createTrainingAudio(c,c.destination,c.destination);a.update(.7);const b=await c.startRendering(),data=b.getChannelData(0);let peak=0;for(const x of data)peak=Math.max(peak,Math.abs(x));return{samples:Array.from(data),peak};});
assert(wav.peak>0&&wav.peak<1);const buf=Buffer.alloc(44+wav.samples.length*2);buf.write('RIFF');buf.writeUInt32LE(buf.length-8,4);buf.write('WAVEfmt ',8);buf.writeUInt32LE(16,16);buf.writeUInt16LE(1,20);buf.writeUInt16LE(1,22);buf.writeUInt32LE(24000,24);buf.writeUInt32LE(48000,28);buf.writeUInt16LE(2,32);buf.writeUInt16LE(16,34);buf.write('data',36);buf.writeUInt32LE(buf.length-44,40);wav.samples.forEach((x,i)=>buf.writeInt16LE(Math.round(Math.max(-1,Math.min(1,x))*32767),44+i*2));fs.writeFileSync(out+'/facility-loop.wav',buf);
const exit=await p.evaluate(async()=>{const{AudioSys:A}=await import('./core/audio.js');TT.trainingDbg.leave();return A.trainingState();});assert.equal(exit.enabled,false);assert.deepEqual(errors,[]);fs.writeFileSync(out+'/checks.json',JSON.stringify({result,exit,peak:wav.peak,errors},null,2));console.log('PASS training loop, muted world voices/music/ambience, cues and mute,20s decal life/4s fade/reuse, clean exit; offline24s WAV rendered');
}finally{await browser?.close();srv.close();}
