// GP-111: bounded, real-renderer comparison of the trapper's homestead.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';
const {chromium}=createRequire(import.meta.url)('playwright'),out='review/trapper',before=process.argv.includes('--before'),prefix=before?'before':'after';
fs.mkdirSync(out,{recursive:true});if(before)for(const [src,name]of [['assets/world/campsites.js','camp-before.js'],['world/history-props.js','history-before.js']])fs.copyFileSync(src,out+'/'+name);
const s=await serve(process.cwd(),0);let b;const stop=setTimeout(()=>process.exit(2),120000);
try{b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(s.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);
const state=await p.evaluate(async()=>{window.TR={T:await import('three'),camp:TT.landmarks.find(l=>l.kind==='campsite'&&l.campStyle==='trapper'),hatch:TT.historyProps.parts['cellar-hatch']};const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');TT.setWorldTime(.4);const c=TR.camp;return{placement:TT.historyProps.group.children.map(o=>({name:o.name,position:o.position.toArray(),rotation:o.rotation.toArray()})),taken:TT.historyProps.taken,camp:{x:c.x,z:c.z,yaw:c.campYaw,colliders:c.colliders.map(x=>({x:x.x,z:x.z,r:x.radius,y0:x.y0,y1:x.y1}))}};});
if(!before)assert.deepEqual(state,JSON.parse(fs.readFileSync(out+'/before-checks.json')).state,'All history placements, reservations and campsite colliders unchanged');
for(const [id,eye,target]of [['homestead',[10,9,12],[-.5,.8,-1]],['cabin',[1.6,3.3,3.6],[-2.9,1,-2.6]],['cabin-rear',[-7,4,-7],[-2.9,1,-2.6]],['workbench',[7,4,2],[2.6,.6,-1.7]],['cellar',[2.2,2.4,2.8],[0,.15,0]],['cellar-detail',[.5,.85,1.45],[0,.15,0]],['whole-site',null,null]]){await p.evaluate(({id,eye,target})=>{const {T,camp,hatch}=TR;const world=v=>new T.Vector3(camp.x+Math.cos(camp.campYaw)*v[0]+Math.sin(camp.campYaw)*v[2],camp.gy+v[1],camp.z-Math.sin(camp.campYaw)*v[0]+Math.cos(camp.campYaw)*v[2]);let e,t;if(id.startsWith('cellar')){hatch.updateWorldMatrix(true,true);e=hatch.localToWorld(new T.Vector3(...eye));t=hatch.localToWorld(new T.Vector3(...target));}else if(id==='whole-site'){t=new T.Vector3((camp.x+hatch.position.x)/2,camp.gy+.5,(camp.z+hatch.position.z)/2);e=t.clone().add(new T.Vector3(12,15,17));}else{e=world(eye);t=world(target);}TT.setShotView({x:e.x,y:e.y,z:e.z,tx:t.x,ty:t.y,tz:t.z,fov:45});},{id,eye,target});await p.waitForTimeout(250);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:92});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({state,pageErrors:errors},null,2));console.log('PASS '+prefix+': seven real-renderer views, no page errors; '+(before?'baseline recorded':'history placement/reservations and camp colliders identical'));
}finally{clearTimeout(stop);await b?.close();s.close();}
