import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{serve}from'../tools/serve.mjs';
const{chromium}=createRequire(import.meta.url)('playwright'),out='review/weapon-fidelity',before=process.argv.includes('--before'),prefix=before?'before':'after',srv=await serve(process.cwd(),0);let browser;const timer=setTimeout(()=>process.exit(2),150000);
try{browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await browser.newPage({viewport:{width:1200,height:760}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/index.html*',r=>{let s=fs.readFileSync('index.html','utf8');if(before)for(const{a,b,text}of JSON.parse(fs.readFileSync(out+'/source-before.json','utf8'))){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i);s=s.slice(0,i)+text+s.slice(j);}s=s.replace('window.TT = stampDebugHooks({','window.WF = {copy:carryGunCopy,ext:gunExtLook,heavy:gunHeavyLook,eligible:EXT_MAG_PRICE,offhand:offhandMeshes,reset:resetReloadAnim,sample:(k,t)=>{const prev=[currentWeapon,reloading,reloadWeapon,reloadAnimDuration,reloadTimer,reloadMagDropped];try{currentWeapon=k;reloading=true;reloadWeapon=k;reloadAnimDuration=2;reloadTimer=(1-t)*2;reloadMagDropped=true;updateReloadAnim(0);const u=weaponMeshes[k].userData,g=carryGunCopy(k);return {pos:u.mag.position.toArray(),rot:u.mag.rotation.toArray(),visible:u.mag.visible,base:u.baseMagPos.toArray(),copySize:window.WF.box(g).getSize(new THREE.Vector3()).toArray()};}finally{[currentWeapon,reloading,reloadWeapon,reloadAnimDuration,reloadTimer,reloadMagDropped]=prev;resetReloadAnim();}}}; window.TT = stampDebugHooks({');return r.fulfill({contentType:'text/html',body:s});});
await p.goto(srv.origin+'/index.html?debug=1&raf=timer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.TT&&DWLoad.snapshot().state==='ready',null,{timeout:45000});await p.evaluate(()=>DWOpening.dismissForTesting());await p.waitForFunction(()=>document.getElementById('opening').hidden);await p.evaluate(()=>{document.getElementById('playerName').value='Weapon review';document.getElementById('modeTraining').click();});await p.waitForFunction(()=>TT.trainingDbg.state().active);
await p.evaluate(()=>{TT.getMarine().visible=false;const cv=[...document.querySelectorAll('canvas')].sort((a,b)=>b.clientWidth*b.clientHeight-a.clientWidth*a.clientHeight)[0],keep=new Set();for(let e=cv;e&&e!==document.body;e=e.parentElement)keep.add(e);for(const e of document.body.children)if(!keep.has(e))e.style.setProperty('display','none','important');window.WF.box=g=>{g.updateMatrixWorld(true);const b=new TT.THREE.Box3();g.traverseVisible(o=>{if(o.isMesh&&o.geometry){o.geometry.computeBoundingBox();b.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));}});return b;};});
const kinds=['m4','ak','aa12','shotgun','sniper','minigun','launcher','flamer','chainsaw','uzi','pistol','revolver'],states={};
for(const k of kinds)for(const view of ['side','three','upgrades']){const id=k+'-'+view;states[id]=await p.evaluate(({k,view})=>{const T=TT.THREE,src=TT.weaponMeshes[k];WF.reset();if(WF.eligible[k])WF.ext(src,k,view==='upgrades');WF.heavy(src,k,view==='upgrades');if(src.userData.suppressor)src.userData.suppressor.visible=view==='upgrades';if(window.WG)TT.scene.remove(WG);const g=WF.copy(k);window.WG=g;g.position.set(0,-199,-647);TT.scene.add(g);const b=WF.box(g),c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3()),d=Math.max(s.z,s.y*1.58,.3)*1.22+.1,n=new T.Vector3(1,view==='three'?.38:.025,view==='three'?.65:0).normalize();TT.setShotView({x:c.x+n.x*d,y:c.y+n.y*d,z:c.z+n.z*d,tx:c.x,ty:c.y,tz:c.z,fov:34});return{size:s.toArray(),length:g.userData.length,mag:src.userData.baseMagPos?.toArray(),muzzle:src.userData.muzzleBase?.toArray()};},{k,view});await p.waitForTimeout(100);await p.screenshot({path:out+'/'+prefix+'-'+id+'.jpg',type:'jpeg',quality:91});}
const parts=await p.evaluate(()=>{let kn=TT.knifeMesh?.();if(!kn)TT.scene.traverse(o=>{if(!kn&&o.userData?.knifeModel)kn=o;});window.WP={};for(const[k,part]of[['knife','knifeModel'],['machete','macheteModel']])if(kn?.userData[part])WP[k]=kn.userData[part].clone(true);for(const k of['m240','mortar']){const b=TT.spawnBuild?.(k,0,-647);if(b?.mesh)WP[k]=b.mesh;}return Object.keys(WP);});
for(const k of parts){await p.evaluate(k=>{TT.scene.remove(WG);for(const g of Object.values(WP))g.visible=false;const g=WP[k];g.visible=true;g.position.set(0,-199,-647);TT.scene.add(g);const b=WF.box(g),T=TT.THREE,c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3()),d=Math.max(s.z,s.y*1.58,s.x,.3)*1.8;TT.setShotView({x:c.x+d,y:c.y+d*.3,z:c.z+d*.4,tx:c.x,ty:c.y,tz:c.z,fov:34});},k);await p.waitForTimeout(100);await p.screenshot({path:out+'/'+prefix+'-'+k+'.jpg',type:'jpeg',quality:91});}
const assembly=await p.evaluate(kinds=>{const result=[];for(const k of kinds){const src=TT.weaponMeshes[k];WF.reset();if(WF.eligible[k])WF.ext(src,k,false);WF.heavy(src,k,false);if(src.userData.suppressor)src.userData.suppressor.visible=false;const normal=WF.copy(k),a=WF.box(normal),u=src.userData,mag=u.mag;if(!mag)continue;mag.position.y-=.42;mag.rotation.x+=.7;mag.visible=false;const during=WF.copy(k),b=WF.box(during);result.push({k,restSize:a.getSize(new TT.THREE.Vector3()).toArray(),reloadSize:b.getSize(new TT.THREE.Vector3()).toArray(),sourceStillHidden:!mag.visible});WF.reset();}return result;},kinds);
if(!before){for(const r of assembly){assert(r.sourceStillHidden);r.restSize.forEach((n,i)=>assert(Math.abs(n-r.reloadSize[i])<1e-6,r.k+' assembled copy during reload'));}const old=JSON.parse(fs.readFileSync(out+'/before-checks.json','utf8'));for(const k of Object.keys(states))assert.deepEqual(states[k].muzzle,old.states[k].muzzle,k+' muzzle unchanged');}
const fidelity=before?null:await p.evaluate(()=>{const checks=[];for(const k of Object.keys(WF.eligible)){for(const gun of [TT.weaponMeshes[k],WF.offhand[k]].filter(Boolean)){WF.ext(gun,k,false);const b0=WF.box(gun.userData.mag||gun.userData.tubeExt).getSize(new TT.THREE.Vector3());const root=gun.userData.mag,pose=root?.position.clone(),scale=root?.scale.clone();WF.ext(gun,k,true);const b1=WF.box(root||gun.userData.tubeExt).getSize(new TT.THREE.Vector3());WF.ext(gun,k,false);const b2=WF.box(root||gun.userData.tubeExt).getSize(new TT.THREE.Vector3());checks.push({k,unchangedRoot:!root||(root.position.equals(pose)&&root.scale.equals(scale)),roundTrip:b0.distanceTo(b2)<1e-7,grows:k==='shotgun'||b1.length()>b0.length()+.001});}}const reload=[0,.18,.32,.52,.7,.99,1].map(t=>({t,...WF.sample('uzi',t)}));return{checks,reload};});if(fidelity){for(const c of fidelity.checks)assert(c.unchangedRoot&&c.roundTrip&&c.grows,JSON.stringify(c));for(const r of fidelity.reload){r.copySize.forEach((v,i)=>assert(Math.abs(v-fidelity.reload[0].copySize[i])<1e-6));if(r.t>=.7)assert.deepEqual(r.pos,r.base);}assert(!fidelity.reload.find(r=>r.t===.32).visible);console.log('PASS '+fidelity.checks.length+' upgrade round trips and seven actual Uzi reload poses');}assert.deepEqual(errors,[]);fs.writeFileSync(out+'/'+prefix+'-checks.json',JSON.stringify({states,parts,assembly,fidelity,errors},null,2));console.log('PASS '+prefix+' '+Object.keys(states).length+' weapon views + '+parts.length+' melee/emplacement views; '+assembly.length+' assembled-copy checks '+(!before?'PASS':'baseline recorded'));
}finally{clearTimeout(timer);await browser?.close();srv.close();}
