const fs=require('node:fs'),path=require('node:path');
const dir=__dirname,css=fs.readFileSync('review/trapper/index.html','utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
 ['overview','Room around the churchyard','The church sits farther back with a clear lawn between its broken walls and the player burial row. Nearby houses and loose coffins have their own space.'],
 ['plots','All six plots stay clear','The six original plot locations are unchanged. The church, debris and loose coffins no longer cover them, and ground cover is cleared from the wider cemetery.'],
 ['occupied','Six completed burials','These are the actual six burial setups, created in the running game. The grave markers and mounds remain visible across the whole row.'],
 ['plan','A less crowded layout','The old headstones have wider rows. The east row bends around the existing trail; the bench and broken boundary sit farther out.'],
 ['approach','Space to approach','The open grave and iron-banded coffins sit beyond the main burial area. Their story details remain, with clearer separation from the ordinary headstones.'],
 ['church','The ruined church','The existing stone shell, broken pews and fallen roof remain together in their own footprint, with room around the outside.']
];
const article=([id,title,note])=>`<article><h2>${title}</h2><figure><div class="pair">${['before','after'].map(p=>`<div class="${p}"><div class="label">${p==='before'?'Before':'After'}</div><img src="data:image/jpeg;base64,${fs.readFileSync(path.join(dir,p+'-'+id+'.jpg')).toString('base64')}" alt="${title} ${p}"></div>`).join('')}</div><figcaption>${note}</figcaption></figure></article>`;
fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coldwater · Clear burial plots</title><style>${css}</style><main><header><small>DEAD-WAVE / COLDWATER / OCTOBER 2, 2026</small><h1>A churchyard with room to breathe</h1><p>The player graves stay in their original places. The church, surrounding ruins and older burials now give them space.</p></header><nav>${[['after','After'],['before','Before'],['compare','Side by side']].map(([id,label])=>`<button data-mode="${id}" aria-pressed="${id==='after'}">${label}</button>`).join('')}</nav>${article(views[0])}<div class="grid">${views.slice(1).map(article).join('')}</div><footer><p>Verified in the real renderer: all six burial setups complete; 90 sampled rays find no scenery over the plots. Original plot coordinates, trees, paths, objective sites and unrelated history props are unchanged.</p><p>Full integration, independent play review and load/FPS verification remain pending with the crew.</p></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('Built six-comparison Coldwater gallery.');
