import fs from 'node:fs';
const root=new URL('./',import.meta.url),pic=(p,id)=>'data:image/jpeg;base64,'+fs.readFileSync(new URL(p+'-'+id+'.jpg',root)).toString('base64');
const css=fs.readFileSync(new URL('../trapper/index.html',root),'utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const views=[
['gate','The former supply entrance','Concrete piers, steel straps, repair braces and dead floodlights give the sealed Cordon gate a military checkpoint identity. The existing chain and warning remain.'],
['checkpoint','Where the trucks were checked','An abandoned guard booth, raised inspection barrier and concrete roadside blocks frame the approach. The missing-person board remains beside the gate.'],
['inside','A dirt road into the valley','The broader inside approach curves around the cave hill and existing trees, then joins the established track near the relay. The terrain itself has not been reshaped.'],
['outside','The other side of the gate','Steel leaves, bracing, hinges and a locking bar dress the outside face. This is still a shut perimeter gate, with the original playable boundary intact.'],
['road','Old tyre tracks outside','Twin worn ruts follow the outer hillside, with grass between them and softened edges. They bend around existing trees and fade away beyond the checkpoint.'],
['details','The empty guard post','A radio, logbook and chair remain inside the small booth. The inspection arm was left raised; the heavy Cordon gate is chained shut.'],
['connection','A route that explains the supplies','About 82 metres of dirt approach connects the gate to the existing inland trail. Outside, roughly 70 metres of worn vehicle track suggests the route the convoy once used.']
];
fs.writeFileSync(new URL('index.html',root),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cordon checkpoint · Before and after</title><style>${css}</style><main><header><small>DEAD-WAVE / THE CORDON CHECKPOINT</small><h1>The road in. The gate that stayed shut.</h1><p>Actual in-game pictures of the dressed gate, abandoned checkpoint, inner dirt approach and outer vehicle tracks.</p></header><nav aria-label="Picture comparison"><button data-mode="after" aria-pressed="true">After</button><button data-mode="before" aria-pressed="false">Before</button><button data-mode="compare" aria-pressed="false">Side by side</button></nav>${views.map(([id,title,note],i)=>`${i===1?'<div class="grid">':''}<article><h2>${title}</h2><figure><div class="pair"><div class="before"><div class="label">Before</div><img loading="lazy" src="${pic('before',id)}" alt="${title} before"></div><div class="after"><div class="label">After</div><img loading="lazy" src="${pic('after',id)}" alt="${title} after"></div></div><figcaption>${note}</figcaption></figure></article>${i===views.length-1?'</div>':''}`).join('')}<footer><p>Focused checks passed: route clearance, exact join to the existing trail, unchanged gate location, trees, objective sites and original paths/collision shapes. All seven objective props pass their existing checks. Two static meshes added.</p><p>Independent crew playthrough, full integration and load/FPS acceptance remain pending.</p><a href="../world-story/index.html">Original world photo review</a> · <a href="../medical-wreck/index.html">Medical supply wreck</a></footer></main><script>for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{document.body.className=b.dataset.mode==='after'?'':b.dataset.mode+'-mode';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};</script></html>`);
console.log('PASS: seven matched Cordon comparisons built.');
